In [1]:
import pandas as pd
import re

## Загрузка табличных данных

### Функция для обработки идентификатора для мерджа двух датасетов

In [2]:
def extract_year_id(value):
    """
    Возвращает кортеж (год, идентификатор) или (None, идентификатор) или None.
    Год преобразуется в полный (2000+год).
    """
    if not isinstance(value, str):
        value = str(value)
    value = value.strip()

    # Паттерн: две цифры, дефис, одна и более цифр (год-ид)
    match1 = re.fullmatch(r'^(\d{2})-(\d+)$', value)
    if match1:
        year = int(match1.group(1))
        patient_id = str(match1.group(2))
        return (2000 + year, patient_id)

    # Паттерн: одна и более цифр, дефис, две цифры (ид-год)
    match2 = re.fullmatch(r'^(\d+)-(\d{2})$', value)
    if match2:
        patient_id = str(match2.group(1))
        year = int(match2.group(2))
        return (2000 + year, patient_id)

    # Только цифры (без дефиса) — идентификатор, год неизвестен
    if value.isdigit():
        patient_id = str(value)
        return (None, patient_id)

    return None

### Загрузка данных и обработка идентификатора

In [3]:
table_data = pd.read_excel("./data_raw/DataSet_V49 (2).xlsx")

In [4]:
table_data[['year', 'patient_id']] = table_data['Код пациента'].apply(
    lambda x: pd.Series(extract_year_id(x))
)

## Загрузка данных временных рядов

In [36]:
time_2020 = pd.read_excel("./data_raw/time_series/2020.xlsx", sheet_name=None)
time_2021 = pd.read_excel("./data_raw/time_series/2021.xlsx", sheet_name=None)
time_2022 = pd.read_excel("./data_raw/time_series/2022.xlsx", sheet_name=None)
time_2023 = pd.read_excel("./data_raw/time_series/2023.xlsx", sheet_name=None)
time_2024 = pd.read_excel("./data_raw/time_series/2024.xlsx", sheet_name=None)
time_2025 = pd.read_excel("./data_raw/time_series/2025.xlsx", sheet_name=None)

In [38]:
for sheet_name, df in time_2020.items():
    time_2020[sheet_name] = time_2020[sheet_name].rename({"№иб": "patient_id", "N иб": "patient_id"})

for sheet_name, df in time_2021.items():
    time_2021[sheet_name] = time_2021[sheet_name].rename({"№иб": "patient_id", "N иб": "patient_id"})

for sheet_name, df in time_2022.items():
    time_2022[sheet_name] = time_2022[sheet_name].rename({"№иб": "patient_id", "N иб": "patient_id"})

for sheet_name, df in time_2023.items():
    time_2023[sheet_name] = time_2023[sheet_name].rename({"№иб": "patient_id", "N иб": "patient_id"})

for sheet_name, df in time_2024.items():
    time_2024[sheet_name] = time_2024[sheet_name].rename({"№иб": "patient_id", "N иб": "patient_id"})

for sheet_name, df in time_2025.items():
    time_2025[sheet_name] = time_2025[sheet_name].rename({"№иб": "patient_id", "N иб": "patient_id"})

In [39]:
time_2025

{'Больные':           №иб            ФИО  Возраст            Диагноз   ХЗ    ХЗ1   ХЗ2  \
 0        25-1     Руденок ВН       71     stemi передний   КО  False  True
 1       25-10     Дроздов АИ       65       stemi задний   КО  False  True
 2     25-1000    Несветов КН       60       STEMI задний   КО  False  True
 3     25-1023   Бамбурова НГ       59       STEMI задний   КО  False  True
 4     25-1025      Иньков ОЮ       53  нестабильная, АКШ  КХО  False  True
 ...       ...            ...      ...                ...  ...    ...   ...
 1625    25-97     Батурин АВ       50       нестабильная   КО  False  True
 1626    25-99   Медведчук АА       83             nSTEMI   КО  False  True
 1627   25-993       Басов СА       52       STEMI задний   КО  False  True
 1628   25-997  Мельчакова ОС       71       нестабильная   КО  False  True
 1629   25-998     Комолов СИ       72             nSTEMI   КО  False  True

         ХЗ3      ХЗ4    ХЗ5   ХЗ6  ХЗ7          ХЗ8  ХЗ9             ХЗ10 ХЗ11
 0     45658  45659.0  False   NaN  2.0  Владивосток  NaN              NaN  NaN
 1     45658  45659.0  False   NaN  2.0  Владивосток  NaN              NaN  NaN
 2     45687  45688.0  False   NaN  2.0    прим край  NaN       ЯБЖ, ЯБДПК  NaN
 3     45688  45690.0  False  ОССН  3.0    прим край  NaN              NaN  NaN
 4     45688  45689.0  False   NaN  2.0    прим край  NaN              NaN  NaN
 ...     ...      ...    ...   ...  ...          ...  ...              ...  ...
 1625  45663  45664.0  False   NaN  2.0    прим край  NaN              NaN  NaN
 1626  45663  45665.0  False   NaN  3.0  владивосток  NaN  Сахарный диабет  ХСН
 1627  45687  45688.0  False   NaN  2.0    прим край  NaN              NaN  NaN
 1628  45687  45688.0  False   NaN  2.0    прим край  NaN  Сахарный диабет  NaN
 1629  45687  45688.0  False   NaN  2.0    прим край  NaN              NaN  NaN

 [1630 rows x 16 columns],
 'Монитор_1':        ID визита    Пациент  N иб            Время поступления  \
 0          17624    Руденок     1  2025-01-01 05:49:14.6500000
 1          17624    Руденок     1  2025-01-01 05:49:14.6500000
 2          17624    Руденок     1  2025-01-01 05:49:14.6500000
 3          17624    Руденок     1  2025-01-01 05:49:14.6500000
 4          17624    Руденок     1  2025-01-01 05:49:14.6500000
 ...          ...        ...   ...                          ...
 71718      19555  Зяблитсов  2599  2025-08-29 14:20:46.6700000
 71719      19555  Зяблитсов  2599  2025-08-29 14:20:46.6700000
 71720      19555  Зяблитсов  2599  2025-08-29 14:20:46.6700000
 71721      19555  Зяблитсов  2599  2025-08-29 14:20:46.6700000
 71722      19555  Зяблитсов  2599  2025-08-29 14:20:46.6700000

        День пребывания                    chartTime  tº, C  АД    нАД   ЧСС  \
 0                  1.0  2025-01-01 06:00:00.0000000   36.2 NaN    NaN   NaN
 1                  1.0  2025-01-01 06:37:00.0000000    NaN NaN  118.0   NaN
 2                  1.0  2025-01-01 06:40:00.0000000    NaN NaN    NaN  65.0
 3                  1.0  2025-01-01 06:45:00.0000000    NaN NaN    NaN  64.0
 4                  1.0  2025-01-01 06:49:00.0000000    NaN NaN  113.0   NaN
 ...                ...                          ...    ...  ..    ...   ...
 71718              2.0  2025-08-30 12:35:00.0000000    NaN NaN   64.0   NaN
 71719              2.0  2025-08-30 12:44:00.0000000    NaN NaN   80.0   NaN
 71720              2.0  2025-08-30 12:54:00.0000000    NaN NaN   91.0   NaN
 71721              2.0  2025-08-30 13:00:00.0000000    NaN NaN    NaN  76.0
 71722              2.0  2025-08-30 13:05:00.0000000    NaN NaN  105.0   NaN

        ...  ВГОК  ВСВЛ  МОК (УЗИ)  tº крови, C  \
 0      ...   NaN   NaN        NaN          NaN
 1      ...   NaN   NaN        NaN          NaN
 2      ...   NaN   NaN        NaN          NaN
 3      ...   NaN   NaN        NaN          NaN
 4      ...   NaN   NaN        NaN          NaN
 ...    ...   ...   ...        ...          ...
 71718  ...   NaN   NaN        NaN          NaN
 71719  ...   NaN   NaN        NaN          NaN
 71720  ...   NaN   NaN        NaN          NaN
 71721  ...   NaN   NaN        NaN          NaN
 71722  ...   NaN   NaN        NaN          NaN

        Пульсация лучевой артерии, лев.  Пульсация лучевой артерии, прав.  \
 0                                  NaN                               NaN
 1                                  NaN                               NaN
 2                                  NaN                               NaN
 3                                  NaN                               NaN
 4                                  NaN                               NaN
 ...                                ...                               ...
 71718                              NaN                               NaN
 71719                              NaN                               NaN
 71720                              NaN                               NaN
 71721                              NaN                               NaN
 71722                              NaN                               NaN

        Проверка CSM  Наполнение капилляров  Парадоксальный пульс  \
 0               NaN                    NaN                   NaN
 1               NaN                    NaN                   NaN
 2               NaN                    NaN                   NaN
 3               NaN                    NaN                   NaN
 4               NaN                    NaN                   NaN
 ...             ...                    ...                   ...
 71718           NaN                    NaN                   NaN
 71719           NaN                    NaN                   NaN
 71720           NaN                    NaN                   NaN
 71721           NaN                    NaN                   NaN
 71722           NaN                    NaN                   NaN

        Лодыжечно-плечевой индекс
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 ...                          ...
 71718                        NaN
 71719                        NaN
 71720                        NaN
 71721                        NaN
 71722                        NaN

 [71723 rows x 51 columns],
 'Монитор_2':        ID визита  Пациент  N иб            Время поступления  День пребывания  \
 0          17631  Поливко    58  2025-01-03 14:52:02.9500000                1
 1          17631  Поливко    58  2025-01-03 14:52:02.9500000                1
 2          17631  Поливко    58  2025-01-03 14:52:02.9500000                1
 3          17631  Поливко    58  2025-01-03 14:52:02.9500000                1
 4          17631  Поливко    58  2025-01-03 14:52:02.9500000                1
 ...          ...      ...   ...                          ...              ...
 94598      19622  Галимов  5926  2025-09-07 16:58:06.3430000               11
 94599      19622  Галимов  5926  2025-09-07 16:58:06.3430000               11
 94600      19622  Галимов  5926  2025-09-07 16:58:06.3430000               11
 94601      19622  Галимов  5926  2025-09-07 16:58:06.3430000               11
 94602      19622  Галимов  5926  2025-09-07 16:58:06.3430000               11

                          chartTime  tº, C  АД    нАД   ЧСС  ...  ВГОК  ВСВЛ  \
 0      2025-01-03 15:04:00.0000000    NaN NaN  141.0   NaN  ...   NaN   NaN
 1      2025-01-03 15:05:00.0000000    NaN NaN    NaN  76.0  ...   NaN   NaN
 2      2025-01-03 15:10:00.0000000    NaN NaN    NaN  80.0  ...   NaN   NaN
 3      2025-01-03 15:15:00.0000000    NaN NaN    NaN  80.0  ...   NaN   NaN
 4      2025-01-03 15:20:00.0000000    NaN NaN    NaN  77.0  ...   NaN   NaN
 ...                            ...    ...  ..    ...   ...  ...   ...   ...
 94598  2025-09-09 07:21:00.0000000    NaN NaN   79.0   NaN  ...   NaN   NaN
 94599  2025-09-09 07:30:00.0000000    NaN NaN    NaN  81.0  ...   NaN   NaN
 94600  2025-09-09 08:00:00.0000000    NaN NaN    NaN  77.0  ...   NaN   NaN
 94601  2025-09-09 09:52:00.0000000    NaN NaN  170.0   NaN  ...   NaN   NaN
 94602  2025-09-09 10:00:00.0000000    NaN NaN    NaN  67.0  ...   NaN   NaN

        МОК (УЗИ)  tº крови, C  Пульсация лучевой артерии, лев.  \
 0            NaN          NaN                              NaN
 1            NaN          NaN                              NaN
 2            NaN          NaN                              NaN
 3            NaN          NaN                              NaN
 4            NaN          NaN                              NaN
 ...          ...          ...                              ...
 94598        NaN          NaN                              NaN
 94599        NaN          NaN                              NaN
 94600        NaN          NaN                              NaN
 94601        NaN          NaN                              NaN
 94602        NaN          NaN                              NaN

        Пульсация лучевой артерии, прав.  Проверка CSM  Наполнение капилляров  \
 0                                   NaN           NaN                    NaN
 1                                   NaN           NaN                    NaN
 2                                   NaN           NaN                    NaN
 3                                   NaN           NaN                    NaN
 4                                   NaN           NaN                    NaN
 ...                                 ...           ...                    ...
 94598                               NaN           NaN                    NaN
 94599                               NaN           NaN                    NaN
 94600                               NaN           NaN                    NaN
 94601                               NaN           NaN                    NaN
 94602                               NaN           NaN                    NaN

        Парадоксальный пульс  Лодыжечно-плечевой индекс
 0                       NaN                        NaN
 1                       NaN                        NaN
 2                       NaN                        NaN
 3                       NaN                        NaN
 4                       NaN                        NaN
 ...                     ...                        ...
 94598                   NaN                        NaN
 94599                   NaN                        NaN
 94600                   NaN                        NaN
 94601                   NaN                        NaN
 94602                   NaN                        NaN

 [94603 rows x 51 columns],
 'Монитор_3':        ID визита    Пациент  N иб            Время поступления  \
 0          17633    Шпакова    60  2025-01-03 15:58:06.3070000
 1          17633    Шпакова    60  2025-01-03 15:58:06.3070000
 2          17633    Шпакова    60  2025-01-03 15:58:06.3070000
 3          17633    Шпакова    60  2025-01-03 15:58:06.3070000
 4          17633    Шпакова    60  2025-01-03 15:58:06.3070000
 ...          ...        ...   ...                          ...
 44241      20035  Забродина  6259  2025-11-01 16:02:22.1900000
 44242      20035  Забродина  6259  2025-11-01 16:02:22.1900000
 44243      20035  Забродина  6259  2025-11-01 16:02:22.1900000
 44244      20035  Забродина  6259  2025-11-01 16:02:22.1900000
 44245      20035  Забродина  6259  2025-11-01 16:02:22.1900000

        День пребывания                    chartTime  tº, C  АД    нАД   ЧСС  \
 0                    1  2025-01-03 16:04:00.0000000    NaN NaN   71.0   NaN
 1                    1  2025-01-03 16:05:00.0000000    NaN NaN    NaN  73.0
 2                    1  2025-01-03 16:10:00.0000000    NaN NaN    NaN  66.0
 3                    1  2025-01-03 16:15:00.0000000    NaN NaN    NaN  66.0
 4                    1  2025-01-03 16:20:00.0000000    NaN NaN    NaN  67.0
 ...                ...                          ...    ...  ..    ...   ...
 44241                2  2025-11-02 08:20:00.0000000    NaN NaN   72.0   NaN
 44242                2  2025-11-02 08:30:00.0000000    NaN NaN    NaN  74.0
 44243                2  2025-11-02 08:35:00.0000000    NaN NaN   77.0   NaN
 44244                2  2025-11-02 09:05:00.0000000    NaN NaN  144.0   NaN
 44245                2  2025-11-02 09:20:00.0000000    NaN NaN   75.0   NaN

        ...  ВГОК  ВСВЛ  МОК (УЗИ)  tº крови, C  \
 0      ...   NaN   NaN        NaN          NaN
 1      ...   NaN   NaN        NaN          NaN
 2      ...   NaN   NaN        NaN          NaN
 3      ...   NaN   NaN        NaN          NaN
 4      ...   NaN   NaN        NaN          NaN
 ...    ...   ...   ...        ...          ...
 44241  ...   NaN   NaN        NaN          NaN
 44242  ...   NaN   NaN        NaN          NaN
 44243  ...   NaN   NaN        NaN          NaN
 44244  ...   NaN   NaN        NaN          NaN
 44245  ...   NaN   NaN        NaN          NaN

        Пульсация лучевой артерии, лев.  Пульсация лучевой артерии, прав.  \
 0                                  NaN                               NaN
 1                                  NaN                               NaN
 2                                  NaN                               NaN
 3                                  NaN                               NaN
 4                                  NaN                               NaN
 ...                                ...                               ...
 44241                              NaN                               NaN
 44242                              NaN                               NaN
 44243                              NaN                               NaN
 44244                              NaN                               NaN
 44245                              NaN                               NaN

        Проверка CSM  Наполнение капилляров  Парадоксальный пульс  \
 0               NaN                    NaN                   NaN
 1               NaN                    NaN                   NaN
 2               NaN                    NaN                   NaN
 3               NaN                    NaN                   NaN
 4               NaN                    NaN                   NaN
 ...             ...                    ...                   ...
 44241           NaN                    NaN                   NaN
 44242           NaN                    NaN                   NaN
 44243           NaN                    NaN                   NaN
 44244           NaN                    NaN                   NaN
 44245           NaN                    NaN                   NaN

        Лодыжечно-плечевой индекс
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 ...                          ...
 44241                        NaN
 44242                        NaN
 44243                        NaN
 44244                        NaN
 44245                        NaN

 [44246 rows x 51 columns],
 'ИВЛ':        ID визита    Пациент  N иб            Время поступления  \
 0          17624    Руденок     1  2025-01-01 05:49:14.6500000
 1          17626  Сидоренко    20  2025-01-01 15:45:17.5230000
 2          17626  Сидоренко    20  2025-01-01 15:45:17.5230000
 3          17626  Сидоренко    20  2025-01-01 15:45:17.5230000
 4          17626  Сидоренко    20  2025-01-01 15:45:17.5230000
 ...          ...        ...   ...                          ...
 59102      20035  Забродина  6259  2025-11-01 16:02:22.1900000
 59103      20035  Забродина  6259  2025-11-01 16:02:22.1900000
 59104      20035  Забродина  6259  2025-11-01 16:02:22.1900000
 59105      20035  Забродина  6259  2025-11-01 16:02:22.1900000
 59106      20035  Забродина  6259  2025-11-01 16:02:22.1900000

        День пребывания                    chartTime Режим ИВЛ  \
 0                    1  2025-01-01 21:00:00.0000000       NaN
 1                    1  2025-01-01 21:00:00.0000000       NaN
 2                    2  2025-01-02 05:00:00.0000000       NaN
 3                    2  2025-01-02 10:30:00.0000000       NaN
 4                    2  2025-01-02 11:30:00.0000000       NaN
 ...                ...                          ...       ...
 59102               10  2025-11-02 03:00:00.0000000       NaN
 59103               10  2025-11-02 07:00:00.0000000       NaN
 59104               10  2025-11-02 07:30:00.0000000       NaN
 59105               10  2025-11-02 08:00:00.0000000       NaN
 59106               10  2025-11-02 08:30:00.0000000       NaN

        Дыхательный объём на выдохе  Минутный объем выдоха  Частота ИВЛ  FiO2  \
 0                              NaN                    NaN          NaN  21.0
 1                              NaN                    NaN          NaN  35.0
 2                              NaN                    NaN          NaN  21.0
 3                              NaN                    NaN          NaN   NaN
 4                              NaN                    NaN          NaN   NaN
 ...                            ...                    ...          ...   ...
 59102                          NaN                    NaN          NaN   NaN
 59103                          NaN                    NaN          NaN   NaN
 59104                          NaN                    NaN          NaN   NaN
 59105                          NaN                    NaN          NaN   NaN
 59106                          NaN                    NaN          NaN   NaN

        ПДКВ  Отношение PaO2/FiO2  ROX-index  VR
 0       NaN                  NaN        NaN NaN
 1       NaN                  NaN        NaN NaN
 2       NaN                  NaN        NaN NaN
 3       NaN                  NaN        NaN NaN
 4       NaN                  NaN        NaN NaN
 ...     ...                  ...        ...  ..
 59102   NaN                  NaN        NaN NaN
 59103   NaN                  NaN        NaN NaN
 59104   NaN                  NaN        NaN NaN
 59105   NaN                  NaN        NaN NaN
 59106   NaN                  NaN        NaN NaN

 [59107 rows x 15 columns],
 'Балансы':       ID визита     Пациент  N иб            Время поступления  \
 0         17624     Руденок     1  2025-01-01 05:49:14.6500000
 1         17624     Руденок     1  2025-01-01 05:49:14.6500000
 2         17624     Руденок     1  2025-01-01 05:49:14.6500000
 3         17625     Дроздов    10  2025-01-01 13:11:13.9400000
 4         17625     Дроздов    10  2025-01-01 13:11:13.9400000
 ...         ...         ...   ...                          ...
 4691      19980  Коломейчук  6330  2025-10-26 16:27:59.1070000
 4692      19980  Коломейчук  6330  2025-10-26 16:27:59.1070000
 4693      19990   Щербинина  6323  2025-10-28 13:25:53.9070000
 4694      20035   Забродина  6259  2025-11-01 16:02:22.1900000
 4695      20035   Забродина  6259  2025-11-01 16:02:22.1900000

       День пребывания  ВСЕГО В ЗОНД/PER OS (с 7.00)  \
 0                   0                         100.0
 1                   1                         603.0
 2                   2                         201.0
 3                   1                         201.0
 4                   2                         201.0
 ...               ...                           ...
 4691                1                         300.0
 4692                2                         201.0
 4693                1                         200.5
 4694                1                         600.0
 4695                2                           0.0

       ВСЕГО ТРАНСФУЗИИ (с 7.00)  ВСЕГО ИНФУЗИИ (с 7.00)  \
 0                           NaN                     NaN
 1                           NaN                    10.0
 2                           NaN                     0.0
 3                           NaN                    70.0
 4                           NaN                    15.0
 ...                         ...                     ...

In [35]:
print(time_2020["Больные"])

None

In [25]:
time_2021["Больные"].head(4)

,№иб,ФИО,Возраст,Диагноз,ХЗ,ХЗ1,ХЗ2,ХЗ3,ХЗ4,ХЗ5,ХЗ6,ХЗ7,ХЗ8,ХЗ9,ХЗ10,ХЗ11
0,21-10,Сальникова ВС,81,STEMI передний,КО,False,True,44197,44198,False,ОССН,2,прим край,NaN,ХСН,NaN
1,21-10019,Гаевский АИ,60,stemi передний,КО,False,True,44355,44362,False,"ОССН, кардиогенный шок",8,Владивосток,NaN,Сахарный диабет,NaN
2,21-10020,Родин ВВ,61,нестабильная,КХО,False,True,44355,44356,False,NaN,2,Прим край,NaN,NaN,NaN
3,21-10022,Оболонин АГ,66,нестабильная,КХО,False,True,44355,44356,False,NaN,2,Прим край,NaN,ХСН,NaN

In [26]:
time_2022["Больные"].head(4)

,№иб,ФИО,Возраст,Диагноз,ХЗ,ХЗ1,ХЗ2,ХЗ3,ХЗ4,ХЗ5,ХЗ6,ХЗ7,ХЗ8,ХЗ9,ХЗ10,ХЗ11
0,22-10,Сакирко ВС,82,нестабильная,КО,False,True,44562,44562,False,NaN,1,прим край,NaN,ХСН,NaN
1,22-10025,Сирота ВА,73,nSTEMI,КО,False,True,44700,44701,False,NaN,2,прим край,NaN,ХСН,NaN
2,22-10032,Сенькина НН,41,ТЭЛА,КО,False,True,44700,44701,False,ОДН,2,прим край,NaN,NaN,NaN
3,22-10034,Продан ВБ,71,nSTEMI,КО,False,True,44700,44701,False,NaN,2,прим край,NaN,ХСН,NaN

In [27]:
time_2023["Больные"].columns

Index(['№иб', 'ФИО', 'Возраст', 'Диагноз', 'ХЗ', 'ХЗ1', 'ХЗ2', 'ХЗ3', 'ХЗ4',
       'ХЗ5', 'ХЗ6', 'ХЗ7', 'ХЗ8', 'ХЗ9', 'ХЗ10', 'ХЗ11'],
      dtype='object')

In [13]:
time_2024["Больные"].head(4)

,№иб,ФИО,Возраст,Диагноз,ХЗ,ХЗ1,ХЗ2,ХЗ3,ХЗ4,ХЗ5,ХЗ6,ХЗ7,ХЗ8,ХЗ9,ХЗ10,ХЗ11
0,24-25444(1),Ким ЛВ,65,нестабильность грудины,КХО,True,True,45299,45301,False,"анемический, ОССН",3,владивосток,NaN,Сахарный диабет,ХСН
1,24-1,Акопян ГС,44,stemi передний,КО,False,True,45292,45293,False,NaN,2,Владивосток,NaN,NaN,NaN
2,24-10002,Малая ЛД,72,нестабильная,КО,False,True,45429,45430,False,NaN,2,прим край,ХБП,Сахарный диабет,ХСН
3,24-10002,Малая ЛД,72,нестабильная,КО,True,True,45433,45436,False,ОПН,4,прим край,NaN,Сахарный диабет,ХСН

In [14]:
time_2025["Больные"].head(4)

,№иб,ФИО,Возраст,Диагноз,ХЗ,ХЗ1,ХЗ2,ХЗ3,ХЗ4,ХЗ5,ХЗ6,ХЗ7,ХЗ8,ХЗ9,ХЗ10,ХЗ11
0,25-1,Руденок ВН,71,stemi передний,КО,False,True,45658,45659.0,False,NaN,2.0,Владивосток,NaN,NaN,NaN
1,25-10,Дроздов АИ,65,stemi задний,КО,False,True,45658,45659.0,False,NaN,2.0,Владивосток,NaN,NaN,NaN
2,25-1000,Несветов КН,60,STEMI задний,КО,False,True,45687,45688.0,False,NaN,2.0,прим край,NaN,"ЯБЖ, ЯБДПК",NaN
3,25-1023,Бамбурова НГ,59,STEMI задний,КО,False,True,45688,45690.0,False,ОССН,3.0,прим край,NaN,NaN,NaN

In [19]:
time_2025["Монитор_1"].head(3)

,ID визита,Пациент,N иб,Время поступления,День пребывания,chartTime,"tº, C",АД,нАД,ЧСС,...,ВГОК,ВСВЛ,МОК (УЗИ),"tº крови, C","Пульсация лучевой артерии, лев.","Пульсация лучевой артерии, прав.",Проверка CSM,Наполнение капилляров,Парадоксальный пульс,Лодыжечно-плечевой индекс
0,17624,Руденок,1,2025-01-01 05:49:14.6500000,1.0,2025-01-01 06:00:00.0000000,36.2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17624,Руденок,1,2025-01-01 05:49:14.6500000,1.0,2025-01-01 06:37:00.0000000,NaN,NaN,118.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17624,Руденок,1,2025-01-01 05:49:14.6500000,1.0,2025-01-01 06:40:00.0000000,NaN,NaN,NaN,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN