# Обработка и анализ табличных данных

In [1]:
import pandas as pd

In [2]:
table_data = pd.read_excel("./data_raw/DataSet_V49 (2).xlsx")

### Пустые или неинформативные даныне

In [6]:
table_data.drop(["Bypass#", 'Повторная оперция', 'Тип повторной операции', 'Плохая мобильность', 'Открытая перация на сердце в анамнезе', 
                 'Ход операции', 'Протокол коронарографии', 'Коррекция А-В блокады', 'Исход А-В блокады', 'Начало А-В блокады (До/после ЧКВ)',
                   'Инфаркт-зависимая артерия(Огригированная)', 'Инфаркт-зависимая артерия(Огригированная)2', 'Unnamed: 344',
                   'SYNTAX Score', 'ОНМК (гем) в анамнезе', 'Калий', 'ФЖ', 'Пробежки ЖТ', 'Рецидивирующая ЖТ', 'ХСН стадия', 'АГ', 
                   'Стенокардия ФК (ИБ)', 'ЖКБ', 'EDV', 'Недостаточность аортального клапана (степень)', 'Стеноз митрального клапана (степень)',
                   'Недостаточность митрального клапана (степень)', 'Недостаточность трикуспидального клапана (степень)', 'НПВ', 'Продолжительность операции',
                   'Причина смерти', 'PQ', 'QRS', 'QT', 'RR', 'Моноциты (абсолютное значение)(a)', 'Эозинофилы (абсолютное значение)(a)', 'Базофилы (абсолютное значение)(a)',
                   'СОЭ(a)', 'Эозинофилы(%)(a)', 'Палочкоядерные нейтрофилы(%)(a)', 'Миелоциты(%)(a)', 'Общий белок(a)', 'Триглицериды(a)', 'ЛДГ(a)', 'eGFR (a)',
                   'Тропонин 1 (b)', 'Тропонин 1 > 0.1 (b)', 'Тропонин 1 (a)', 'Тропонин 1 > 0.1 (a)', 'Тропонин 1', 'Тропонин 1 > 0.1', 'Индекс курения',
                   'Время ЧКВ', 'А-В блокада (степень)', 'Летальный исход икка', 'Диагноз', 'Дата и время развития SOFA 8 и более', 'Часов в ОРИТ ДО развития SOFA 8',
                   'Часов в ОРИТ ПОСЛЕ развития SOFA 8', 'Максимальный прокальцитонин за сутки до развития SOFA 8', 'Максимальный ЛАКТАТ артерия за сутки до развития SOFA 8',
                   'Максимальный ЛАКТАТ вена за сутки до развития SOFA 8', 'Максимальный ЛАКТАТ артерия за сутки после развития SOFA 8',
                   'Максимальный ЛАКТАТ вена за сутки после развития SOFA 8', 'SOFA первый раз больше или равна 8 баллам', 'SOFA до развития 8 и более баллов',
                   'Используемый антибиотик ДО развития SOFA 8 и более', 'Левофлоксацин антибиотик ДО развития SOFA 8 и более', 'Линезолид антибиотик ДО развития SOFA 8 и более',
                   'Меропенем антибиотик ДО развития SOFA 8 и более', 'Метронидазол антибиотик ДО развития SOFA 8 и более', 'Моксифлоксацин антибиотик ДО развития SOFA 8 и более',
                   'Нифуроксазид антибиотик ДО развития SOFA 8 и более', 'Фосфомицин антибиотик ДО развития SOFA 8 и более', 'Цефазолин антибиотик ДО развития SOFA 8 и более',
                   'Сульбактам антибиотик ДО развития SOFA 8 и более', 'Цефоперазон антибиотик ДО развития SOFA 8 и более', 'Цефтриаксон антибиотик ДО развития SOFA 8 и более',
                   'Количество часов применения антибиотика ДО развития SOFA 8 и более', 'Антибиотик после развития SOFA 8 и более', 'Моксифлоксацин после развития SOFA 8 и более',
                   'Левофлоксацин после развития SOFA 8 и более', 'Азитромицин после развития SOFA 8 и более', 'Линезолид после развития SOFA 8 и более', 'Меропенем после развития SOFA 8 и более',
                   'Метронидазол после развития SOFA 8 и более', 'Нифуроксазид после развития SOFA 8 и более', 'Фосфомицин после развития SOFA 8 и более', 'Цефазолин после развития SOFA 8 и более',
                   'Сульбактам после развития SOFA 8 и более', 'Цефепим после развития SOFA 8 и более', 'Цефтриаксон после развития SOFA 8 и более', 'Через сколько часов после развития SOFA 8 и более был введен антибиотик',
                   'APACHE сутки до развития SOFA 8 и более', 'APACHE сутки ПОСЛЕ развития SOFA 8 и более', 'АД среднее за сутки до развития SOFA 8'], 
                   axis=1, inplace=True)

### Обработка типов данных колонок

В ходе работы с данными выяснилось, что есть дубликаты - повторные записи пациентов в зависимости от повторных госпитализаций

Для решаемой задачи классификации это не является проблемой, так как каждая отдельная госпитализация рассматривается как отдельный случай и мы смотрим на риски неблагоприятного исхода в тот или иной момент госпитализации. 

Но, если мы начинаем разбивать нашу выборку на обучающую, тестовую и валидационную, то возникнет проблема - модель увидит одного и того же пациента в разных выборках и переобучится. Это решается с помощью стратифицированного разбиения пациентов по id (GroupKFold или train_test_split с группировкой на пациента)

In [7]:
table_data.head(3)

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,STEMI,ЧКВ,Дата STEMI,Вид STEMI,...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
0,20-6545,Хасьянов РА,78.0,М,Да,Да,Нет,Да,NaN,NaN,...,-5.0,18.5,18.5,18.5,18.5,18.5,18.5,NaN,NaN,NaN
1,19-22109,Тюркова ГГ,80.0,Ж,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17-13439,Ремизов РВ,40.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
counts = table_data["Name"].value_counts()
duplicated_names = counts[counts > 1].index.to_list()
duplicated_df = table_data[table_data["Name"].isin(duplicated_names)]

duplicated_df

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,STEMI,ЧКВ,Дата STEMI,Вид STEMI,...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
0,20-6545,Хасьянов РА,78.0,М,Да,Да,Нет,Да,NaN,NaN,...,-5.0,18.5,18.5,18.5,18.5,18.5,18.5,NaN,NaN,NaN
11,975,Щетинкин ЮВ,56.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,590,Вирич ВИ,75.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1722,Бабич АП,65.0,Ж,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,17-12105,Бабаев СН,59.0,NaN,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17419,10407,Ефименко ВИ,64.0,М,Да,Да,Да,Да,2015-07-16 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17425,10019,Гаевский АИ,60.0,М,Да,Да,Да,Да,2021-06-08 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17427,1,Халиман ОА,48.0,М,Да,Да,Да,Да,2020-01-01 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17428,2024-06-18 00:00:00,Журавлев АЮ,50.0,М,Да,Да,Да,Да,2018-01-01 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17429,2024-04-19 00:00:00,Петров ВЮ,53.0,М,Да,Да,Да,Да,2018-12-31 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Всего записей-дубликатов - около 5к. 

Почти все из них - это повторные госпитализации. Вероятно, среди них есть и полные дубликаты записей, и некорректные строки. 
Все такие записи имеют уникальный код пациента

## Обработка данных

В ходе анализа датасета были выявлены МНОГОЧИСЛЕННЫЕ ошибки в формировании и заполнении датасета. По возможности, эти проблемы требуется исправить вручную

Обработка пропусков в колонке Пол. Данные заполнялись по сколнениям фамилии только там, где была уверенность в принадлежности к тому или иному полу. "Пограничные" случаи оставались None

In [9]:
# Loaded variable 'table_data' from kernel state

# Sort by column: 'Sex' (ascending)
table_data = table_data.sort_values(['Sex'], na_position='first')

table_data.loc[47, "Sex"] = "М"
table_data.loc[106, "Sex"] = "М"
table_data.loc[158, "Sex"] = "М"
table_data.loc[568, "Sex"] = "М"
table_data.loc[882, "Sex"] = "М"
table_data.loc[1064, "Sex"] = "М"
table_data.loc[1197, "Sex"] = "М"
table_data.loc[1241, "Sex"] = "М"
table_data.loc[1513, "Sex"] = "М"
table_data.loc[1871, "Sex"] = "М"
table_data.loc[2420, "Sex"] = "М"
table_data.loc[2423, "Sex"] = "М"
table_data.loc[3133, "Sex"] = "Ж"
table_data.loc[3406, "Sex"] = "М"
table_data.loc[4306, "Sex"] = "Ж"
table_data.loc[5320, "Sex"] = "М"
table_data.loc[6157, "Sex"] = "Ж"
table_data.loc[6639, "Sex"] = "Ж"
table_data.loc[6998, "Sex"] = "М"
table_data.loc[7138, "Sex"] = "М"
table_data.loc[7240, "Sex"] = "М"
table_data.loc[7468, "Sex"] = "М"
table_data.loc[7548, "Sex"] = "М"
table_data.loc[9072, "Sex"] = "М"
table_data.loc[9073, "Sex"] = "Ж"
table_data.loc[9325, "Sex"] = "М"
table_data.loc[11323, "Sex"] = "М"
table_data.loc[11330, "Sex"] = "Ж"
table_data.loc[11526, "Sex"] = "М"
table_data.loc[11703, "Sex"] = "М"
table_data.loc[11822, "Sex"] = "Ж"
table_data.loc[11831, "Sex"] = "М"
table_data.loc[11919, "Sex"] = "М"
table_data.loc[11934, "Sex"] = "Ж"
table_data.loc[12078, "Sex"] = "М"
table_data.loc[12182, "Sex"] = "М"
table_data.loc[11216, "Sex"] = "М"
table_data.loc[11272, "Sex"] = "М"
table_data.loc[12471, "Sex"] = "М"
table_data.loc[12552, "Sex"] = "Ж"
table_data.loc[15950, "Sex"] = "М"

In [10]:
table_data["Стентирование в анамнезе"].value_counts()

Стентирование в анамнезе
0      3337
1      1360
Нет      63
Да        4
Name: count, dtype: int64

In [11]:
# table_data['Стентирование в анамнезе'] = table_data['Стентирование в анамнезе'].astype(str).str.strip().str.lower()

mapping = {
    'да': 1,
    'нет': 0,
    '1': 1,
    '0': 0
}

table_data['Стентирование в анамнезе'] = table_data['Стентирование в анамнезе'].replace(mapping)

### TODO: Разбить разные варианты на разные колонки и привести к единому виду

In [12]:
table_data["Форма ФП"].value_counts()

Форма ФП
Пароксизм ФП                             1002
Постоянная форма ФП                       713
Пароксизмальная форма ФП Пароксизм ФП     379
Пароксизмальная форма ФП                  364
Персистирующая форма ФП                    43
                                         ...
Пароксизмальная форма фп Пароксизм фп       1
Постоянная форма                            1
Пароксизм фП                                1
ПароксизмФП                                 1
Пароксизмальная форма ФП Пароксзим ФП       1
Name: count, Length: 63, dtype: int64

In [13]:
mapping = {
    'ПароксизмФП': 'Пароксизм ФП',
    'Пароксизм фп': 'Пароксизм ФП',
    'Пароксизмальная форма фп': 'Пароксизмальная форма ФП',
}

table_data['Форма ФП'] = table_data['Форма ФП'].replace(mapping)

-------------

In [14]:
table_data["Дилатация предсердий"].value_counts()

Дилатация предсердий
Нет                  687
дилатация ЛП, ПП     431
дилатация ЛП         391
нет данных            47
дилатация лп           8
дилатация ЛП,ПП        7
дилатация ПП           5
дилатация ЛП, ПП       1
увеличение ЛП          1
дилатация лп, пп       1
дилятация ЛП           1
Name: count, dtype: int64

In [15]:
mapping = {
    'нет данных': 'Нет',
    'дилатация лп': 'дилатация ЛП',
    'дилятация ЛП': 'дилатация ЛП',
    'дилатация ЛП, ПП ': 'дилатация ЛП,ПП',
    'дилатация ЛП, ПП': 'дилатация ЛП,ПП',
    'дилатация лп, пп': 'дилатация ЛП,ПП',
    'увеличение ЛП': 'дилатация ЛП'
}

table_data['Дилатация предсердий'] = table_data['Дилатация предсердий'].replace(mapping)

In [16]:
table_data["Дилатация предсердий"].value_counts()

Дилатация предсердий
Нет                734
дилатация ЛП,ПП    440
дилатация ЛП       401
дилатация ПП         5
Name: count, dtype: int64

---------------

In [17]:
table_data["ФП b (после чкв)"].value_counts()

ФП b (после чкв)
Нет     12457
Да       2710
ЛОЖЬ        2
Name: count, dtype: int64

In [18]:
mapping = {
    'ЛОЖЬ': 'Нет',
}

table_data['ФП b (после чкв)'] = table_data['ФП b (после чкв)'].replace(mapping)

In [19]:
table_data["ФП b (после чкв)"].value_counts()

ФП b (после чкв)
Нет    12459
Да      2710
Name: count, dtype: int64

-------------

In [20]:
table_data["MKB"].value_counts()

MKB
I20.0    2376
I21.1    1992
I21.0    1891
I21.9    1854
I21.4     828
         ...
M34.0       1
K62.1       1
J15.8       1
M54.1       1
N11.0       1
Name: count, Length: 464, dtype: int64

In [21]:
table_data['MKB'] = table_data['MKB'].astype(str).str.strip().str.upper()

In [22]:
mapping = {
    'I20.00': 'I20.0',
    'I20.80': 'I21.0',
    'I21.10': 'I21.1',
    'I21.40': 'I21.4',
    'I21.90': 'I21.9',
    'I22.00': 'I22.0',
    'I22.10': 'I22.1',
    'I22.80': 'I22.8',
    'I22.90': 'I22.9',
    'I25.50': 'I25.5',
    'I60.60': 'I60.6',
    'I61.00': 'I61.0',
    'I61.40': 'I61.4',
    'I63.30': 'I63.3',
    'I63.40': 'I63.4',
    'I67.20': 'I67.2',
    'I69.80': 'I69.8',
    "None": "NaN",
    "2022-09-21 00:00:00": "NaN",
    
}

table_data['MKB'] = table_data['MKB'].replace(mapping)

------------

In [ ]:
# table_data["ХСН стадия"].value_counts()

KeyError: 'ХСН стадия'

In [ ]:
# mapping = {
#     '2a': 'IIA',
#     '2b': 'IIB',
# }

# table_data['ХСН стадия'] = table_data['ХСН стадия'].replace(mapping)

In [ ]:
# table_data["ХСН стадия"].value_counts()

ХСН стадия
IIA    4310
II     1451
I       696
IIB      51
Name: count, dtype: int64

---------

In [24]:
table_data["ХСН фк"].value_counts()

ХСН фк
2        7992
IIFK     2553
0        1436
1         972
3         910
IIIFK     167
IFK       150
4          51
IVFK        4
Name: count, dtype: int64

----------

In [ ]:
# table_data["АГ"].value_counts()

KeyError: 'АГ'

In [ ]:
# mapping = {
#     'ЛОЖЬ': 0,
#     'ИСТИНА': 1,
# }

# table_data['АГ'] = table_data['АГ'].replace(mapping)

/tmp/ipykernel_1777742/1020979169.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  table_data['АГ'] = table_data['АГ'].replace(mapping)

In [ ]:
# table_data["АГ"].value_counts()

АГ
False    4060
True      637
2           2
Name: count, dtype: int64

-----------

In [27]:
table_data["Вид операции(ИБ)(Новый)"].value_counts()

Вид операции(ИБ)(Новый)
ТЛБАП                                                                                                             10215
ЧКА                                                                                                                2075
чка                                                                                                                1942
-                                                                                                                   974
Реканализация                                                                                                        50
Аорто-коронарное шунтирование                                                                                         9
ТЛБАП со стентированием ПМЖВ                                                                                          7
Протезирование                                                                                                        4
Тромбаспирация                                                                                                        4
Реваскуляризация миокарда                                                                                             4
Пункция перикарда                                                                                                     2
ТЛБАП со стентированием ПКА.                                                                                          2
ТЛБАП со стентированием ПКА                                                                                           2
реваскуляризация миокарда                                                                                             2
ТЛБАП со стентированием ПМЖВ.                                                                                         2
Аорто-коронарное шунтирование.                                                                                        2
Чка                                                                                                                   2
ТЛБАП со стентированием ПМЖВ (ХТО).                                                                                   1
ТЛБАП со стентированием ствола ЛКА с выходом в ОВ                                                                     1
ЭИТ                                                                                                                   1
ТЛБАП со стентированием ПМЖВ, ОВ с выходом в ствол ЛКА                                                                1
ТЛБАП со стентированием ПМЖВ, ОВ                                                                                      1
ТЛБАП со стентированием ОВи ПМЖВ                                                                                      1
ТЛБАП со стентированиемОВ-ВТК                                                                                         1
ТЛБАП и стентирование ПМЖВ                                                                                            1
ТЛБАП со стентированием ОВ                                                                                            1
ТЛБАП со стентированием ОВ, ПМЖВ                                                                                      1
Имплантация ЭКС 460 в режиме DDDR                                                                                     1
ТЛБАП со стентированием ОВ и ПКА.                                                                                     1
Аспирация тромботических масс                                                                                         1
?Имплантация ЭКС 460??                                                                                                1
ТЛБАП со стентированием ПМЖВ с выходом в ствол ЛКА                                                                    1
ТЛБАП со стентированием стволаЛКА и ПМЖВ                                                                              1
ТЛБАП ПМЖВ.                                                                                                           1
Остановка? кровотечения из периферического сосуда? эндоскопическая? с использованием электрокоагуляции.               1
имплантация ЭКС 460 DR?                                                                                               1
Бедренно-подколенное шунтирование справа ниже щели коленного сустава в сочетании с ТЛБАП артерий правой голени        1
?Имплантация ЭКС 460                                                                                                  1
Лапароскопическая аппендектомия                                                                                       1
ТЛБАП со стентированием ПКА, ВТК1                                                                                     1
ТЛБАП со стентированиемПМЖВ                                                                                           1
Гемиляминэктомия                                                                                                      1
Эндартерэктомия                                                                                                       1
Реваскуляризация                                                                                                      1
Имплантация                                                                                                           1
Name: count, dtype: int64

### Все категории, их количество и целесобразность использования - сомнительны

In [28]:
mapping = {
    'чка': 'ЧКА',
    'ТЛБАП со стентированием ПМЖВ.': 'ТЛБАП со стентированием ПМЖВ',
    'реваскуляризация миокарда': 'Реваскуляризация миокарда',
    'Чка': 'ЧКА',
    'ТЛБАП со стентированием ПКА.': 'ТЛБАП со стентированием ПКА',
    'ТЛБАП и стентирование ПМЖВ': 'ТЛБАП со стентированием ПМЖВ',
    'ТЛБАП со стентированиемПМЖВ': 'ТЛБАП со стентированием ПМЖВ',
    'Реваскуляризация': 'Реваскуляризация миокарда',
    '?Имплантация ЭКС 460??': "-",
    'ТЛБАП ПМЖВ.': 'ТЛБАП со стентированием ПМЖВ',
    
}

table_data['Вид операции(ИБ)(Новый)'] = table_data['Вид операции(ИБ)(Новый)'].replace(mapping)

In [29]:
table_data["Вид операции(ИБ)(Новый)"].value_counts()

Вид операции(ИБ)(Новый)
ТЛБАП                                                                                                             10215
ЧКА                                                                                                                4019
-                                                                                                                   975
Реканализация                                                                                                        50
ТЛБАП со стентированием ПМЖВ                                                                                         12
Аорто-коронарное шунтирование                                                                                         9
Реваскуляризация миокарда                                                                                             7
ТЛБАП со стентированием ПКА                                                                                           4
Протезирование                                                                                                        4
Тромбаспирация                                                                                                        4
Пункция перикарда                                                                                                     2
Аорто-коронарное шунтирование.                                                                                        2
ТЛБАП со стентированием ПМЖВ (ХТО).                                                                                   1
ЭИТ                                                                                                                   1
ТЛБАП со стентированием ствола ЛКА с выходом в ОВ                                                                     1
ТЛБАП со стентированием ОВ, ПМЖВ                                                                                      1
ТЛБАП со стентированием ОВ и ПКА.                                                                                     1
Имплантация ЭКС 460 в режиме DDDR                                                                                     1
ТЛБАП со стентированием ПМЖВ, ОВ с выходом в ствол ЛКА                                                                1
ТЛБАП со стентированием ПМЖВ, ОВ                                                                                      1
ТЛБАП со стентированием ОВи ПМЖВ                                                                                      1
ТЛБАП со стентированием ОВ                                                                                            1
ТЛБАП со стентированиемОВ-ВТК                                                                                         1
ТЛБАП со стентированием ПМЖВ с выходом в ствол ЛКА                                                                    1
Аспирация тромботических масс                                                                                         1
ТЛБАП со стентированием стволаЛКА и ПМЖВ                                                                              1
Остановка? кровотечения из периферического сосуда? эндоскопическая? с использованием электрокоагуляции.               1
имплантация ЭКС 460 DR?                                                                                               1
Бедренно-подколенное шунтирование справа ниже щели коленного сустава в сочетании с ТЛБАП артерий правой голени        1
?Имплантация ЭКС 460                                                                                                  1
Лапароскопическая аппендектомия                                                                                       1
ТЛБАП со стентированием ПКА, ВТК1                                                                                     1
Гемиляминэктомия                                                                                                      1
Эндартерэктомия                                                                                                       1
Имплантация                                                                                                           1
Name: count, dtype: int64

------------------

In [30]:
table_data["ДАД(a)"].value_counts()

ДАД(a)
80     2698
70     2467
80     1960
70     1608
90      642
       ...
30        1
701       1
105       1
46        1
94        1
Name: count, Length: 135, dtype: int64

In [31]:
# table_data['ДАД(a)'] = table_data['ДАД(a)'].astype(str).str.strip()
# table_data['ДАД(a)'] = table_data['ДАД(a)'].astype(int)

mapping = {
    r'\80': 80,
    r'\70': 70,
}

table_data['ДАД(a)'] = table_data['ДАД(a)'].replace(mapping)

In [32]:
table_data["ДАД(a)"].value_counts()

ДАД(a)
80     2698
70     2467
80     1962
70     1609
90      642
       ...
30        1
701       1
105       1
46        1
94        1
Name: count, Length: 133, dtype: int64

---------------

### Сомнительный столбец

In [33]:
# Сопутствующие2

table_data["Сопутствующие1"].value_counts()

Сопутствующие1
ХСН                                                                                                           2444
Сахарный диабет                                                                                               1916
ПИКС                                                                                                           559
ЯБЖ, ЯБДПК                                                                                                     323
ХОБЛ                                                                                                           288
ФП постоянная форма                                                                                            224
ОНМК                                                                                                           127
Подагра                                                                                                         19
Ревматоидные поражения                                                                                          16
6 и др                                                                                                          13
2 и3                                                                                                             3
Кардиогенный шок Killip IV                                                                                       2
Цирроз                                                                                                           2
Анемия легкой степени тяжести                                                                                    1
Лимфостаз нижних конечносте1                                                                                     1
Кровотечение из ЖКТ в анамнезе                                                                                   1
ТЭЛА                                                                                                             1
Поликистоз почек, экстрипация матки в анамнезе                                                                   1
Полимиозит                                                                                                       1
Хронический пиелонефрит, склеродермия?                                                                           1
ЗНО молочной железы                                                                                              1
Базалиома кожи носа, полиостеоартроз                                                                             1
Хронический гепатит смешанного генеза                                                                            1
Обтурационная кишечная непроходимость, выведение калостомы, рак ободочной кишки                                  1
Псориаз                                                                                                          1
Туберкулез, снят с учета                                                                                         1
Атеросклероз сосудов нижних конечностей                                                                          1
ДЭП                                                                                                              1
Образование S6 правого легкого                                                                                   1
ХВГС, ДЭП                                                                                                        1
Хр. гепатит 1-2 ст. активности, Хр. холецистит, Хр. панкретит                                                    1
Ожирение 3 ст                                                                                                    1
Умеренный аортальный стеноз, атеросклероз артерий нижних конечностей, атеросклероз брахиоцефальных артерий       1
Рак почки. Оперирован 2012 г.                                                                                    1
3 и 4                                                                                                            1
ТЭЛА мелких ветвей                                                                                               1
Name: count, dtype: int64

-------------

### Сомнительный признак

In [34]:
table_data["Осложнения"].value_counts()

Осложнения
ЖТ/ФЖ                                                                                                  395
Отек легких                                                                                            382
ФП/ТП                                                                                                  318
а-в блокада                                                                                            219
Гематома руки                                                                                          173
Психоз                                                                                                 156
No ReFlow                                                                                              109
Гемаперикард                                                                                            94
Кровотечение из ЖКТ                                                                                     36
ОНМК                                                                                                    24
Тромбоз стента                                                                                          20
Макрогематурия                                                                                          19
Ранняя пневмония                                                                                        17
Другие                                                                                                  12
ТИА                                                                                                     12
Гематома после пункции вены                                                                             11
Сепсис                                                                                                  10
Гематома бедра                                                                                          10
ТЭЛА                                                                                                     7
Носовое кровотечение                                                                                     6
ОИМ                                                                                                      6
Гидроперикард                                                                                            4
Пневмоторакс                                                                                             3
Поздняя пневмония > 5 суток                                                                              2
ЖТ                                                                                                       2
Перфорация 5 тип (пр. п)                                                                                 2
Полная АВ-блокада, гематома шеи, анемия                                                                  1
ФЖ, ОНМК, Отек легких                                                                                    1
Отек легких, АВ-блокада 1, TIMI 0, ВЭКС                                                                  1
ЖТ/ФЖ, Кровотечение из ЖКТ небольшим обьемом                                                             1
ЖТ/ФЖ, Полная АВ-блокада исходно, ВЭКС                                                                   1
ЖТ, ЭИТ                                                                                                  1
ФП                                                                                                       1
ОНМК по гемморагическому типу                                                                            1
Делирий                                                                                                  1
Психоз, НЖТ, АВ-блокада 2                                                                                1
Отек легких, макрогематурия                                                                              1
Синдром Фредерика                                                                                        1
Полная АВ-блокада в конце                                                                                1
ОНМК гемморагический тип                                                                                 1
ОРДС                                                                                                     1
Отек легких, ТЭЛА                                                                                        1
ОПН                                                                                                      1
Полная АВ блокада (с-м Фредерика), желудочно-кишечное кровотечение                                       1
Перфорация ЗМЖВ ПКА, гемоперикард, СН после эмболизации                                                  1
Повторный ОНМК по ишемическому типу, пароксизм ЖТ, илеофеморальный тромбоз слева, ишемия н/к слева.      1
Тромбоэмболия правой подколенной артерии                                                                 1
TIMI 1-2                                                                                                 1
Отек легких, ЖТ/ФЖ                                                                                       1
ЖТ, Полная АВ-блокада, ВАБК                                                                              1
Полная АВ-блокада, ВЭКС                                                                                  1
ФЖ, Отек легких, делирий, гипостатическая пневмония                                                      1
ЖТ интраоперационно ЭИТ                                                                                  1
ФЖ                                                                                                       1
гематоракс                                                                                               1
Name: count, dtype: int64

------------

In [35]:
table_data["CADILLAC (Низкий риск)"].value_counts()

CADILLAC (Низкий риск)
0      2951
Нет    2676
1      2444
Да     1514
Name: count, dtype: int64

In [36]:
mapping = {
    'Нет': 0,
    'Да': 1,
}

table_data['CADILLAC (Низкий риск)'] = table_data['CADILLAC (Низкий риск)'].replace(mapping)
table_data['CADILLAC (Средний риск)'] = table_data['CADILLAC (Средний риск)'].replace(mapping)
table_data['CADILLAC (Высокий риск)'] = table_data['CADILLAC (Высокий риск)'].replace(mapping)
table_data['РЕКОРД (Низкий риск)'] = table_data['РЕКОРД (Низкий риск)'].replace(mapping)
table_data['РЕКОРД (Высокий риск)'] = table_data['РЕКОРД (Высокий риск)'].replace(mapping)

/tmp/ipykernel_1780519/4111910564.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  table_data['CADILLAC (Низкий риск)'] = table_data['CADILLAC (Низкий риск)'].replace(mapping)
/tmp/ipykernel_1780519/4111910564.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  table_data['CADILLAC (Средний риск)'] = table_data['CADILLAC (Средний риск)'].replace(mapping)
/tmp/ipykernel_1780519/4111910564.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  table_data['CADILLAC (Высокий риск)'] = table_data['CADILLAC (Высокий риск)'].replace(mapping)
/tmp/ipykernel_1780519/4111910564.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  table_data['РЕКОРД (Низкий риск)'] = table_data['РЕКОРД (Низкий риск)'].replace(mapping)
/tmp/ipykernel_1780519/4111910564.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  table_data['РЕКОРД (Высокий риск)'] = table_data['РЕКОРД (Высокий риск)'].replace(mapping)

In [37]:
table_data["CADILLAC (Низкий риск)"].value_counts()

CADILLAC (Низкий риск)
0.0    5627
1.0    3958
Name: count, dtype: int64

In [38]:
table_data["РЕКОРД (Высокий риск)"].value_counts()

РЕКОРД (Высокий риск)
1.0    10041
0.0     4621
Name: count, dtype: int64

In [39]:
table_data

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,STEMI,ЧКВ,Дата STEMI,Вид STEMI,...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
47,17-12105,Бабаев СН,59.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,17-17180,Ползиков СВ,58.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,15536,Анфёров ЮА,74.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,21-8249,Арутюнян МА,66.0,NaN,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,17-20825,Кондрашин АА,31.0,М,Нет,Да,Нет,Нет,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6503,19-9921,Шишов ГД,71.0,М,Да,Да,Да,Да,2019-06-12 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6505,19-9912,Рой АГ,63.0,М,Да,Да,Да,Да,2019-06-11 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6506,19-99,Красулин НТ,64.0,М,Да,Да,Да,Да,2019-01-05 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6485,19-1267,Сасов КП,70.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17429,2024-04-19 00:00:00,Петров ВЮ,53.0,М,Да,Да,Да,Да,2018-12-31 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
dead = table_data[table_data["Смерть"] == "Да"]

In [41]:
dead

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,STEMI,ЧКВ,Дата STEMI,Вид STEMI,...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
6157,16-3126,Переходова СМ,74.0,Ж,Нет,Да,Нет,Нет,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11703,17239,Дектерев АЕ,78.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6323,20-74,Полякова АГ,81.0,Ж,Нет,Да,Нет,Нет,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6221,20-11902,Елисеева АА,81.0,Ж,Нет,Да,Нет,Нет,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6220,17-1066,Евсеенко АГ,69.0,Ж,Нет,Да,Нет,Нет,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6449,19122,Королев АН,63.0,М,Да,Да,Да,Да,2015-12-20 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6417,20-10244,Князев ЕВ,72.0,М,Да,Да,Да,Да,03-07-2020 0:00:00,Задний,...,-14.9,12.2,12.2,12.2,12.2,12.2,12.2,NaN,NaN,NaN
6518,19-9576,Соболев ВИ,73.0,М,Да,Да,Да,Да,2019-06-07 00:00:00,Задний,...,-4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6536,19-9084,Колесников АН,71.0,М,Да,Да,Да,Да,2019-05-30 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6507,19-9825,Туговиков АА,48.0,М,Да,Да,Да,Да,13-06-2019 0:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN