In [1]:
import pandas as pd

### Попытки мерджа двух датасетов - временные ряды и табличные данные

**Зачем** - датасет с табличными данными содержит основную информацию о пациенте, исход и временные рамки лечения. Это потребуется для создания модели прогноза временных рядов. 
Так же, в будущем табличный датасет может быть обогащен информацией от временных рядов для лучшей классификации исхода.

In [2]:
table_data = pd.read_excel("./data_raw/DataSet_V49 (2).xlsx")

In [3]:
time_series_data = pd.read_excel("./data_raw/data-timeseries_test.xlsx")

In [4]:
time_series_data["chartTime"] = pd.to_datetime(time_series_data["chartTime"])

In [15]:
table_data["В базе данных"].head(3)

0    Да
1    Да
2    Да
Name: В базе данных, dtype: object

In [5]:
list(table_data.columns)

['Код пациента',
 'Name',
 'Age',
 'Sex',
 'Наличие в БД',
 'Наличие в файле',
 'STEMI',
 'ЧКВ',
 'Дата STEMI',
 'Вид STEMI',
 'SYNTAX Score',
 'Инфаркт-зависимая артерия',
 'Поражение ствола',
 'Количество пораженных сосудов(Syntax)',
 'Количество пораженных сосудов(Значимость)',
 'TIMI',
 'Инфаркт миокарда в анамнезе (<3)',
 'Инфаркт миокарда в анамнезе (>3)',
 'Инфаркт миокарда со стентированием в анамнезе',
 'ОНМК (иш) в анамнезе',
 'ОНМК (гем) в анамнезе',
 'Стентирование в анамнезе',
 'Тромболизис',
 'Форма ФП',
 'Калий',
 'Дилатация предсердий',
 'ФП b (после чкв)',
 'ФП a (в анамнезе)',
 'ФП при окс (до чкв)',
 'ФП постоянная форма',
 'ФЖ',
 'Пробежки ЖТ',
 'Рецидивирующая ЖТ',
 'MKB',
 'Класс ОСН по Killip',
 'ХСН стадия',
 'ХСН фк',
 'ГБ стадия',
 'ГБ риск',
 'АГ',
 'Стенокардия (ИБ)',
 'Стенокардия форма(ИБ)',
 'Стенокардия ФК (ИБ)',
 'СД',
 'ХБП',
 'ЯБ',
 'МКБ',
 'ЖКБ',
 'ФВ ЛЖ (b)',
 'ФВ ЛЖ',
 'EDV',
 'КДР ЛЖ',
 'КСР ЛЖ',
 'МЖП',
 'ЗСЛЖ',
 'ПСПЖ',
 'СДЛА',
 'Размер правого желудочка',
 'Стеноз аортального клапана (степень)',
 'Недостаточность аортального клапана (степень)',
 'Стеноз митрального клапана (степень)',
 'Недостаточность митрального клапана (степень)',
 'Недостаточность трикуспидального клапана (степень)',
 'НПВ',
 'НПВ диаметр',
 'La1',
 'La2',
 'Ra1',
 'Ra2',
 'Bypass#',
 'Гематокрит',
 'Гемоглобин',
 'Эритроциты',
 'Лейкоциты',
 'Тромбоциты',
 'Нейтрофилы (абсолютное значение)',
 'Нейтрофилы (относительное значение)',
 'Лимфоциты (абсолютное значение)',
 'Лимфоциты (относительное значение)',
 'Моноциты (абсолютное значение)',
 'Моноциты (относительное значение)',
 'Эозинофилы (абсолютное значение)',
 'Эозинофилы (относительное значение)',
 'Базофилы (абсолютное значение)',
 'Базофилы (относительное значение)',
 'Сумма всех лейкоцитов',
 'Средний объем эритроцита',
 'Среднее содержание гемоглобина в эритроците',
 'Ср, концентрация гемоглобина в эритроците',
 'Распределение эритроцитов по объему (RDW-CV)',
 'Распределение эритроцитов по объему (RDW-SD)',
 'Средний объем тромбоцита (MPV)',
 'Расчетная ширина распределения тромбоцитов',
 'Тромбокрит',
 'Коэффициент крупных тромбоцитов',
 'СОЭ',
 'С-реактивный белок',
 'PLR (тромбоциты/лимфоциты абс) (61-239)',
 'MLR (моноциты/лимфоциты)',
 'LMR (лимфоциты абс/моноциты абс)',
 'SII (тромбоциты*нейтрофилы абс / лимфоциты абс)',
 'ELR (эозинофилы абс/лимфоциты абс',
 'ELR %',
 'ENR (эозин абс/нейтрофилы абс)',
 'BLR (базофилы абс/лимфоциты абс)',
 'SIRI (NxM)/L',
 'PIV or AISI (NxMxPLT)/L',
 'GLR (глюкоза мг/дл / лимф абс)',
 'FLR (fibr/L abs)',
 'RLR (RDW/ lymph abs)',
 'MPV/PC (MPV/ PLT)',
 'Глюкоза в мг/дл',
 'Фибриноген',
 'Эозинофилы(%)(b)',
 'Палочкоядерные нейтрофилы(%)(b)',
 'Cегментоядерные нейтрофилы(%)(b)',
 'Лимфоциты(%)(b)',
 'Моноциты(%)(b)',
 'Общий белок(b)',
 'Глюкоза(b)',
 'АСАТ(b)',
 'АЛАТ(b)',
 'Билирубин общий(b)',
 'Холестерин общий(b)',
 'Триглицериды(b)',
 'Креатинин(b)',
 'Мочевина(b)',
 'ЛДГ(b)',
 'КФК(b)',
 'КФК-МВ(b)',
 'ПТИ(b)',
 'МНО(b)',
 'ТВ(b)',
 'АПТВ(b)',
 'Дата направления (Общий анализ крови)',
 'Дата взятия биоматериала (Общий анализ крови)',
 'Дата выполнения (Общий анализ крови)',
 'Дата направления (Общий анализ крови-экспрес)',
 'Дата взятия биоматериала (Общий анализ крови-экспрес)',
 'Дата выполнения (Общий анализ крови-экспрес)',
 'Начало операции(ИБ)(Новый)',
 'Конец операции(ИБ)(Новый)',
 'Продолжительность операции',
 'Экстренная операция(ИБ)(Новый)',
 'Вид операции(ИБ)(Новый)',
 'дата поступления',
 'дата выписки',
 'длительность нахождения в стационаре',
 'Смерть',
 'Исход заболевания',
 'дата смерти',
 'повторные операции',
 'Повторная оперция',
 'Тип первой операции БД',
 'Тип повторной операции',
 'Поступление в реанимацию',
 'Выписка из реанимации',
 'Количество дней в реанимации',
 'Смерть в реанимации',
 'Apache II',
 'GRACE(Общее)',
 'GRACE(Общее)>140',
 'интегрилин|эптифибатид|коромакс|агграстат',
 'Причина смерти',
 'Рост',
 'Вес',
 'Индекс массы тела',
 'Экстракардиальная артериопатия',
 'Плохая мобильность',
 'Открытая перация на сердце в анамнезе',
 'Срочность',
 'Систолическое АД(b)',
 'Диастолического АД(b)',
 'ЧСС (b)',
 'САД(a)',
 'ДАД(a)',
 'ЧСС(а)',
 'P',
 'PQ',
 'QRS',
 'QT',
 'RR',
 'Лейкоциты(a)',
 'Нейтрофилы (абсолютное значение)(a)',
 'Лимфоциты (абсолютное значение)(a)',
 'Моноциты (абсолютное значение)(a)',
 'Эозинофилы (абсолютное значение)(a)',
 'Базофилы (абсолютное значение)(a)',
 'Эр(a)',
 'Hb(a)',
 'Гематокрит(a)',
 'Тромбоциты(a)',
 'СОЭ(a)',
 'Эозинофилы(%)(a)',
 'Палочкоядерные нейтрофилы(%)(a)',
 'Cегментоядерные нейтрофилы(%)(a)',
 'Лимфоциты(%)(a)',
 'Моноциты(%)(a)',
 'Миелоциты(%)(a)',
 'Общий белок(a)',
 'Глюкоза(a)',
 'АСАТ(a)',
 'АЛАТ(a)',
 'Билирубин общий(a)',
 'Холестерин общий(a)',
 'Триглицериды(a)',
 'Креатинин(a)',
 'Мочевина(a)',
 'ЛДГ(a)',
 'КФК(a)',
 'КФК-МВ(a)',
 'ПТИ(a)',
 'МНО(a)',
 'ФБГ(a)',
 'ТВ(a)',
 'АПТВ(a)',
 'Сопутствующие1',
 'Сопутствующие2',
 'eGFR (a)',
 'Осложнения',
 'Креатинин',
 'СКФ',
 'Тропонин 1 (b)',
 'Тропонин 1 > 0.1 (b)',
 'Тропонин 1 (a)',
 'Тропонин 1 > 0.1 (a)',
 'Тропонин 1',
 'Тропонин 1 > 0.1',
 'Smoking',
 'SmokeIndex',
 'Ход операции',
 'Протокол коронарографии',
 'Общий анализ крови раньше операции',
 'Общий анализ крови_экспресс раньше операции',
 'Аортальный стеноз (Градиент)',
 'Аортальный стеноз (Заключение)',
 'Отделение',
 'ХОБЛ (Новый столбец)',
 'Коррекция А-В блокады',
 'Исход А-В блокады',
 'Начало А-В блокады (До/после ЧКВ)',
 'А-В блокада',
 'Файл(Анализы)',
 'Файл(ИБ)',
 'Стенокардия в диагнозе при поступлении',
 'ПИКС в диагнозе при поступлении',
 'Запись требует проверки',
 'Инфаркт-зависимая артерия(Огригированная)',
 'Инфаркт-зависимая артерия(Огригированная)2',
 'Ишемический инсульт (Выгрузка из ИБ - временный столбец)',
 'Геморрагический инсульт (Выгрузка из ИБ - временный столбец)',
 'Инсульт (Выгрузка из ИБ - временный столбец)',
 'SpO2',
 'Курит',
 'Индекс курения',
 'GRACE(Общее)>156',
 'Отек легких(b)',
 'Отек легких(a)',
 'Отек легких',
 'Медицинская помощь оказана за первые 4 часа',
 'Гипертоническая болезнь',
 'ФВ < 40',
 'CADILLAC',
 'РЕКОРД',
 'PAMI',
 'TIMI (Летальность)',
 'CADILLAC (Низкий риск)',
 'CADILLAC (Средний риск)',
 'CADILLAC (Высокий риск)',
 'РЕКОРД (Низкий риск)',
 'РЕКОРД (Высокий риск)',
 'GRACE (Низкий риск)',
 'GRACE (Средний риск)',
 'GRACE (Высокий риск)',
 'TIMI (Летальность) (Низкий риск)',
 'TIMI (Летальность) (Средний риск)',
 'TIMI (Летальность) (Высокий риск)',
 'PAMI (Низкий риск)',
 'PAMI (Средний риск)',
 'PAMI (Высокий риск)',
 'Время ЧКВ',
 'А-В блокаДа (Новый)',
 'А-В блокада (степень)',
 'Летальный исход икка',
 'Диагноз',
 'Дата и время развития SOFA 8 и более',
 'Время введения первого антибиотика',
 'Часов до введения первого антибиотика',
 'Часов в ОРИТ ДО развития SOFA 8',
 'Часов в ОРИТ ПОСЛЕ развития SOFA 8',
 'Максимальный прокальцитонин за сутки до развития SOFA 8',
 'Максимальный ЛАКТАТ артерия за сутки до развития SOFA 8',
 'Максимальный ЛАКТАТ вена за сутки до развития SOFA 8',
 'Максимальный ЛАКТАТ артерия за сутки после развития SOFA 8',
 'Максимальный ЛАКТАТ вена за сутки после развития SOFA 8',
 'SOFA первый раз больше или равна 8 баллам',
 'SOFA до развития 8 и более баллов',
 'Используемый антибиотик ДО развития SOFA 8 и более',
 'Левофлоксацин антибиотик ДО развития SOFA 8 и более',
 'Линезолид антибиотик ДО развития SOFA 8 и более',
 'Меропенем антибиотик ДО развития SOFA 8 и более',
 'Метронидазол антибиотик ДО развития SOFA 8 и более',
 'Моксифлоксацин антибиотик ДО развития SOFA 8 и более',
 'Нифуроксазид антибиотик ДО развития SOFA 8 и более',
 'Фосфомицин антибиотик ДО развития SOFA 8 и более',
 'Цефазолин антибиотик ДО развития SOFA 8 и более',
 'Сульбактам антибиотик ДО развития SOFA 8 и более',
 'Цефоперазон антибиотик ДО развития SOFA 8 и более',
 'Цефтриаксон антибиотик ДО развития SOFA 8 и более',
 'Количество часов применения антибиотика ДО развития SOFA 8 и более',
 'Антибиотик после развития SOFA 8 и более',
 'Моксифлоксацин после развития SOFA 8 и более',
 'Левофлоксацин после развития SOFA 8 и более',
 'Азитромицин после развития SOFA 8 и более',
 'Линезолид после развития SOFA 8 и более',
 'Меропенем после развития SOFA 8 и более',
 'Метронидазол после развития SOFA 8 и более',
 'Нифуроксазид после развития SOFA 8 и более',
 'Фосфомицин после развития SOFA 8 и более',
 'Цефазолин после развития SOFA 8 и более',
 'Сульбактам после развития SOFA 8 и более',
 'Цефепим после развития SOFA 8 и более',
 'Цефтриаксон после развития SOFA 8 и более',
 'Через сколько часов после развития SOFA 8 и более был введен антибиотик',
 'APACHE сутки до развития SOFA 8 и более',
 'APACHE сутки ПОСЛЕ развития SOFA 8 и более',
 'АД среднее за сутки до развития SOFA 8',
 'Среднее АД 1 сутки в орит',
 'Минимальное АД 1 сут',
 'Макс АД 1 сут',
 'Среднее АД 3 сутки в орит',
 'Минимальное АД 3 сут',
 'Макс АД 3 сут',
 'Среднее АД 7 сутки в орит',
 'Минимальное АД 7 сут',
 'Макс АД 7 сут',
 'Среднее ЧСС 1 сутки',
 'Мин ЧСС 1 сутки',
 'Максимальное ЧСС 1 сутки',
 'Среднее ЧСС 3 сутки',
 'Мин ЧСС 3 сутки',
 'Максимальное ЧСС 3 сутки',
 'Среднее ЧСС 7 сутки',
 'Мин ЧСС 7 сутки',
 'Максимальное ЧСС 7 сутки',
 'Лейкоциты больше 9 до назначения аб',
 'ИВЛ',
 'Вазопрессорная поддержка',
 'Набор данных (Данные Кокарев)',
 'Unnamed: 344',
 'Адреналин',
 'Добутамин',
 'Допмин',
 'Норадреналин',
 'Левосимендан',
 'Мезатон',
 'Max Aдреналин',
 'Max Добутамин',
 'Max Допмин',
 'Max Норадреналин',
 'Max Мезатона',
 'UA (нестабильная стенокардия)',
 'В базе данных',
 'Синдромный диагноз',
 'killip',
 'Кардиогенный шок',
 'Натрий (Na) (b)',
 'Калий (K) (b)',
 'Хлор (Cl) (b)',
 'Кальций ионизированный (Ca+) (b)',
 'Натрий (Na) (a)',
 'Калий (K) (a)',
 'Хлор (Cl) (a)',
 'Кальций ионизированный (Ca+) (a)',
 'Натрий (Na)',
 'Калий (K)',
 'Хлор (Cl)',
 'Кальций ионизированный (Ca+)',
 'pHARTmin (b)',
 'pHARTmin (a)',
 'pHARTmin',
 'pHARTmax (b)',
 'pHARTmax (a)',
 'pHARTmax',
 'pO2ARTmin (b)',
 'pO2ARTmin (a)',
 'pO2ARTmin',
 'pO2ARTmax (b)',
 'pO2ARTmax (a)',
 'pO2ARTmax',
 'pCO2min (b)',
 'pCO2min (a)',
 'pCO2min',
 'pCO2max (b)',
 'pCO2max (a)',
 'pCO2max',
 'SaO2min (b)',
 'SaO2min (a)',
 'SaO2min',
 'SaO2max (b)',
 'SaO2max (a)',
 'SaO2max',
 'LACTartMin (b)',
 'LACTartMin (a)',
 'LACTartMin',
 'LACTartMax (b)',
 'LACTartMax (a)',
 'LACTartMax',
 'BEArtMin (b)',
 'BEArtMin (a)',
 'BEArtMin',
 'BEArtMax (b)',
 'BEArtMax (a)',
 'BEArtMax',
 'HCO3ArtMin (b)',
 'HCO3ArtMin (a)',
 'HCO3ArtMin',
 'HCO3ArtMax (b)',
 'HCO3ArtMax (a)',
 'HCO3ArtMax',
 'PHVenMin (b)',
 'PHVenMin (a)',
 'PHVenMin',
 'PHVenMax (b)',
 'PHVenMax (a)',
 'PHVenMax',
 'PO2VenMin (b)',
 'PO2VenMin (a)',
 'PO2VenMin',
 'PO2VenMax (b)',
 'PO2VenMax (a)',
 'PO2VenMax',
 'PCO2VenMin (b)',
 'PCO2VenMin (a)',
 'PCO2VenMin',
 'PCO2VenMax (b)',
 'PCO2VenMax (a)',
 'PCO2VenMax',
 'ScvO2Min (b)',
 'ScvO2Min (a)',
 'ScvO2Min',
 'ScvO2Max (b)',
 'ScvO2Max (a)',
 'ScvO2Max',
 'LactVenMin (b)',
 'LactVenMin (a)',
 'LactVenMin',
 'LactVenMax (b)',
 'LactVenMax (a)',
 'LactVenMax',
 'BEVenMin (b)',
 'BEVenMin (a)',
 'BEVenMin',
 'BEVenMax (b)',
 'BEVenMax (a)',
 'BEVenMax',
 'HCO3VenMin (b)',
 'HCO3VenMin (a)',
 'HCO3VenMin',
 'HCO3VenMax (b)',
 'HCO3VenMax (a)',
 'HCO3VenMax',
 'BNP (b)',
 'BNP (a)',
 'BNP']

In [6]:
list(time_series_data.columns)

['Unnamed: 0',
 'ID визита',
 'Пациент',
 'N иб',
 'Время поступления',
 'День пребывания',
 'chartTime',
 'tº, C',
 'АД',
 'нАД',
 'ЧСС',
 'Пульс',
 'ЦВД (CVP)',
 'SpO2',
 'ИПД/PPV',
 'VCO2',
 'СВ (CO)',
 'СИ (CI)',
 'ДЗЛК',
 'ДЛА',
 'НСВ (CCO)',
 'НСИ (CCI)',
 'СВ по Фику',
 'Ударный объем',
 'ИУО',
 'ССС',
 'ИССС',
 'ЛСС',
 'ИЛСС',
 'УРЛЖ',
 'ИУРЛЖ',
 'УРПЖ',
 'ИУРПЖ',
 'РЛЖ (LCW)',
 'ИРЛЖ (LCWI)',
 'Сердечный ритм',
 'РПЖ',
 'ИРПЖ',
 'AaDO2',
 'CaO2',
 'CvO2',
 'Эктопия сердца',
 'ВГОК',
 'ВСВЛ',
 'МОК (УЗИ)',
 'tº крови, C',
 'Пульсация лучевой артерии, лев.',
 'Пульсация лучевой артерии, прав.',
 'Проверка CSM',
 'Наполнение капилляров',
 'Парадоксальный пульс',
 'Лодыжечно-плечевой индекс']

In [7]:
time_series_data.head(5)

,Unnamed: 0,ID визита,Пациент,N иб,Время поступления,День пребывания,chartTime,"tº, C",АД,нАД,...,ВГОК,ВСВЛ,МОК (УЗИ),"tº крови, C","Пульсация лучевой артерии, лев.","Пульсация лучевой артерии, прав.",Проверка CSM,Наполнение капилляров,Парадоксальный пульс,Лодыжечно-плечевой индекс
0,0,17633,Шпакова,60,2025-01-03 15:58:06.3070000,1,2025-01-03 16:04:00,NaN,NaN,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,17633,Шпакова,60,2025-01-03 15:58:06.3070000,1,2025-01-03 16:05:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,17633,Шпакова,60,2025-01-03 15:58:06.3070000,1,2025-01-03 16:10:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17633,Шпакова,60,2025-01-03 15:58:06.3070000,1,2025-01-03 16:15:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,17633,Шпакова,60,2025-01-03 15:58:06.3070000,1,2025-01-03 16:20:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
table_data.head(5)

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,STEMI,ЧКВ,Дата STEMI,Вид STEMI,...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
0,20-6545,Хасьянов РА,78.0,М,Да,Да,Нет,Да,NaN,NaN,...,-5.0,18.5,18.5,18.5,18.5,18.5,18.5,NaN,NaN,NaN
1,19-22109,Тюркова ГГ,80.0,Ж,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17-13439,Ремизов РВ,40.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16-20326,Синенко ОП,78.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9993,Комолов ВИ,75.0,М,Да,Да,Да,Да,2015-07-09 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
time_series_data[time_series_data["ID визита"] ==  "2197"]

Empty DataFrame
Columns: [Unnamed: 0, ID визита, Пациент, N иб, Время поступления, День пребывания, chartTime, tº, C, АД, нАД, ЧСС, Пульс, ЦВД (CVP), SpO2, ИПД/PPV, VCO2, СВ (CO), СИ (CI), ДЗЛК, ДЛА, НСВ (CCO), НСИ (CCI), СВ по Фику, Ударный объем, ИУО, ССС, ИССС, ЛСС, ИЛСС, УРЛЖ, ИУРЛЖ, УРПЖ, ИУРПЖ, РЛЖ (LCW), ИРЛЖ (LCWI), Сердечный ритм, РПЖ, ИРПЖ, AaDO2, CaO2, CvO2, Эктопия сердца, ВГОК, ВСВЛ, МОК (УЗИ), tº крови, C, Пульсация лучевой артерии, лев., Пульсация лучевой артерии, прав., Проверка CSM, Наполнение капилляров, Парадоксальный пульс, Лодыжечно-плечевой индекс]
Index: []

[0 rows x 52 columns]

In [24]:
table_data[["Смерть", "дата выписки"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17430 entries, 0 to 17429
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Смерть        16613 non-null  object
 1   дата выписки  15056 non-null  object
dtypes: object(2)
memory usage: 272.5+ KB

In [31]:
table_data["дата выписки"] = pd.to_datetime(table_data["дата выписки"], errors='coerce')

In [32]:
table_data = table_data.sort_values("дата выписки")
time_series_data = time_series_data.sort_values("chartTime")

In [ ]:
ts_valid = time_series_data.merge(table_data[['patient_id', 'target_time']], on='patient_id', how='inner')
ts_valid = ts_valid[ts_valid['time'] <= ts_valid['target_time']]