In [1]:
import pandas as pd

In [5]:
import os
os.getcwd()
os.listdir()

['.jupyter',
 '.ipython',
 '.yarn',
 'anonymized_parsed_data_analyzes.csv',
 'Untitled Folder',
 'parser.py',
 'scikit_learn_data',
 'Untitled1.ipynb',
 '.bash_history',
 'Пары_четверг',
 '.local',
 'anonymized_parsed_data_histories.csv',
 'Untitled2.ipynb',
 'learn',
 'data_raw',
 'Untitled.ipynb',
 'tmp.ipynb',
 'new_library.py',
 'data_analysis',
 '__pycache__',
 'models',
 'experiments.tar.gz',
 '.npm',
 'catboost_info',
 'nltk_data',
 '.cache',
 '.ipynb_checkpoints',
 'data',
 '.config',
 'anonymized_parsed_data_v8.csv']

In [2]:
data = pd.read_excel("./data_raw/data.xlsx", sheet_name=None)

In [22]:
for sheet_name, df in data.items():
    print(sheet_name)

Больные
Монитор_1
Монитор_2
Монитор_3
ИВЛ
Балансы
Лаб
Препараты
ЗППТ

### Попытки поиска связи между данными во временных рядах и в табличных данных. Цель - связать два источника данных

Пока есть предположение, что номер ИБ - номер истории болезни, который можно найти в текстовом датасете

In [24]:
data["Монитор_3"].to_excel("./data_raw/data-timeseries_test.xlsx")

In [3]:
data["Больные"].head(10)

,№иб,ФИО,Возраст,Диагноз,ХЗ,ХЗ1,ХЗ2,ХЗ3,ХЗ4,ХЗ5,ХЗ6,ХЗ7,ХЗ8,ХЗ9,ХЗ10,ХЗ11
0,25-1,Руденок ВН,71,stemi передний,КО,False,True,45658,45659.0,False,NaN,2.0,Владивосток,NaN,NaN,NaN
1,25-10,Дроздов АИ,65,stemi задний,КО,False,True,45658,45659.0,False,NaN,2.0,Владивосток,NaN,NaN,NaN
2,25-1000,Несветов КН,60,STEMI задний,КО,False,True,45687,45688.0,False,NaN,2.0,прим край,NaN,"ЯБЖ, ЯБДПК",NaN
3,25-1023,Бамбурова НГ,59,STEMI задний,КО,False,True,45688,45690.0,False,ОССН,3.0,прим край,NaN,NaN,NaN
4,25-1025,Иньков ОЮ,53,"нестабильная, АКШ",КХО,False,True,45688,45689.0,False,NaN,2.0,прим край,NaN,NaN,NaN
5,25-1026,Дементьева ЛФ,65,нестабильная,КО,False,True,45688,45689.0,False,NaN,2.0,прим край,ПИКС,Сахарный диабет,6 и др
6,25-1029,Черных ГА,77,STEMI задний,КО,False,True,45688,45692.0,False,NaN,5.0,прим край,NaN,"ЯБЖ, ЯБДПК",ОНМК
7,25-1029,Черных ГА,77,STEMI задний,КО,True,True,45694,45695.0,False,NaN,2.0,прим край,NaN,"ЯБЖ, ЯБДПК",ОНМК
8,25-1030,Мартыненко СВ,74,STEMI передний,КО,False,True,45688,45691.0,False,NaN,4.0,владивосток,NaN,NaN,NaN
9,25-1032,Козлюк ТК,74,STEMI задний,КО,False,True,45688,45690.0,True,ОССН,3.0,владивосток,ИВЛ 18 ч,ХСН,NaN

In [11]:
data["ЗППТ"].head(10)

,ID визита,Пациент,N иб,Время поступления,День пребывания,encounterID,Procedura,Start,Stop,Dlitelnost
0,17635,Магомедов,68,2025-01-04 15:36:41.1500000,2,17635,Гемодиафильтрация,2025-01-05 22:00:00.0000000,2025-01-15 04:00:00.0000000,13320
1,17635,Магомедов,68,2025-01-04 15:36:41.1500000,8,17635,Гемодиафильтрация,2025-01-11 14:30:00.0000000,2025-01-15 04:00:00.0000000,5130
2,17635,Магомедов,68,2025-01-04 15:36:41.1500000,13,17635,Гемодиализ,2025-01-16 18:00:00.0000000,NaN,0
3,17635,Магомедов,68,2025-01-04 15:36:41.1500000,17,17635,Гемодиафильтрация,2025-01-20 19:15:00.0000000,2025-01-25 02:00:00.0000000,6165
4,17635,Магомедов,68,2025-01-04 15:36:41.1500000,18,17635,Гемофильтрация,2025-01-21 11:00:00.0000000,2025-01-23 15:00:00.0000000,3120
5,17635,Магомедов,68,2025-01-04 15:36:41.1500000,21,17635,Гемодиафильтрация,2025-01-24 18:00:00.0000000,2025-01-25 02:00:00.0000000,480
6,17710,Розинков,305,2025-01-16 11:14:41.2400000,1,17710,Гемодиализ,2025-01-16 18:00:00.0000000,2025-01-17 18:00:00.0000000,1440
7,17819,Манякин,904,2025-01-29 12:41:32.8530000,1,17819,Гемодиафильтрация,2025-01-29 23:00:00.0000000,NaN,0
8,17849,Козлюк,1032,2025-01-31 17:09:30.9230000,2,17849,Гемодиафильтрация,2025-02-01 18:22:00.0000000,NaN,0
9,17858,Розинков,305,2025-02-02 12:51:45.9900000,1,17858,Гемодиафильтрация,2025-02-02 13:00:00.0000000,NaN,0

In [12]:
data = pd.read_csv("./data_raw/anonymized_parsed_data_v8.csv")

In [15]:
data["anonymized_text_data"].iloc[0]

'Подождите, пожалуйста... Идет подготовка к выводу всех обследований и воздействий. Это может занять несколько минут. 100%\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nОбщий анализ крови Выполнен 17.02.2015 в 10:58\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Реанимации и интенсивной терапии РСЦ ,\nПалата № 1 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Врач анестезиолог-реаниматолог [ФИО]\nДата направления 17.02.2015 в 04:15 Дата взятия биоматериала: 17.02.2015 Время: 04:15\nИсследуемый компонент Результат Референсные значения и единица измерения Лейкоциты (WBC) 13 3.9-9 10^9/L Нейтрофилы (Neu#) 9.52 1-6 10^9/L Лимфоциты (Lym#) 2.35 1.2-3 % Моноциты (Mon#) 0.92 0.09-0.6 10^9/L Эозинофилы (Eos#) 0.09 0.02-0.3 10^9/L Базофилы (Bas#) 0.09 до 0.06 10^9/L Нейтрофилы (Neu%) 73.4 47-72 % Лимфоциты (Lym%) 18.1 19-37 % Моноциты (Mon%) 7.1 3-11 % Эозинофилы (Eos%) 0.7 0.5-5 % Базофилы (Bas%) 0.7 до 1 % Эритроциты (RBC) 4.78 3.9-5 10^12/L Гемоглобин (HGB) 154 120-160 g/L Гематокрит (HCT) 0.45 36-48 % Средний объем эритроцита (MCV) 93 80-100 fL Среднее содержание гемоглобина в эритроците (MCH) 32.1 27-31 pg Ср. концентрация гемоглобина в эритроците (MCHC) 344 300-380 g/L Тромбоциты (PLT) 160 150-400 10^9/L Средний объем тромбоцита (MPV) 10.1 7.4-10.4 fL СОЭ 20 --\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1" HBs Ag Выполнен 17.02.2015 в 12:34\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Реанимации и интенсивной терапии РСЦ ,\nПалата № 1 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Врач анестезиолог-реаниматолог [ФИО]\nДата направления 17.02.2015 в 04:15 Дата взятия биоматериала: 17.02.2015 Время: 04:15\nИсследуемый компонент Результат Референсные значения и единица измерения НBsAg отрицательно --\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nОбщий анализ крови Выполнен 18.02.2015 в 12:07\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Кардиологическое ,\nПалата № 8 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Зав.\nотделением ОРИТ РСЦ [ФИО]\nДата направления 17.02.2015 в 21:53 Дата взятия биоматериала: 18.02.2015 Время: 21:53\nИсследуемый компонент Результат Референсные значения и единица измерения Лейкоциты (WBC) 9.5 3.9-9 10^9/L Нейтрофилы (Neu#) 5.58 1-6 10^9/L Лимфоциты (Lym#) 2.56 1.2-3 % Моноциты (Mon#) 1.13 0.09-0.6 10^9/L Эозинофилы (Eos#) 0.13 0.02-0.3 10^9/L Базофилы (Bas#) 0.06 до 0.06 10^9/L Нейтрофилы (Neu%) 59 47-72 % Лимфоциты (Lym%) 27.1 19-37 % Моноциты (Mon%) 11.9 3-11 % Эозинофилы (Eos%) 1.4 0.5-5 % Базофилы (Bas%) 0.6 до 1 % Эритроциты (RBC) 4.85 3.9-5 10^12/L Гемоглобин (HGB) 155 120-160 g/L Гематокрит (HCT) 0.46 36-48 % Средний объем эритроцита (MCV) 94 80-100 fL Среднее содержание гемоглобина в эритроците (MCH) 32 27-31 pg Ср. концентрация гемоглобина в эритроците (MCHC) 339 300-380 g/L Тромбоциты (PLT) 143 150-400 10^9/L Средний объем тромбоцита (MPV) 9.9 7.4-10.4 fL СОЭ 19 --\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1" aHCV (сумм) Выполнен 18.02.2015 в 13:26\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Реанимации и интенсивной терапии РСЦ ,\nПалата № 1 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Врач анестезиолог-реаниматолог [ФИО]\nДата направления 17.02.2015 в 04:15 Дата взятия биоматериала: 17.02.2015 Время: 04:15\nИсследуемый компонент Результат Референсные значения и единица измерения aHCV (сумм) ПОЛОЖИТЕЛЬНО --\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1" Агрегация с индукторами Выполнен 19.02.2015 в 12:25\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Кардиологическое ,\nПалата № 8 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Зав.\nотделением врач-кардиолог [ФИО]\nДата направления 18.02.2015 в 15:45 Дата взятия биоматериала: 19.02.2015 Время: 15:45\nИсследуемый компонент Результат Референсные значения и единица измерения Агрегация с индукторами (АДФ) (Платно) 46 55-75 % Агрегация с индукторами (Коллаген) (Платно) 66 50-75 % Агрегация с индукторами (Ристомицин) (Платно) 76 55-100 %\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nОбщий анализ крови Выполнен 19.02.2015 в 13:32\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Кардиологическое ,\nПалата № 8 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Зав.\nотделением врач-кардиолог [ФИО]\nДата направления 18.02.2015 в 15:45 Дата взятия биоматериала: 19.02.2015 Время: 15:45\nИсследуемый компонент Результат Референсные значения и единица измерения Лейкоциты (WBC) 7.6 3.9-9 10^9/L Нейтрофилы (Neu#) 4.16 1-6 10^9/L Лимфоциты (Lym#) 2.43 1.2-3 % Моноциты (Mon#) 0.86 0.09-0.6 10^9/L Эозинофилы (Eos#) 0.08 0.02-0.3 10^9/L Базофилы (Bas#) 0.04 до 0.06 10^9/L Нейтрофилы (Neu%) 55 47-72 % Лимфоциты (Lym%) 32.1 19-37 % Моноциты (Mon%) 11.3 3-11 % Эозинофилы (Eos%) 1.1 0.5-5 % Базофилы (Bas%) 0.5 до 1 % Эритроциты (RBC) 4.66 3.9-5 10^12/L Гемоглобин (HGB) 148 120-160 g/L Гематокрит (HCT) 0.44 36-48 % Средний объем эритроцита (MCV) 94 80-100 fL Среднее содержание гемоглобина в эритроците (MCH) 31.7 27-31 pg Ср. концентрация гемоглобина в эритроците (MCHC) 336 300-380 g/L Тромбоциты (PLT) 150 150-400 10^9/L Средний объем тромбоцита (MPV) 9.7 7.4-10.4 fL СОЭ 36 --\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЛейкоцитарная формула Выполнен 18.02.2015 в 13:09\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Кардиологическое ,\nПалата № 8 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Зав.\nотделением ОРИТ РСЦ [ФИО]\nДата направления 17.02.2015 в 21:53 Дата взятия биоматериала: 18.02.2015 Время: 21:53\nИсследуемый компонент Результат Референсные значения и единица измерения эозинофилы 1 1-5 10^12/л палочкоядерные нейтрофилы 2 1-6 % сегментоядерные нейтрофилы 56 47-72 % лимфоциты 31 19-37 % моноциты 10 3-11 %\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1" Анализ крови на группу Rh Выполнен 17.02.2015 в 12:52\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Реанимации и интенсивной терапии РСЦ ,\nПалата № 1 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Врач анестезиолог-реаниматолог [ФИО]\nДата направления 17.02.2015 в 04:15 Дата взятия биоматериала: 17.02.2015 Время: 12:52\nИсследуемый компонент Результат Референсные значения и единица измерения Группа крови AB(IV) -- Резус-принадлежность Rh+ --\nАнализ выполнил(а): Оператор КДЛ Операторович\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nБиохимический анализ крови (Автомат) Выполнен 17.02.2015 в 10:53\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Реанимации и интенсивной терапии РСЦ ,\nПалата № 1 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Врач анестезиолог-реаниматолог [ФИО]\nДата направления 17.02.2015 в 04:15 Дата взятия биоматериала: 17.02.2015 Время: 04:15\nИсследуемый компонент Результат Референсные значения и единица измерения\nИсследуемый компонент Результат Референсные значения и единица измерения Глюкоза 5.89 3.3-6 ммоль/л Мочевина 5.99 1.7-8.3 ммоль/л АсАТ 179.46 M - до 38 ед/л Общий белок 73.17 65-85 г/л АлАТ 39.96 M - до 41 ед/л КФК 1492.41 M - до 190 ед/л Билирубин общий 25.17 до 25.7 мкмоль/л КФК МВ-фракц 156.75 до 25 ед/л Креатинин 98.49 M - 62-115 мкмоль/л\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nБиохимический анализ крови (Автомат) Выполнен 19.02.2015 в 11:41\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Кардиологическое ,\nПалата № 8 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Зав.\nотделением врач-кардиолог [ФИО]\nДата направления 18.02.2015 в 15:45 Дата взятия биоматериала: 19.02.2015 Время: 15:45\nИсследуемый компонент Результат Референсные значения и единица измерения\nИсследуемый компонент Результат Референсные значения и единица измерения Глюкоза 6.39 3.3-6 ммоль/л Общий белок 72.7 65-85 г/л АсАТ 46.31 M - до 38 ед/л ГГТП 26.33 M - до 66 ед/л АлАТ 24.97 M - до 41 ед/л Мочевая кислота 575.88 M - 200-415 мкмоль/л Билирубин общий 21.98 до 25.7 мкмоль/л КФК 337.67 M - до 190 ед/л Холестерин общий 5.97 до 6.2 ммоль/л КФК МВ-фракц 28.05 до 25 ед/л Триглицериды 2.4 M - 0.45-1.12 ммоль/л Сывороточное железо 9.65 M - 9.5-30 мкмоль/л Креатинин 92.15 M - 62-115 мкмоль/л Холестерин высокой плотности 0.87 0.9-1.54 ммоль/л Мочевина 5.36 1.7-8.3 ммоль/л Холестерин низкой плотности 3.84 M - 1.23-4.45 мкмоль/л\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nОбщий анализ мочи (Урискан) Выполнен 17.02.2015 в 10:50\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Реанимации и интенсивной терапии РСЦ ,\nПалата № 1 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Врач анестезиолог-реаниматолог [ФИО]\nДата направления 17.02.2015 в 04:15 Дата взятия биоматериала: 17.02.2015 Время: 04:15\nИсследуемый компонент Результат Референсные значения и единица измерения эритроциты (BLD) -- -- билирубин (BIL) Не обнаружено -- уробилинон (URO) Не обнаружено -- ацетон (KET) Не обнаружено -- белок (PRO) Не обнаружено -- нитриты (NIT) Не обнаружено -- глюкоза (GLU) Не обнаружено -- реакция (pH) 5 -- удельный вес (SG) 1.01 -- лейкоциты (LEU) Не обнаружено -- аскорбиновая кислота (VIC) neg -- цвет (COL) соломенно-желтый -- прозрачность (CLA) прозрачная -- Эпителий плоский в п.зр. ед -- Лейкоциты в п.зр. ед --\nАнализ выполнил(а):\nУчреждение: Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nОбщий анализ мочи (Урискан) Выполнен 19.02.2015 в 11:03\nФ.И.О. [ФИО] ,\nДата рождения: 01.03.1970 , 51 год , М\nОтделение Кардиологическое ,\nПалата № 8 Медицинская карта № 2197 /\nДиагноз ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip.\nНаправил Зав.\nотделением врач-кардиолог [ФИО]\nДата направления 18.02.2015 в 15:45 Дата взятия биоматериала: 19.02.2015 Время: 15:45\nИсследуемый компонент Результат Референсные значения и единица измерения эритроциты (BLD) -- -- билирубин (BIL) Не обнаружено -- уробилинон (URO) 16.00 -- ацетон (KET) Не обнаружено -- белок (PRO) Не обнаружено -- нитриты (NIT) Не обнаружено -- глюкоза (GLU) Не обнаружено -- реакция (pH) 7.5 -- удельный вес (SG) 1.02 -- лейкоциты (LEU) Не обнаружено -- аскорбиновая кислота (VIC) neg -- цвет (COL) соломенно-желтый -- прозрачность (CLA) прозрачная -- Эпителий плоский в п.зр. 2-3 -- Лейкоциты в п.зр. 2-3 --\nАнализ выполнил(а): Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЭКГ\nФ.И.О.: [ФИО] № Возраст: 51 год\n[ФИО]:\nЗаключение: Синусовый ритм с чсс 88/мин.Q позитивный ИМ в области перегородки,верхушки.Нарушение в/ж проводимости. Дата: 17.02.2015 Время: 02:55 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЭКГ на месте № 1741\nФ.И.О.: [ФИО] Возраст: 51 год\n[ФИО] синусовый Тип(Электрическая ось)нормальное Позиция промежуточная Переходная зона V 3 -V 4 P 0.10" PQ 0.16" QRS 0.08" QT 0.36" RR 1.00" Описание: STv4-v6 приподнят, на нисх. колене з.R точка J\nЗаключение: Ритм синусовый 60 в минуту. С/эпикардиальное повреждение диф. с СРРЖ. контроль Дата: 17.02.2015 Время: 08:19 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЭКГ\nФ.И.О.: [ФИО] № Возраст: 51 год\n[ФИО]:\nЗаключение: 18 час 55 мин. Ритм синусовый с чсс 60 в 1 мин. Динамики зубцов и сегментов нет. Дата: 17.02.2015 Время: 21:31 Подпись: [ФИО]\nУЛЬТРАЗВУКОВОЕ ИССЛЕДОВАНИЕ СЕРДЦА №\nФ.И.О.[ФИО]; Возраст 51 год; Вес 102 Дата: 18.02.2015\nДиагноз: Аорта не изменена;кальциноз ст., регургитация ст. Фибриозное кольцо см.(до 2,6см); на уровне синуса 3.7см.(2,4-3,9см.) Аортальный клапан уплотнен. Амплитуда раскрытия:полная. Ао кровоток: не изменен.ЛЖ/Ао5 мм.рт.ст. Левый желудочек: в пределах нормы. КДР 4.7(до 5,7см.) см. КСР 3.2 см.(до 3,8см.) УО мл; КДО мл; ФВ 41 %(более 55%). Способ измерения М-режим Зоны выявлены в области п.ппг.пв. Диастолическая дисфункция: преобладание кровотока в систолу предсердий. МЖП: 1,0см. утолщена (N 0,7-1,1), ЗСЛЖ: 1,0см. утолщена (N 0,7-1,1) МЖП-движение: нормальное. Митральный клапан: створки не изменены; Пролапс ст. Регургитация ст. Фиброзное кольцо уплотнено; кальциноз см Трикуспидальный: ; пролапс ст. Регургитация ; Передняя стенка ПЖ 0.45 см. Легочный клапан: не изменен; Легочная артерия: не изменена см. Систолическое давление в ПЖ, ЛА 20 мм.рт.ст.(до 35 мм.рт.ст.) Максимальный систолический градиент ПЖ/ЛА 5. Правый желудочек: 2.0 см.(от 2,6см.) В 4-х камерной проекции см.(4,3х7,8см.) Правое предсердие: 3,6-4,6 см.(4,5х5,2см) Левое предсердие: 3,5-4,7 см.(4,5х5,2см) МПП: лоцируется на всем протяжении мм (до 10мм) Нижняя полая вена: см., коллабирует более 50% Дополнительные трабекулы в базальном, среднем отделе, в области верхушки ЛЖ, ПЖ Перикардиальный выпот: нет.\nЗаключение: Аорта,ФК АоК, МК уплотнены. Полости сердца не расширены. Гипокинез, передних, передне-перегородочных сегмнтов. Дискинезия передне-верхушечных сегментов. Передне-верхушечная аневризма сердца(4,0-3,6 см)ДД ЛЖ 1 тип. Сократимость ЛЖ снижена. ЛГ -0 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЭКГ на месте № 1809\nФ.И.О.: [ФИО] Возраст: 51 год\n[ФИО] Тип(Электрическая ось)нормальное Позиция промежуточная Переходная зона V 1 P " PQ " QRS " QT " RR " Описание:\nЗаключение: Ритм синусовый 60 в минуту. Динамика переднего распрастраненного Q негативного инфаркта. Дата: 18.02.2015 Время: 09:17 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЭКГ № 1864\nФ.И.О.: [ФИО] Возраст: 51 год\n[ФИО] карта № 2197 Ритм Тип(Электрическая ось)нормальное Позиция промежуточна Переходная зона V 1 P " PQ " QRS " QT " RR " Описание:\nЗаключение: Дата: 19.02.2015 Время: 09:39 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЭКГ на месте № 1809\nФ.И.О.: [ФИО] Возраст: 51 год\n[ФИО] Тип(Электрическая ось)нормальное Позиция промежуточная Переходная зона V 1 P " PQ " QRS " QT " RR " Описание:\nЗаключение: Ритм синусовый 60 в минуту. Tv2-5 углубился. Динамика переднего распрастраненного Q негативного инфаркта. Дата: 19.02.2015 Время: 10:22 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЭКГ № 1987\nФ.И.О.: [ФИО] Возраст: 51 год\n[ФИО] карта № 2197 Ритм Тип(Электрическая ось)нормальное Позиция промежуточна Переходная зона V 1 P " PQ " QRS " QT " RR " Описание:\nЗаключение: Ритм синусовый 67 в минуту. Tv5v6(+), Tv2-v4 ум. по глубине.Динамика Q негативного переднего распрастраненного инфаркта. Дата: 24.02.2015 Время: 09:51 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nЭКГ № 2124\nФ.И.О.: [ФИО] Возраст: 51 год\n[ФИО] карта № 2197 Ритм Тип(Электрическая ось)нормальное Позиция промежуточна Переходная зона V 1 P " PQ " QRS " QT " RR " Описание:\nЗаключение: Ритм синусовый 67 в минуту. Существенной динамики зубцов. Дата: 26.02.2015 Время: 10:52 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1" Коронарография Доза 12 мЗв\nФ.И.О.: [ФИО] Возраст: 51 год\n[ФИО] 8 Результат: Ствол ЛКА - без сужений; ПМЖВ - протяжённый стеноз с/3 99% с признаками пристеночного тромбоза; ОВ - крупная(левый тип коронарного кровотока) - без сужений; ВТК - крупная, стеноз д/3 80%; ПКА - мелкая, окклюзия в с/3, без заполнения д/3\nЗаключение: ТЛБАП со стентированием ПМЖВ Дата: 17.02.2015 Время: 03:05 Подпись: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nПротокол заседания врачебной комиссии ВК №2197 от 17.02.2015 Присутствовали: Председатель - зам. главного врача по лечебной работе: [ФИО], Члены: зам. главного врача по ЭВН [ФИО] заведующий Кардиологическое Реанимации и интенсивной терапии РСЦ\nотделением [ФИО] Заседание проводится по представлению лечащего врача Данные о направлении на обследование или воздействие\nДата направления: 17.02.2015 09:26\nНаправил: Врач-кардиолог [ФИО] Комментарий к направлению: 2 покрытых коронарных стента и доставляющая система для рассмотрения вопроса по обеспечению дорогостоящим расходным материалом пациента (ки) [ФИО] Возраст 51 год (\nистория болезни №2197).\nПалата 8 Полис пациента: Страховая организация: Восточно страховой Альянс Вид документа: не указан [ПОЛИС] [АДРЕС]Страховая организация: Восточно страховой Альянс Вид документа: не указан [ПОЛИС] Адрес пациента: край. Приморскийг.Арсеньев, ул. Черняховского д.117 кв.\nДиагноз: ИБС: Q-негативный передне-распространенный инфаркт миокарда от 17.02.2015 г. ТЛБАП со стентирование ПМЖВ от 17.02.15 г. Гипертоническая болезнь 3 ст., риск 4. ОСН I Killip. Код МЭС 0010251 Обоснование назначения дорогостоящего обследования: коронарография С данными истории болезни,\nанамнезом ознакомлены. Пациент(ка) является жителем Приморского края. Решение врачебной комиссии: КАГ экстренно по КМУ РСЦ. Председатель врачебной комиссии: [ФИО] [ФИО] и интенсивной терапии РСЦ\nотделениемФомин И.М. Подпись лечащего врача _