In [1]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
import re
import nltk
from nltk.corpus import stopwords
import pymorphy3
import pandas as pd

In [3]:
# Для русских текстов
morph = pymorphy3.MorphAnalyzer(lang='ru')
stop_words = set(stopwords.words('russian'))

def preprocess_text(text):
    # Удаление цензурных символов (****, ### и т.д.)
    text = re.sub(r'[*#]+', '', text)
    
    # Удаление спецсимволов, но сохранение основных знаков препинания
    text = re.sub(r'[^a-zA-Zа-яА-ЯёЁ0-9\s.,!?-]', ' ', text)
    
    # Приведение к нижнему регистру
    text = text.lower()
    
    # Токенизация
    tokens = text.split()
    
    # Удаление стоп-слов и лемматизация
    cleaned_tokens = []
    for token in tokens:
        if token not in stop_words and len(token) > 2:
            lemma = morph.parse(token)[0].normal_form
            cleaned_tokens.append(lemma)
    
    return ' '.join(cleaned_tokens)

In [4]:
table_data = pd.read_excel("../../data_raw/DataSet_V49 (2).xlsx")

In [5]:
text_data = pd.read_csv("../../anonymized_parsed_data_histories.csv")

In [6]:
len(text_data)

21670

In [7]:
table_data.dropna(subset=['Смерть'], inplace=True)

In [8]:
len(table_data)

16613

In [9]:
df2_subset = table_data[['Файл(ИБ)', 'Смерть']]
df2_subset.rename(columns={'Файл(ИБ)': 'file_name', 'Смерть': 'label'}, inplace=True)

df2_subset["file_name"] = df2_subset["file_name"].astype(str)
# text_data['file_name'] = text_data['file_name'].apply(lambda x: str(int(x)) if pd.notna(x) else None)

# Делаем merge по идентификатору
df1 = text_data.merge(df2_subset, on='file_name', how='inner')

/tmp/ipykernel_2681605/2526386153.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_subset.rename(columns={'Файл(ИБ)': 'file_name', 'Смерть': 'label'}, inplace=True)
/tmp/ipykernel_2681605/2526386153.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_subset["file_name"] = df2_subset["file_name"].astype(str)

In [10]:
df1

,file_name,patient_id,anonymized_text_data,label
0,ДружковаГВ25177_history_0.html,25177.0,[ФИО] «Приморская краевая клиническая больница...,Нет
1,ДорошенкоВИ_history_0.html,7461.0,[ФИО] «Приморская краевая клиническая больница...,Нет
2,ТкаченкоВВ278_history_0.html,278.0,[ФИО] «Приморская краевая клиническая больница...,Нет
3,ЗубоваИН9275_history_0.html,9275.0,[ФИО] «Приморская краевая клиническая больница...,Нет
4,НесинаНД_history_0.html,4039.0,[ФИО] «Приморская краевая клиническая больница...,Нет
...,...,...,...,...
10453,ДовшковаЛФ_history_0.html,8567.0,[ФИО] «Приморская краевая клиническая больница...,Нет
10454,АхапкинАВ_history_0.html,13287.0,[ФИО] «Приморская краевая клиническая больница...,Нет
10455,КонстантиновКВ4084_history_0.html,4084.0,[ФИО] «Приморская краевая клиническая больница...,Нет
10456,ЛысенкоТВ9514_history_0.html,9514.0,[ФИО] «Приморская краевая клиническая больница...,Нет
10457,СклярЭВ_history_0.html,14632.0,[ФИО] «Приморская краевая клиническая больница...,Нет

In [11]:
df1['anonymized_text_data'][0]

'[ФИО] «Приморская краевая клиническая больница №1» (690990, Владивосток, ул. Алеутская 57) Согласие пациента на обработку персональных данных. Я, (\nФ.И.О. полностью) [ФИО] Место рождения [ФИО] край, г.Уссурийск, ул. Октябрьская д.5 кв.56 Паспорт [ПАСПОРТНЫЕ ДАННЫЕ] , выдан 25.07.2006 Орган, выдавший паспорт Даю своё согласие на обработку своих персональных данных [ФИО] Здравоохранения «Приморской краевой клинической больнице №1 » в целях сохранения моего здоровья на срок в соответствии с действующим законодательством. Персональные данные, необходимые для использования в ГУЗ ПККБ №1 – фамилия, имя, отчество, год, месяц,\nдата рождения, адрес, семейное, социальное положение, образование, профессия, медицинский\nдиагноз, сведения о перенесенных заболеваниях, а так же другие сведения необходимые для постановки\nдиагноза и проведения лечения. Обработка персональных данных включает в себя сбор, систематизацию, накопление, хранение, уточнение (обновление, изменение), использование, передачу в другие лечебно-диагностические государственные учреждения, а также в страховые медицинские организации, обезличивание и уничтожение. Дата:30.12.2021 Подпись: ГБУЗ ПККБ №1 Процедурная карта б ГБУЗ ПККБ №1 Процедурная карта больного ФИО больного [ФИО] , 60 лет\nОтделение Кардиологическое , № истории 25177 Поступила 30.12.2021 , выписана Анестезия, консультации: [ФИО] код специалиста\nФ.И.О. Код манипуляции Кол-во Дата Личный код специалиста\nФ.И.О. ГБО процедуры № ИРТ [ФИО] врача № Рентген хирургич. обследование Эндоскопия, ФБС, ФГАС УЗИ,\nЭКГ, ЭХО бр. полости НКИ ПЦР(Ag) HbAg HCV ВИЧ ЭДС (RW) Фл-я АДСМ/корь / Кал на я/глист Страховая организация: .Восточно-страховой Альянс Вид документа: Полис ОМС единого образца [ПОЛИС] Дата выдачи 02.03.2012 Ф 20 (-) ОТР ЗКЗ ОТР Рост 168 Вес 85 Т°С 36.6 Код формы по ОКУД Код учрежд. по ОКПО Министерство здравоохранения РФ Медицинская документация Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1" наименование учреждения Форма №30 ОУ Учреждена Минздравом СССР 04.10.80.№1030 Медицинская карта № 25177/1 стационарного больного Дата и время поступления: 30.12.2021, 13:16 Поступил в\nотделение: Кардиологическое,\nПалата: 11 Переведен в\nотделение:\nОтделение Код КСГ(по МКБ) Код КСГ(по операции) Дата приема Время № ИБ в отд.\nПалата Реанимации и интенсивной терапии РСЦ 30.12.2021 13:40 3839 2 Кардиологическое 01.01.2022 10:05 1 11 Дата и время выписки: 10.01.2022, 11:21 Контингент По полису ОМС ПК Проведено койко-дней 11 койко-дней Вид транспортировки при поступлении: На каталке Группа крови и резус-принадлежность: ____, Rh+ Привит от гриппа: нет ; пневмонии:нет Побочное действие лекарств (непереносимость) на спирт - крапивница 30.12.2021 [ФИО] Пол Ж Возраст 60 лет\nДата рождения 27.06.1961 Паспорт серия: 0503 № 941786 СНИЛС [СНИЛС] Постоянное место жительства: Приморский край, г. Уссурийск, [АДРЕС]. Тел.: Адрес родственников: Социальное положение: Работающий Страховой статус: Застрахован Место работы: Профессия(должность): Группа инвалидности: _, удостоверение № Кем направлен больной: СМП , направление № врач: , Прикрепление по полису : Доставлен в стационар Экстренно ,\nДиагноз направившего учреждения:\nДиагноз при поступлении: ИБС. Нестабильная стенокардия высокого риска. ОСН I ФК по Killip.\nДиагноз клинический: ИБС, инфаркт миокарда передне-распространенный без подъема сегмента ST от 27.12.21 г. ТЛБАП со стентированием ПМЖВ от 30.12.21г. 10.01.2022 .. ИБС,нестабильная стенокардия высокого риска. ТЛБАП со стентированием ПМЖВ от 30.12.21г.ОСН I ФК по Killip. .. п/о: ИБС. Нестабильная стенокардия высокого риска. ОСН I ФК по Killip. 30.12.2021 .. Фоновый\nдиагноз: Гипертоническая болезнь III стадии, неконтролируемая, Артериальная гипертензия 3 степени, риск IV степени. ХСН с сохраненной ФВ, 2 функ. класса.\nДиагноз заключительный клинический: а) основной: ИБС, инфаркт миокарда передне-распространенный без подъема сегмента ST от 27.12.21 г. ТЛБАП со стентированием ПМЖВ от 30.12.21г. б) осложнение основного: ОСН I ФК по Killip. в) фоновый\nдиагноз: Гипертоническая болезнь III стадии, неконтролируемая, Артериальная гипертензия 3 степени, риск IV степени. ХСН с сохраненной ФВ, 2 функ. класса. г) сопутствующий: Хронический эрозивный гастрит, ремиссия. Хронический холецистит. Хронический паренхиматозный панкреатит, ремиссия. Узел щитовидной железы . Код МЭС: Код МКБ: I21.40 Сданы: да/нет Личные вещи нет ценные вещи нет документы С режимом ознакомлен(а) Роспись _________________ Историю болезни заполнил: [ФИО] [ФИО] бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\n[ФИО] карта № 25177/1 стационарного больного [ФИО] Информативное согласие больного Количество госпитализаций в данном году по поводу данного заболевания: Хирургические операции, методы обезболивания и послеоперационные осложнения [ФИО] [ФИО] операции Код КСГ ТЛБАП со стентированием ПМЖВ 8.1.1.3.1 30.12.2021 [ФИО] A16.12.028 st25.012 Выполненная ВМП ОМС Отметка о выдаче листка нетрудоспособности: Больничный лист c 30.12.2021 по 10.01.2022 № Больничный лист c 11.01.2022 по 12.01.2022 № Явка к врачу по месту жительства: 12.01.2022 После выписки: Исход заболевания: выписан с улучшением Характер течения основного заболевания : Долечивание Трудоспособность снижена Особые отметки: Видимые онкозаболевания: нет С профилактикой кишечных инфекций ознакомлен.\nОсмотрен на педикулез и чесотку. М/с Дата 30.12.2021, 09.01.2022 Лечащий врач: [ФИО] Зав.\nотделением [ФИО] Чек лист оценки эпидемиологического статуса пациента при\nплановой госпитализации в условиях пандемии COVID-19 ФИО пациента [ФИО]\n[ФИО] термометрии и пульсоксиметрии Температура тела 36,6 [ФИО], которые необходимо отразить при сборе\nанамнеза у пациента [ФИО]\nанамнез Посещение др.стран и регионов нашей страны с неблагоприятной эпид.обстановкой за последние 14 дней 🗹 наличие тесных контактов за последние 14 дней с лицами, находящимися под наблюдением по инфекции, вызванной новым коронавирусом SARS-CoV-2, которые в последующем заболели 🗹 наличие тесных контактов за последние 14 дней с лицами, у которых лабораторно подтвержден\nдиагноз COVID-19 🗹 Есть ли у лиц, с которыми Вы проживаете или тесно общаетесь, симптомы ОРИ? 🗹 Привиты ли Вы от гриппа? 🗹 Привиты ли Вы от пневмококковой инфекции? 🗹 Привиты ли Вы от коронавирусной инфекции COVID-19? 🗹 Если привиты, то укажите даты первого и второго этапа. 1 этап 15,09,2021 2 этап 07,10,2021 Сведения о наличии обследования при поступлении или перенесенном заболевании наличие ПЦР или экспресс-теста на антиген вируса НКИ отриц. полож. результат экспресс-теста на антитела для переболевших новой коронавирусной инфекции SARS-CoV-2 (при наличии) IgG IgM Подпись медицинского сотрудника________________________ Время 13.19 Дата 30.12.2021 Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\n[ФИО] врачебный\nосмотр [ФИО] Возраст 60 лет ИБ 25177 Дата и время\nосмотра 30.12.2021, 13.16 При поступлении: рост 168 см, вес 85 кг, температура 36.6 С, АД 140/80 мм. рт. ст.\nЖалобы: На ноющие боли за грудиной. Начало заболевания : 25.12.2021\nАнамнез заболевания: ГБ длительное время с максимальными цифрами АД до 220 и 120 мм рт.ст. Постоянно принимает лористу, эпизодически индапамид. ИБС, клиника стенокардии 2 ФК с 2008г., ранее ИМ отрицает. Принимала ацекардол, самостоятельно отменила препарат. Ухудшение состояния с 25.12.21г., в покое стали беспокоить пекущие боли за грудиной, иррадиирующие в левую руку, повышение АД до 170 и 90 мм рт.ст. СМП вызвала 27.12.21г., по\nЭКГ - субэндокардиальная ишемия по передне-боковой стенке. Госпитализирована в Уссурийскую ГБ. Проводилось лечение антикоагулянтами, антиагрегантами, статинами, гипотензивными и антиангинальными препаратами. Переведена в РСЦ. Клопидогрелем, статинами насыщена. Транспортировку перенесла удовлетворительно. В п/о РСЦ согласие на лечение получено. Переводится в ОРИТ РСЦ для подготовки к ЧКВ. Результат ПЦР на Covid-19: Отрицательный с м/ж.\nАнамнез жизни: Вирусные гепатиты, ТВС, вен. заболевания отрицает. Другие заболевания: Хронический эрозивный гастрит, ремиссия. Хронический холецистит. Хронический паренхиматозный панкреатит, ремиссия. Последняя ФГДС в 2019г. Узел щитовидной железы, не лечится. Аллергологические реакции на лекарственные препараты и пищевые продукты: на спирт - крапивница. Травмы: нет. Операции: нет Наследственность: нет. Вредные привычки: курит до 3 пачек в день, спиртное умеренно. Выезд за пределы РФ/ПК за последние 6 месяцев:нет Эпидемиологический\nанамнез : в течение последних 14 дней границы РФ не пересекал (ла), другие регионы РФ не посещал(а), контакт с лицами, с подтверждённым\nдиагнозом COVID 19 или находящимися на карантине – отрицает Сведения о перенесенном заболевании COVID 19:нет, привита сентябрь - октябрь 2021г. Анализ на COVID 19 (ПЦР) отрицательный с места жительства. Страховой\nанамнез: На ЛВН в течение года находился с 27.12.21 Текущий ЛВН продолжение с 30.12.21 Профессия(должность): . Данные объективного\nосмотра: Общее состояние больного: средней тяжести. Сознание - ясное. Телосложение правильное. Питание нормальное. Окраска кожных покровов и видимых слизистых: обычная. Влажность кожных покровов и слизистых: нормальные. Периферические лимфоузлы не пальпируются. Молочные железы без особенностей Щитовидная железа без особенностей Костно-мышечный аппарат без особенностей. Отеки нет. Органы дыхания Форма грудной клетки правильная. В акте дыхания участвуют обе половины. Перкуторно-легочный звук: норма. При аускультации дыхание везикулярное. Хрипы не выслушиваются. ЧДД: 16 в 1 мин. Органы кровообращения Границы сердца: Правая на 1 см кнаружи от правого края грудины; верхняя по III - ребру; левая по левой средне-ключичной линии Тоны сердца ритмичные. ЧСС: 70 в 1 мин., пульс: 70 уд./мин., удовлетворительного наполнения и напряжения. АД (сист/диаст): 140/80 мм. рт. ст. Шум отсутствует. Органы пищеварения Язык влажный. Живот правильной формы, за счет подкожно-жировой клетчатки не увеличен. При пальпации мягкий. Печень не увеличена. Размеры по Курлову 9*8*7 см. Консистенция обычная, при пальпации безболезненна. Селезенка не пальпируется. Мочевыделительная система Симптом поколачивания в поясничной области отрицателен с обеих сторон. Расстройства мочеиспускания не отмечает.\nДиагноз: ИБС. Нестабильная стенокардия высокого риска. ОСН I ФК по Killip. Фоновый\nдиагноз: Гипертоническая болезнь III стадии, Артериальная гипертензия 3 степени, неконтролируемая, риск IV степени. Осложнение основного DS: Сопутствующий DS: Хронический эрозивный гастрит, ремиссия. Хронический холецистит. Хронический паренхиматозный панкреатит, ремиссия. Узел щитовидной железы.\nПлан ведения и лечения: Р 1, Д 10 Клопидогрел 75 мг 1 р/д АСК 100 мг 1 р/д Клексан 0,8 мл 2 р/д п/к Аторвастатин 40 мг вечером Лизиноприл 5 мг вечером Бисопролол 5 мг утром Нитраты в/в капельно Омепразол 20 мг 1 р/д Гемотрансфузии:не нуждается в гемотрансфузии Врач: [ФИО] Зав.\nотделением: [ФИО] ФИО пациента: [ФИО], номер истории: 25177 Показания к реваскуляризации миокарда Достаточно 1-го критерия!!! ✔ GRACE <140 (104-139) Возраст старше 75 лет Стенокардия покоя с преходящими изменениями на\nЭКГ, изменения сегмента ST>0.05 мВ, преходящие подъемы ST Инверсия зубца Т более 0,2 мВ Необходимо наличие не менее 2х критериев ✔ Стенокардия покоя (менее 20 минут), купированная спонтанно или нитроглицерином.\nАнамнез патологии периферических или церебральных артерий Перенесенный инфаркт миокарда, в том числе безболевой реваскуляризация в\nанамнезе (ЧКВ или АКШ) Сахарный диабет Хроническая почечная недостаточность (СКФ ниже 50 мл/мин) Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\nОтделение Реанимации и интенсивной терапии РСЦ Первичный\nосмотр анестезиолога-реаниматолога [ФИО] Возраст 60 лет ИБ 25177 Дата и время\nосмотра 30.12.2021, 13.17 При поступлении: рост 168 см, вес 85 кг, температура 36.6 С, АД 140/80 мм. рт. ст. Состояние больного: средней тяжести\nЖалобы: На давящую боль в груди\nАнамнез заболевания: Дополнений к\nанамнезу нет Аллергологический\nанамнез: на спирт - крапивница 30.12.2021 Данные объективного\nосмотра: Больная\nосмотрена анестезиологом-реаниматологом. Состояние больной средней степени тяжести за счет нестабильной стенокардии. В сознании. Кожный покров бледно-розовый, нормальной влажности, нормотермия 36.6 С. Дыхание самостоятельное, везикулярное, проводится равномерно во все отделы легких, хрипов нет. Гемодинамика стабильна, гипертензия, синусовый ритм ЧСС 64 в мин. Живот мягкий и безболезненный при пальпации. Шкала нутритивного скрининга Алгоритм организации клинического питания в ПККБ№1. Шаг 1. Диагностика недостаточности питания. - Первичная оценка в приемном покое или при первичном\nосмотре. Использование шкалы NRS 2002. Шкала риска нутритивной недостаточности (NRS 2002) [ФИО] Индекс массы тела менее 20 кг/м2 и(или) окружность середины плеча менее 25 см x Похудел ли пациент за последние 3 месяца? x Объем съедаемой пищи за последнюю неделю уменьшился и стал недостаточным? x Тяжелое заболевание, требующие госпитализацию в ОРИТ и(или) объемной инфузионно-трансфузионной терапии и т.д. x Таблица 1. Начальный скрининг. Если на один из вопросов был получен удовлетворительный ответ, то переходить к таблице номер 2. Если на все вопросы ответ отрицательный, то повторная оценка проводится через неделю. Таблица 2. Окончательная скрининговая оценка. Сниженный нутритивный статус Тяжесть заболевания 1 балл Нормальный нутритивный статус 1 балл Перелом бедра. Больные с декомпенсацией хр. заболеваний: цирроз печени, ХОБЛ, хронический гемодиализ, диабет, онкология Синдромный\nдиагноз:ОКС\nДиагноз: ИБС. Нестабильная стенокардия высокого риска. ОСН I ФК по Killip. Фоновый\nдиагноз: Гипертоническая болезнь III стадии, Артериальная гипертензия 3 степени, неконтролируемая, риск IV степени. Осложнение основного DS: Сопутствующий DS: Хронический эрозивный гастрит, ремиссия. Хронический холецистит. Хронический паренхиматозный панкреатит, ремиссия. Узел щитовидной железы.\nПлан ведения и лечения:\nПланируется терапия согласно реанимационной карты, клопидогрель 75 мг 1 р/с, ацекардол 100 мг 1 р/с, аторвастатин 40 мг 1 р/с, лизиноприл 5 мг 1 р/с, эноксипарин 0.8 мг 2 р/с, омепразол 20 мг 1 р/с, мониторинг, лабораторный контроль, мероприятия общего ухода, ЧКВ. Врач: [ФИО] Зав.\nотделением: [ФИО] Учреждение Государственное бюджетное учреждение здравоохранения "Приморская краевая клиническая больница № 1"\n[ФИО]\nдиагноза [ФИО] Возраст 60 лет ИБ 25177 Дата и время\nосмотра 30.12.2021, 13.16\nОбоснование\nдиагноза: У больной,60 лет,несомненно,имеется ИБС,проявлдяющаяся приступами стенокардии,которые участились в течение последней недели .Проведена КАГ-ЛКА: ствол - не изменен; ПМЖВ — стеноз с/3 99%, далее без значимых стенозов; ОВ - без значимых стенозов; ПКА — стеноз д/3 55%, далее без значимых стенозов. Выполнена ТЛБАП со стентированием ПМЖВ .ИБС возниклдва на фоне имеющейся Гипертонической болезни\nДиагноз: ИБС,нестабильная стенокардия высокого риска. ТЛБАП со стентированием ПМЖВ от 30.12.21г.ОСН I ФК по Killip. Осложнение основного DS: Фоновый\nдиагноз: Гипертоническая болезнь III стадии,неконтролируемая, Артериальная гипертензия 3 степени, риск IV степени.ХСН с сохраненной ФВ,2фкл Сопутствующий DS: Хронический эрозивный гастрит, ремиссия. Хронический холецистит. Хронический паренхиматозный панкреатит, ремиссия. Узел щитовидной железы. Врач: [ФИО] Л И С Т Н А З Н А Ч Е Н И Й\nФ.И.О. [ФИО] Дата поступления: 30.12.2021 ИБ № 25177\nДиагноз: ИБС, инфаркт миокарда передне-распространенный без подъема сегмента ST от 27.12.21 г. ТЛБАП со стентированием ПМЖВ от 30.12.21г. Побочное действие (непереносимость) лекарств: 30.12.2021 : на спирт - крапивница Диета: Диета № 10 01.01.2022 Диета № 10 01.01.2022 Режим: Активный 01.01.2022 Активный 01.01.2022 Название препарата/смеси Комментарии Подпись медсестры Дата назначения Дата отмены Подпись врача Sol. Phentanyli 50 mcg/ml 2 ml 1 р/д в/в на 1 дн. Введено в 21:15 (м/с: А.В. Царева), с целью премедикации и обезболивания 30.12.2021 31.12.2021 Р.В. Рощенко Аторвастатин 40 мг (1 таб. 40 мг) 1 р/д внутрь на 12 дн. ужин 01.01.2022 10.01.2022 Д.В. Семенникова Ацекардол 100 мг (1 таб. 100 мг) 1 р/д внутрь на 12 дн. утро 01.01.2022 10.01.2022 Д.В. Семенникова Бисопролол 5 мг (1 таб. 5 мг) 1 р/д внутрь на 12 дн. 2,5 мг 12т утро 01.01.2022 10.01.2022 Д.В. Семенникова Лизиноприл-АЛСИ 5 мг (1 таб. 5 мг) 1 р/д внутрь на 12 дн. вечер 01.01.2022 10.01.2022 Д.В. Семенникова Плавикс 75 мг (1 таб. 75 мг) 1 р/д внутрь на 12 дн. утро 01.01.2022 10.01.2022 Д.В. Семенникова Омепразол 20 мг 1 р/д внутрь на 30 дн. Утром до еды 01.01.2022 10.01.2022 Д.В. [ФИО] Мельникова Tab.Trankvezipami 1 mg (1 таб. 1 mg) 1 р/д внутрь на 5 дн. по 1 табл. на ночь 06.01.2022 10.01.2022 Д.В. Семенникова 30.12.2021\nЭКГ на месте(Прил 5.2) 30.12.2021 Коронарография (Прил 5.2) 30.12.2021\nЭКГ дежурная смена (с 16 часов)(Прил 5.2) 30.12.2021 СТАЦИОНАР.\nКонсультация ВК ВТМП дорогостоящие расходные материалы; 2 коронарных стента с лекарственным покрытием + расходный материал для ТЛБАП 31.12.2021\nЭКГ дежурная смена (с 16 часов)(Прил 5.2) 01.01.2022 Тропонин I, миоглобин, СК МВ (экспресс) 01.01.2022\nБиохимический анализ крови_экспресс 01.01.2022\nОбщий анализ крови_экспресс 01.01.2022 Коагулогия_экспресс 01.01.2022 Группа крови и фенотип_экспресс 01.01.2022\nАнализ крови на ВИЧ 01.01.2022\nОбщий анализ мочи (Урискан) 01.01.2022 Эхокардиография (Прил.7) РОДДОМ, ТЕРАПИЯ, РСЦ,П-ка 01.01.2022 aHCV (сумм) 01.01.2022 HBs Ag 01.01.2022\nЭКГ на месте(Прил 5.2) 01.01.2022 Кровь на КСР (Сифилис ИФА РМП (ЭДС)) 01.01.2022 Коагулогия (SYSMEX CA-1500) 01.01.2022 Агрегация с индукторами 01.01.2022 Troponin I (колличественный) 01.01.2022 Кал на я/глистов 01.01.2022\nЭКГ дежурная смена (с 16 часов)(Прил 5.2) 03.01.2022\nБиохимический анализ крови (Автомат) 03.01.2022\nЛейкоцитарная формула 03.01.2022\nОбщий анализ мочи (Урискан) 03.01.2022\nЭКГ на месте(Прил 5.2) 03.01.2022 Р-графия легких(Прил. 5_2) 03.01.2022\nОбщий анализ крови 03.01.2022 Коагулогия (SYSMEX CA-1500) 03.01.2022 Агрегация с индукторами 03.01.2022 Суточное мониторирование\nЭКГ(5_2) 06.01.2022\nЭКГ на месте(Прил 5.2) 06.01.2022 Кал на я/глистов 06.01.2022 Суточное мониторирование\nЭКГ(5_2) 06.01.2022\nЭКГ\nконсультация врача ФД (анализ) 10.01.2022 СТАЦИОНАР. Направление на ВК по больничному листу ЛИСТ ПОЧАСОВЫХ НАЗНАЧЕНИЙ на 30.12.2021\nФ.И.О. [ФИО] , возраст 60 лет , гр.крови ____ Rh+ Дата госпитализации: 30.12.2021 ИБ № 25177\nПалата: 2 Дата поступления в\nотделение Реанимации и интенсивной терапии РСЦ : 30.12.2021\nДиагноз: ИБС. Нестабильная стенокардия высокого риска. ОСН I ФК по Killip. Диета: __________ (___.___.2021) Режим: __________ (___.___.2021) Рост: 168 см Вес: 85 кг Название препарата/смеси 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 1 2 3 4 5 6 7 8 Всего Омез 20 мг нет 20 20 мг автовыполнение из ICCA Аторис 40 мг нет 40 40 мг автовыполнение из ICCA Плавикс 75 мг нет 75 75 мг автовыполнение из ICCA Тромбо АСС 100 мг нет 100 100 мг автовыполнение из ICCA Лизиноприл 5 мг нет 5 5 мг автовыполнение из ICCA 30.12.2021\nЭКГ на месте(Прил 5.2) [ФИО] 30.12.2021 Коронарография (Прил 5.2) [ФИО] Врач: НЕ СОГЛАСОВАНО В.К. Подпись: __________ Медсестра: ____________________ Подпись: __________ Зав.\nотделением: [ФИО] Подпись: __________ ЛИСТ ПОЧАСОВЫХ НАЗНАЧЕНИЙ на 31.12.2021\nФ.И.О. [ФИО] , возраст 60 лет , гр.крови ____ Rh+ Дата госпитализации: 30.12.2021 ИБ № 25177\nПалата: 2 Дата поступления в\nотделение Реанимации и интенсивной терапии РСЦ : 30.12.2021\nДиагноз: п/о: ИБС. Нестабильная стенокардия высокого риска. ОСН I ФК по Killip. Диета: __________ (___.___.2021) Режим: __________ (___.___.2021) Рост: 168 см Вес: 85 кг Название препарата/смеси 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 1 2 3 4 5 6 7 8 Всего Омез 20 мг нет 20 20 мг автовыполнение из ICCA Аторис 40 мг нет 40 40 мг автовыполнение из ICCA Пла

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from gensim.models import Word2Vec, FastText

In [13]:
df1['anonymized_text_data'] = df1['anonymized_text_data'].apply(lambda x: preprocess_text(x))

In [58]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    min_df=2,
    max_df=0.9,
    ngram_range=(1, 3),
    analyzer='word',
    sublinear_tf=True
)

X_texts = vectorizer.fit_transform(df1["anonymized_text_data"])

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, classification_report

In [27]:
df1["processed"] = vectorizer.fit_transform(df1["anonymized_text_data"])

TypeError: sparse array length is ambiguous; use getnnz() or shape[0]

In [59]:
print()

In [33]:
df1["label"] = df1["label"].map({'Да': 1, 'Нет': 0})

In [60]:
X_train_full, X_val, y_train_full, y_val = train_test_split(
    X_texts, df1["label"], test_size=0.2, random_state=42, stratify=df1["label"]
)

In [61]:
X_train, X_test, y_train, y_test = train_test_split(
    X_train_full, y_train_full, test_size=0.2, random_state=42, stratify=y_train_full
)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X_texts, df1["label"], test_size=0.2, random_state=42, stratify=df1["label"]
)

In [25]:
df_train

,file_name,patient_id,anonymized_text_data,label
6406,НикитенкоВП_history_0.html,19932.0,фио приморский краевой клинический больница 69...,Нет
909,МореваВН12270_history_0.html,12270.0,фио приморский краевой клинический больница 69...,Нет
8958,МисюринаАП_history_0.html,20526.0,фио приморский краевой клинический больница 69...,Нет
7326,ХильТА11840_history_0.html,11840.0,фио приморский краевой клинический больница 69...,Нет
5002,МолочинаОВ12871_history_0.html,12871.0,фио приморский краевой клинический больница 69...,Нет
...,...,...,...,...
8798,ГригорянМР_history_0.html,7578.0,фио приморский краевой клинический больница 69...,Нет
5574,ЧечельЕП_history_0.html,21324.0,фио приморский краевой клинический больница 69...,Нет
2702,ЮнРН4055_history_0.html,4055.0,фио приморский краевой клинический больница 69...,Нет
3671,ШишкинВК_history_0.html,12819.0,фио приморский краевой клинический больница 69...,Нет
4122,ПикулаОВ5109_history_0.html,5109.0,фио приморский краевой клинический больница 69...,Нет

In [37]:
y_val

8366    0
6802    0
4816    0
1012    0
9585    0
       ..
2221    0
4941    0
4800    0
481     0
9730    0
Name: label, Length: 2092, dtype: int64

In [41]:
y_val

8366    0
6802    0
4816    0
1012    0
9585    0
       ..
2221    0
4941    0
4800    0
481     0
9730    0
Name: label, Length: 2092, dtype: int64

In [62]:
text_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)

text_model.fit(X_train, y_train)

y_pred_proba = text_model.predict_proba(X_val)[:, 1]
y_pred = text_model.predict(X_val)
auc = roc_auc_score(y_val, y_pred_proba)
print(f"AUC на val: {auc:.4f}")

AUC на val: 0.9988

In [63]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      2003
           1       0.83      0.98      0.90        89

    accuracy                           0.99      2092
   macro avg       0.91      0.98      0.95      2092
weighted avg       0.99      0.99      0.99      2092

In [64]:
y_pred_proba = text_model.predict_proba(X_test)[:, 1]
y_pred = text_model.predict(X_test)
auc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC на val: {auc:.4f}")

AUC на val: 0.9973

In [65]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      1603
           1       0.87      0.94      0.91        71

    accuracy                           0.99      1674
   macro avg       0.93      0.97      0.95      1674
weighted avg       0.99      0.99      0.99      1674

In [49]:
text_model.coef_

array([[ 0.05871388, -0.00336014, -0.11952745, ...,  0.32387704,
         0.12455201,  0.12455201]], shape=(1, 10000))

In [66]:
feature_names = vectorizer.get_feature_names_out()

In [56]:
import numpy as np

In [68]:
coefs = text_model.coef_[0]  # для бинарной классификации

# индексы сортировки по абсолютной важности
top_indices = np.argsort(np.abs(coefs))[::-1][:50]  # топ-20

# печатаем топ
for idx in top_indices:
    print(f"{feature_names[idx]}: {coefs[idx]:.4f}")

мероприятие: 3.7956
адреналин: 3.0517
реанимационный: 2.5957
отметить: 2.1852
катетеризация: 2.0405
прекратить: 1.9414
подключичный: 1.8158
центральный: 1.8068
катетеризация подключичный: 1.7783
катетеризация подключичный другой: 1.7759
подключичный другой: 1.7759
другой центральный: 1.7759
подключичный другой центральный: 1.7759
другой центральный вено: 1.7749
центральный вено: 1.7443
шок: 1.6105
минут: 1.5468
кардиогенный шок: 1.5216
стенка левый желудочек: 1.5077
норадреналин: 1.4662
стенка левый: 1.4611
др: 1.3988
sol morphini hydrochloridi: 1.3772
hydrochloridi: 1.3771
morphini hydrochloridi: 1.3771
sol morphini: 1.3761
morphini: 1.3755
биологический: 1.2667
morphini hydrochloridi ml: 1.2068
hydrochloridi ml: 1.2068
фио sol morphini: 1.1959
ketamini: 1.1817
sol ketamini: 1.1817
номер история: 1.1756
цель седации: 1.1738
седации: 1.1497
центральный вено рсц: 1.1321
вено рсц: 1.1321
свидетельство рождение: 1.1315
ребёнок: 1.1128
зонд: 1.1086
hydrochloridi ml один: 1.0482
медицинский помощи: 1.0463
помощи: 1.0453
ketamini ml: 1.0340
sol ketamini ml: 1.0340
фио sol ketamini: 1.0081
кардиогенный: 1.0025
ивл: 0.9741
отечь лёгкий: 0.9669

In [28]:
count = 0
for i in sorted(y_pred):
    if i == 'Да':
        count += 1

print(count)

126

In [ ]:
print("Hello world")

In [ ]:
y_pred_proba = text_model.predict_proba(df_test["processed"])[:, 1]
y_pred = text_model.predict(df_test["processed"])
auc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC на val: {auc:.4f}")

In [ ]:
print(classification_report(y_test, y_pred))