In [8]:
!pip install -U nltk pymorphy2 pymorphy2-dicts-ru pymorphy3

Requirement already satisfied: nltk in /opt/conda/lib/python3.11/site-packages (3.9.2)
Requirement already satisfied: pymorphy2 in /opt/conda/lib/python3.11/site-packages (0.9.1)
Requirement already satisfied: pymorphy2-dicts-ru in /opt/conda/lib/python3.11/site-packages (2.4.417127.4579844)
Collecting pymorphy3
  Downloading pymorphy3-2.0.6-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: click in /opt/conda/lib/python3.11/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /opt/conda/lib/python3.11/site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /opt/conda/lib/python3.11/site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from nltk) (4.66.1)
Requirement already satisfied: dawg-python>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from pymorphy2) (0.7.2)
Requirement already satisfied: docopt>=0.6 in /opt/conda/lib/python3.11/site-packages (from pymorphy2) (0.6.2)
Collecting dawg2-python>=0.8.0 (from pymorphy3)
  Downloading dawg2_python-0.9.0-py3-none-any.whl.metadata (7.5 kB)
Collecting pymorphy3-dicts-ru (from pymorphy3)
  Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl.metadata (2.0 kB)
Downloading pymorphy3-2.0.6-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.9/53.9 kB 308.0 kB/s eta 0:00:00a 0:00:01
Downloading dawg2_python-0.9.0-py3-none-any.whl (9.3 kB)
Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 6.6 MB/s eta 0:00:0000:0100:01
Installing collected packages: pymorphy3-dicts-ru, dawg2-python, pymorphy3
Successfully installed dawg2-python-0.9.0 pymorphy3-2.0.6 pymorphy3-dicts-ru-2.4.417150.4580142

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [14]:
import re
import nltk
from nltk.corpus import stopwords
import pymorphy3
import pandas as pd

In [13]:
# Для русских текстов
morph = pymorphy3.MorphAnalyzer(lang='ru')
stop_words = set(stopwords.words('russian'))

def preprocess_text(text):
    # Удаление цензурных символов (****, ### и т.д.)
    text = re.sub(r'[*#]+', '', text)
    
    # Удаление спецсимволов, но сохранение основных знаков препинания
    text = re.sub(r'[^a-zA-Zа-яА-ЯёЁ0-9\s.,!?-]', ' ', text)
    
    # Приведение к нижнему регистру
    text = text.lower()
    
    # Токенизация
    tokens = text.split()
    
    # Удаление стоп-слов и лемматизация
    cleaned_tokens = []
    for token in tokens:
        if token not in stop_words and len(token) > 2:
            lemma = morph.parse(token)[0].normal_form
            cleaned_tokens.append(lemma)
    
    return ' '.join(cleaned_tokens)

In [52]:
table_data = pd.read_excel("../../data_raw/DataSet_V49 (2).xlsx")

In [53]:
text_data = pd.read_csv("../../anonymized_parsed_data_v8.csv")

In [54]:
text_data

,file_name,patient_id,anonymized_text_data
0,АсатрянРС_analyzes_0.html,7365.0,"Подождите, пожалуйста... Идет подготовка к выв..."
1,СтаценкоНА_analyzes_0.html,18865.0,"Подождите, пожалуйста... Идет подготовка к выв..."
2,ДмитриеваЛН_analyzes_0.html,3137.0,"Подождите, пожалуйста... Идет подготовка к выв..."
3,ПетровЕГ_analyzes_0.html,554.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4,ВласенкоВГ_analyzes_0.html,1504.0,"Подождите, пожалуйста... Идет подготовка к выв..."
...,...,...,...
4398,ГорчаковаДМ_analyzes_0.html,12845.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4399,КорниенкоЛД_analyzes_0.html,13202.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4400,КоноваловВадимГерманович14917_analyzes_0.html,14917.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4401,КоробейниковЕА_analyzes_0.html,19044.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4402,МайороваЛС_analyzes_0.html,16859.0,"Подождите, пожалуйста... Идет подготовка к выв..."

In [17]:
text_data["patient_id"] = text_data["patient_id"].astype(object)

In [18]:
text_data

,file_name,patient_id,anonymized_text_data
0,АсатрянРС_analyzes_0.html,7365.0,"Подождите, пожалуйста... Идет подготовка к выв..."
1,СтаценкоНА_analyzes_0.html,18865.0,"Подождите, пожалуйста... Идет подготовка к выв..."
2,ДмитриеваЛН_analyzes_0.html,3137.0,"Подождите, пожалуйста... Идет подготовка к выв..."
3,ПетровЕГ_analyzes_0.html,554.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4,ВласенкоВГ_analyzes_0.html,1504.0,"Подождите, пожалуйста... Идет подготовка к выв..."
...,...,...,...
4398,ГорчаковаДМ_analyzes_0.html,12845.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4399,КорниенкоЛД_analyzes_0.html,13202.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4400,КоноваловВадимГерманович14917_analyzes_0.html,14917.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4401,КоробейниковЕА_analyzes_0.html,19044.0,"Подождите, пожалуйста... Идет подготовка к выв..."
4402,МайороваЛС_analyzes_0.html,16859.0,"Подождите, пожалуйста... Идет подготовка к выв..."

In [55]:
table_data.dropna(subset=['Смерть'], inplace=True)

In [21]:
df2_subset = table_data[['Код пациента', 'Смерть']]
df2_subset.rename(columns={'Код пациента': 'patient_id', 'Смерть': 'label'}, inplace=True)

df2_subset["patient_id"] = df2_subset["patient_id"].astype(str)
text_data['patient_id'] = text_data['patient_id'].apply(lambda x: str(int(x)) if pd.notna(x) else None)

# Делаем merge по идентификатору
df1 = text_data.merge(df2_subset, on='patient_id', how='inner')

/tmp/ipykernel_2110872/4045082474.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_subset.rename(columns={'Код пациента': 'patient_id', 'Смерть': 'label'}, inplace=True)
/tmp/ipykernel_2110872/4045082474.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_subset["patient_id"] = df2_subset["patient_id"].astype(str)

In [23]:
df1["label"].value_counts()

label
Нет    697
Да      33
Name: count, dtype: int64

In [59]:
df1['anonymized_text_data'] = df1['anonymized_text_data'].apply(lambda x: preprocess_text(x))

In [57]:
df2_subset = table_data[['Файл(Анализы)', 'Смерть']]
df2_subset.rename(columns={'Файл(Анализы)': 'file_name', 'Смерть': 'label'}, inplace=True)

df2_subset["file_name"] = df2_subset["file_name"].astype(str)
# text_data['file_name'] = text_data['file_name'].apply(lambda x: str(int(x)) if pd.notna(x) else None)

# Делаем merge по идентификатору
df1 = text_data.merge(df2_subset, on='file_name', how='inner')

/tmp/ipykernel_2110872/3919788308.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_subset.rename(columns={'Файл(Анализы)': 'file_name', 'Смерть': 'label'}, inplace=True)
/tmp/ipykernel_2110872/3919788308.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_subset["file_name"] = df2_subset["file_name"].astype(str)

In [58]:
df1

,file_name,patient_id,anonymized_text_data,label
0,АсатрянРС_analyzes_0.html,7365.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
1,ПетровЕГ_analyzes_0.html,554.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
2,ДиктяревАВ_analyzes_0.html,10765.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
3,СвергунСЛ3428_analyzes_0.html,3428.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
4,КаргинСП5884_analyzes_0.html,5884.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
...,...,...,...,...
2875,БелоцерковецЖП4941_analyzes_0.html,4941.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
2876,ЛегаевГФ_analyzes_0.html,10622.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
2877,ГорчаковаДМ_analyzes_0.html,12845.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
2878,КорниенкоЛД_analyzes_0.html,13202.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет
2879,КоноваловВадимГерманович14917_analyzes_0.html,14917.0,"Подождите, пожалуйста... Идет подготовка к выв...",Нет

In [60]:
df1['anonymized_text_data'][0]

'подождите, пожалуйста... идти подготовка вывод обследование воздействий. это занять несколько минут. 100 учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница общий анализ кровь экспресс выполнить 03.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение реанимация интенсивный терапия рсц палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. направить врач-реаниматолог фио дата направление 03.05.2019 дата взятие биоматериал 03.05.2019 время исследовать компонент результат референсный значение единица измерение лейкоцит wbc 6.7 3.9-9 лимфоцит lym 0.8 1.2-3 лимфоцит lym 11.9 19-37 эритроцит rbc 3.85 3.9-5 гемоглобин hgb 116 120-160 гематокрит hct 30.4 36-48 средний объём эритроцит mcv 79.1 80-100 средний содержание гемоглобин эритроцит mch 30.1 27-31 ср. концентрация гемоглобин эритроцит mchc 381 300-380 тромбоцит plt 145 150-400 средний объём тромбоцит mpv 7.9 7.4-10.4 pct 0.11 0.15-0.4 анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница биохимический анализ кровь экспресс выполнить 03.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение реанимация интенсивный терапия рсц палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. направить врач-реаниматолог фио дата направление 03.05.2019 дата взятие биоматериал 03.05.2019 время исследовать компонент результат референсный значение единица измерение исследовать компонент результат референсный значение единица измерение креатинин 108.1 62-115 мкмоль мочевина 5.47 1.7-8.3 ммоль анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница лейкоцитарный формула экспресс выполнить 05.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. направить врач-реаниматолог фио дата направление 03.05.2019 дата взятие биоматериал 05.05.2019 время исследовать компонент результат референсный значение единица измерение эозинофил 1-5 палочкоядерный нейтрофил 1-6 сегментоядерный нейтрофил 47-72 лимфоцит 19-37 моноцит 3-11 базофил промиелоцит миелоцит метамиелоцит атипичный мононуклеар плазматический клетка нормобласт бласт широкоплазменный лимфоцит анализ выполнить фио учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница общий анализ кровь экспресс выполнить 05.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. направить врач-реаниматолог фио дата направление 03.05.2019 дата взятие биоматериал 05.05.2019 время исследовать компонент результат референсный значение единица измерение лейкоцит wbc 3.9-9 нейтрофил neu 1-6 лимфоцит lym 1.2-3 моноцит mon 0.09-0.6 эозинофил eos 0.02-0.3 базофил bas 0.06 нейтрофил neu 47-72 лимфоцит lym 19-37 моноцит mon 3-11 эозинофил eos 0.5-5 базофил bas эритроцит rbc 3.9-5 гемоглобин hgb 120-160 гематокрит hct 36-48 средний объём эритроцит mcv 80-100 средний содержание гемоглобин эритроцит mch 27-31 ср. концентрация гемоглобин эритроцит mchc 300-380 rdw-cv 11.5-14.5 rdw-sd 35-56 тромбоцит plt 150-400 средний объём тромбоцит mpv 7.4-10.4 pdw 10-20 pct 0.15-0.4 p-lcc 30-90 p-lcr 11-45 соэ экспресс анализ выполнить фио комментарий анализ проба учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница общий анализ мочить урискать экспресс выполнить 05.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. направить врач-реаниматолог фио дата направление 03.05.2019 дата взятие биоматериал 05.05.2019 время исследовать компонент результат референсный значение единица измерение эритроцит bld реакция белок количественно 0.1 анализ выполнить фио комментарий анализ проба учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница биохимический анализ кровь экспресс выполнить 05.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. направить врач-реаниматолог фио дата направление 03.05.2019 дата взятие биоматериал 05.05.2019 время исследовать компонент результат референсный значение единица измерение исследовать компонент результат референсный значение единица измерение глюкоза 3.3-6 ммоль креатинин 62-115 мкмоль асат мочевина 1.7-8.3 ммоль алат кфк экспресс 190 билирубин общий 25.7 мкмоль кфк мв-фракца экспресс анализ выполнить фио комментарий анализ проба учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница коагулогия экспресс выполнить 05.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. направить врач-реаниматолог фио дата направление 03.05.2019 дата взятие биоматериал 05.05.2019 время исследовать компонент результат референсный значение единица измерение pt, пти квика 70-130 inr мно 0.9-1.2 фибриноген fbgmfu 1.8-3.5 аптво ачтво aptt 26.4-37.5 сечь анализ выполнить фио комментарий анализ проба учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница группа кровь фенотип экспресс выполнить 05.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. направить врач-реаниматолог фио дата направление 03.05.2019 дата взятие биоматериал 05.05.2019 время исследовать компонент результат референсный значение единица измерение анализ выполнить фио комментарий анализ проба учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница общий анализ кровь выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение лейкоцит wbc 3.7 3.9-9 нейтрофил neu 1.79 1-6 лимфоцит lym 1.44 1.2-3 моноцит mon 0.35 0.09-0.6 эозинофил eos 0.07 0.02-0.3 базофил bas 0.05 0.06 0.1 нейтрофил neu 48.3 47-72 лимфоцит lym 38.9 19-37 моноцит mon 9.5 3-11 эозинофил eos 1.9 0.5-5 базофил bas 1.4 эритроцит rbc 4.63 3.9-5 гемоглобин hgb 134 120-160 гематокрит hct 36-48 средний объём эритроцит mcv 86.4 80-100 средний содержание гемоглобин эритроцит mch 28.9 27-31 ср. концентрация гемоглобин эритроцит mchc 335 300-380 rdw-cv 14.6 11.5-14.5 11-16 rdw-sd 45.3 35-56 35-56 тромбоцит plt 165 150-400 средний объём тромбоцит mpv 10.1 7.4-10.4 pdw 12.3 10-20 9-17 10е9 pct 0.17 0.15-0.4 0.108-0.282 p-lcr 26.1 11-45 11-45 соэ 1-15 анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница troponin колличественный выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение иссл. troponini колличественный 0.1 анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница группа крови,rh,фенотип гемотрансфузия выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение группа кровь резус- принадлежность положительный анализ выполнить оператор кдл операторович учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница hbs выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение нbsag отрицательно анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница ahcv сумма выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение ahcv сумма отрицательно анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница лейкоцитарный формула выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение эозинофил 1-5 палочкоядерный нейтрофил 1-6 сегментоядерный нейтрофил 47-72 лимфоцит 19-37 моноцит 3-11 базофил промиелоцит миелоцит метамиелоцит атипичный мононуклеар плазматический клетка нормобласт бласт анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница анализ кровь вич выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение анализ кровь вич отрицательный анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница биохимический анализ кровь автомат выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение исследовать компонент результат референсный значение единица измерение глюкоза 5.41 3.3-6 ммоль 3.3-6.4 ммоль общий белок 74.34 65-85 66-88 асат 16.84 мочевой кислота 279.6 200-415 мкмоль мкмоль алат 13.5 кфк 107.39 190 билирубин общий 8.65 25.7 мкмоль 1.7-21 мкмоль кфк мв-фракца 12.45 билирубин связанный 3.66 5.2 ммоль 5.2 мкмоль сывороточный железо 14.26 9.5-30 мкмоль мкмоль холестерин общий 5.51 6.2 ммоль ммоль холестерин высокий плотность 1.35 0.9-1.54 ммоль триглицерид 1.23 0.45-1.12 ммоль ммоль холестерин низкий плотность 3.63 1.23-4.45 мкмоль креатинин 106.64 62-115 мкмоль 62-115 мкмоль с-реактивный белок 3.85 мочевина 4.53 1.7-8.3 ммоль 1.7-8.3 ммоль анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница общий анализ мочить урискать выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение билирубин bil обнаружить уробилинон uro норма ацетон ket обнаружить белок pro обнаружить нитрит nit обнаружить глюкоза glu обнаружить реакция удельный вес 1.01 лейкоцит leu обнаружить аскорбиновый кислота vic обнаружить цвет col светло-жёлтый глюкоза количественно белок количественно 0.1 лейкоцит п.зр. эритроцит п.зр. оксалат none слизь редк дрожжеподобный гриб none анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница кал глист выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение яйцо личинка гельминт обнаружить простейшее обнаружить анализ выполнить экг сердце ф.и.о. фио возраст год диагноз ритм чсс фио зона qrs дополнение результат заключение время мониторный наблюдение фон синусовый ритм чсс день 63-91 мин. средний ночью 66-78 мин. средний чсс норма зарегистрировать одиночный 4152 желудочковый экстрасистола периодически тип тригеминии, квадригеминии, парный групповой желудочковый экстрасистолы, одиночный 122 групповой наджелудочковый экстрасистолы, короткий пароксизм наджелудочковый тахикардии. ишемический изменение выявлены. дата 07.05.2019 время подпись фио учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница суточный мониторирование ф.и.о. фио возраст год фио результат заключение время смад зарегистрировать днемсистоло-диастолический гипертензия повышенный индекс времен,ночью-умеренный систоло-диастолический гипертензия повыш.инд.времени. дата 08.05.2019 время подпись фио учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница экг ф.и.о. фио возраст год фио заключение синусовый ритм чсс мин. рубцовый изменение миокард задний стенки. субэндокардиальный ишемия боков стенка дифференцировать гмлж дистрофический изменение миокарда. жэс экг. дата 03.05.2019 время подпись фио ультразвуковой исследование сердце ф.и.о. фио возраст год вес дата 06.05.2019 диагноз аорта уплотнить кальциноз ст., регургитация ст. фибриозный кольцо см. 2,6см уровень синус 3.8см. 2,4-3,9см. аортальный клапан уплотнен. амплитуда раскрытие полная. кровоток изменен.лж ао6 мм.рт.ст. левый желудочек предел нормы. кдр 5.0 5,7см. см. кср 3.4 см. 3,8см. кдо способ измерение м-режим зона выявить область зад-бок. диастолический дисфункция преобладание кровоток систола предсердий. мжп 1,2см. утолстить 0,7-1,1 зслж 1,1см. утолстить 0,7-1,1 мжп-движение нормальное. митральный клапан створка уплотнить пролапс ст. регургитация ст. фиброзный кольцо уплотнить кальциноз трикуспидальный пролапс ст. регургитация передний стенка 0.3 см. лёгочный клапан изменить лёгочный артерия изменить см. систолический давление пж, мм.рт.ст. мм.рт.ст. максимальный систолический градиент правый желудочек 2.5 см. 2,6см. 4-й камерный проекция см. 4,3х7,8см. правый предсердие 4,1х5,1 см. 4,5х5,2см левый предсердие 4,5х5,6 см. 4,5х5,2см мпп лоцироваться весь протяжение 10мма нижний полый вена 1.50 см., коллабировать дополнительный трабекула базальном, среднее отделе, область верхушка лж, перикардиальный выпот нет. заключение увеличение лп. фиброз небольшой гипокинез задне-боковой сегмент лж. ао, ф.к. створка аокл, мкл уплотнены. нед-ть аокл ст. нед-ть мкл ст, незначительный объему. vc-2 мм. небольшой гипертрофия мжп. глобальный сократимость хорошая. подпись фио учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница фио врача-лфк 06.05.2019 фио возраст год палата диагноз цель обследование ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. осмотр история болезнь ознакомлена. назначить лечебный гимнастика заболевание сердце перикарда. диагноз фио с.л. учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница эзофагогастродуоденоскопия диагностический 7365 ф.и.о. фио возраст год домашний адрес край. приморский, р-н. уссурийский, уссурийск, адрес вирусный гепатит вотр фио направление результат пищевод свободно проходим, слизистый розовая, розетка кардия смыкаться полностью. желудок умеренный количество секрета,складка расправляться перистальтика активный слизистый очаговый гиперемия тело антральный отдел антральный отделевый область привратник два эрозия 0,2см каждый поверхностный привратник проходим,слизистый луковица дпк очаговый гиперемией,ть выходной отдел стенка поверхностный эрозия 01см 0,2см красный дном. слизистый постбульбарный отдел изменена. заключение эрозивный гастродуоденопатия. дата 07.05.2019 время подпись фио учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница коронарография доза мзв ф.и.о. фио возраст год фио результат пунктировать radialis dext. выполнить полипроекционный лка ствол изменить пмжть значимый стеноз значимый стеноз пка стеноз далее значимый стенозов. заключение омт дата 03.05.2019 время подпись фио учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница обучение самоуход ф.и.о. фио возраст год фио занятие самоуходу. 1.ознакомление заболеванием. 2.обучение навык самоуход измерение ад, чд, чсс оказание первый доврачебный помощь 3.режим физический активности. 4.особенность питания. 5.соблюдение врачебный назначение ознакомление лекарственный препаратами, назначить врач дата 06.05.2019 время подпись фио учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница рентгеновский исследование р-графия лёгкий доза 0,15 мзв ф.и.о. фио возраст год фио результат заключение ро-грамм огп,от 06.05.2019г,стоя,определяться сердечный тень поперечник аорта нерасширена,видный склероз дуги.лёгочный поле очагово-инфильтративный затемнений,с обогащение деформация лёгочный рисунка.корень нерасширенные,структурный четкие.выпот плевральный полость нет.купол диафрагма расположить 7ом ребре,четкие. дата 07.05.2019 время подпись фио учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница коагулогия sysmex ca-1500 выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение pt, пти квика 101.6 70-130 70-130 сечь протромбиновый время 10.9 10.4-12.6 сечь 10.4-12.6 сечь inr мно 0.94 0.9-1.2 0.9-1.2 фибриноген fbgmfu 2.3 1.8-3.5 1.8-3.5 тромбиновый время 19.3 14-21 сечь 14-21 сечь аптво ачтво aptt 34.3 26.4-37.5 сечь 26.4-37.5 сечь анализ выполнить учреждение государственный бюджетный учреждение здравоохранение приморский краевой клинический больница электролит выполнить 06.05.2019 ф.и.о. фио дата рождение 24.03.1953 год отделение кардиохирургический палата медицинский карта 7365 диагноз ибс. нестабильный стенокардия умеренный риска. пикс. осн killip фон хсн ст., ф.к. фио фио направление 05.05.2019 дата взятие биоматериал 06.05.2019 время исследовать компонент результат референсный значение единица измерение натрий 143.7 130-150 ммоль 130-150 ммоль калий 3.79 3-5 ммоль 3-5 ммоль хлор 102.4 98-107 95-110 ммоль анализ выполнить учреждение государс

In [30]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /opt/conda/lib/python3.11/site-packages (from gensim) (2.3.5)
Requirement already satisfied: scipy>=1.7.0 in /opt/conda/lib/python3.11/site-packages (from gensim) (1.16.3)
Collecting smart_open>=1.8.1 (from gensim)
  Downloading smart_open-7.5.0-py3-none-any.whl.metadata (24 kB)
Collecting wrapt (from smart_open>=1.8.1->gensim)
  Downloading wrapt-2.0.1-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (9.0 kB)
Downloading gensim-4.4.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 9.6 MB/s eta 0:00:00:00:010:01m
Downloading smart_open-7.5.0-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 kB 7.8 MB/s eta 0:00:00
Downloading wrapt-2.0.1-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.1/114.1 kB 8.6 MB/s eta 0:00:00
Installing collected packages: wrapt, smart_open, gensim
Successfully installed gensim-4.4.0 smart_open-7.5.0 wrapt-2.0.1

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from gensim.models import Word2Vec, FastText

In [61]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    min_df=2,
    max_df=0.9,
    ngram_range=(1, 3),
    analyzer='char_wb',
    sublinear_tf=True
)

X_texts = vectorizer.fit_transform(df1["anonymized_text_data"])

In [34]:
X_texts

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1212588 stored elements and shape (730, 10000)>

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, classification_report

In [62]:
X_train, X_test, y_train, y_test = train_test_split(
    X_texts, df1["label"], test_size=0.2, random_state=42, stratify=df1["label"]
)

In [63]:
text_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)

text_model.fit(X_train, y_train)

y_pred_proba = text_model.predict_proba(X_test)[:, 1]
y_pred = text_model.predict(X_test)
auc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC на тесте: {auc:.4f}")

AUC на тесте: 0.9897

In [65]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          Да       0.54      0.90      0.68        21
         Нет       1.00      0.97      0.98       555

    accuracy                           0.97       576
   macro avg       0.77      0.94      0.83       576
weighted avg       0.98      0.97      0.97       576