In [4]:
%pip install hypothesis pytest

Requirement already satisfied: hypothesis in /opt/conda/lib/python3.11/site-packages (6.152.4)
Collecting pytest
  Downloading pytest-9.0.3-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: sortedcontainers<3.0.0,>=2.1.0 in /opt/conda/lib/python3.11/site-packages (from hypothesis) (2.4.0)
Collecting iniconfig>=1.0.1 (from pytest)
  Downloading iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: packaging>=22 in /opt/conda/lib/python3.11/site-packages (from pytest) (23.2)
Collecting pluggy<2,>=1.5 (from pytest)
  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pygments>=2.7.2 in /opt/conda/lib/python3.11/site-packages (from pytest) (2.16.1)
Downloading pytest-9.0.3-py3-none-any.whl (375 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 375.2/375.2 kB 839.2 kB/s eta 0:00:0000:0100:01
Downloading iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)
Installing collected packages: pluggy, iniconfig, pytest
  Attempting uninstall: pluggy
    Found existing installation: pluggy 1.3.0
    Uninstalling pluggy-1.3.0:
      Successfully uninstalled pluggy-1.3.0
Successfully installed iniconfig-2.3.0 pluggy-1.6.0 pytest-9.0.3
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import numpy as np
# from numpy.conftest import dtype

### ДОКА==Поступление==ИБ

In [7]:
d_v49=pd.read_excel("./data_raw/side_project/DataSet_V49_9_03_26.xlsx")
#display(d_v47.head())
display(f'Размер датасета: {d_v49.shape}')

'Размер датасета: (17426, 473)'

In [8]:
d_v49=d_v49[(d_v49['STEMI']=='Да')&
            (d_v49['ЧКВ']=='Да')&
            (d_v49['Наличие в БД']=='Да')&
            (d_v49['Наличие в файле']=='Да')]

In [9]:
d_v49.shape

(6253, 473)

In [10]:
#Определение начала года в датасете
d_v49.replace({'Начало операции(ИБ)(Новый)': '-'}, np.nan, inplace=True)#заменим '-' на NaN
d_v49['Начало операции(ИБ)(Новый)']= d_v49['Начало операции(ИБ)(Новый)'].astype("datetime64[ns]")
d_v49['дата поступления'] = pd.to_datetime(d_v49['дата поступления'], errors='coerce')
d_v49['Дата взятия биоматериала (Общий анализ крови)']= pd.to_datetime(d_v49['Дата взятия биоматериала (Общий анализ крови)'], errors='coerce')
d_v49['Дата STEMI']= pd.to_datetime(d_v49['Дата STEMI'], errors='coerce')
#у нас есть Синдромный диагноз и в поступлении подпишем чтобы не путаться
d_v49 = d_v49.rename(columns={'Синдромный диагноз': 'Синдромный диагноз ИБ'})

display(d_v49['Начало операции(ИБ)(Новый)'].isna().sum())
display(d_v49['Начало операции(ИБ)(Новый)'].sort_values().head(1))
display(d_v49['Начало операции(ИБ)(Новый)'].sort_values(ascending= False).head(1))
display(d_v49['Дата взятия биоматериала (Общий анализ крови)'].sort_values(ascending= False).head(1))
display(d_v49['Дата взятия биоматериала (Общий анализ крови)'].sort_values().head(1))
display(d_v49['Дата STEMI'].sort_values(ascending= False).head(1))
display(d_v49['Дата STEMI'].sort_values().head(1))

/tmp/ipykernel_91920/2912208443.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  d_v49.replace({'Начало операции(ИБ)(Новый)': '-'}, np.nan, inplace=True)#заменим '-' на NaN

np.int64(18)

17324   2014-06-12 07:00:00
Name: Начало операции(ИБ)(Новый), dtype: datetime64[ns]

16335   2024-12-02 13:30:00
Name: Начало операции(ИБ)(Новый), dtype: datetime64[ns]

2635   2022-02-17 09:35:00
Name: Дата взятия биоматериала (Общий анализ крови), dtype: datetime64[ns]

197   2015-02-05 16:44:00
Name: Дата взятия биоматериала (Общий анализ крови), dtype: datetime64[ns]

901   2024-10-28
Name: Дата STEMI, dtype: datetime64[ns]

10788   2012-01-11
Name: Дата STEMI, dtype: datetime64[ns]

In [11]:
#Дубликаты
#проверим наличие явных дубликатов
display(f'{d_v49.duplicated().sum()} явных дубликатов')

pd.set_option('display.max_rows', 100)

#Дубликаты по коду и имени
display(d_v49[d_v49[["Код пациента", "Name"]].duplicated(keep=False) == True])#keep=False все строки помечаются как дубликаты по 'Код пациента' и 'Name'

'10 явных дубликатов'

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,Диагноз Файл,Диагноз ИМ,Диагноз ИМ Дата,STEMI (Новый),...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
428,24-8185,Бондаренко СС,70.0,М,Да,Да,БондаренкоСС8185_history_0.html,Да,2024-04-21,Да,...,-9.7,NaN,15.7,15.7,NaN,15.7,15.7,NaN,NaN,NaN
429,24-8185,Бондаренко СС,70.0,М,Да,Да,БондаренкоСС8185_history_0.html,Да,2024-04-21,Да,...,-9.7,NaN,15.7,15.7,NaN,15.7,15.7,NaN,NaN,NaN
474,24-7688,Шевченко ИБ,59.0,М,Да,Да,ШевченкоИБ7688_history_0.html,Да,2024-04-16,Да,...,-11.9,NaN,15.5,15.5,NaN,15.5,15.5,NaN,285.6,285.6
475,24-7688,Шевченко ИБ,59.0,М,Да,Да,ШевченкоИБ7688_history_0.html,Да,2024-04-16,Да,...,-11.9,NaN,15.5,15.5,NaN,15.5,15.5,NaN,285.6,285.6
515,24-7431,Лященко АН,83.0,Ж,Да,Да,ЛященкоАН7431_history_0.html,Да,2024-04-10,Да,...,-7.2,17.3,17.3,17.3,17.3,17.3,17.3,NaN,NaN,NaN
516,24-7431,Лященко АН,83.0,Ж,Да,Да,ЛященкоАН7431_history_0.html,Да,2024-04-10,Да,...,-7.2,17.3,17.3,17.3,17.3,17.3,17.3,NaN,NaN,NaN
517,24-7431,Лященко АН,83.0,Ж,Да,Да,ЛященкоАН7431_history_0.html,Да,2024-04-10,Да,...,-7.2,17.3,17.3,17.3,17.3,17.3,17.3,NaN,NaN,NaN
518,24-7431,Лященко АН,83.0,Ж,Да,Да,ЛященкоАН7431_history_0.html,Да,2024-04-10,Да,...,-7.2,17.3,17.3,17.3,17.3,17.3,17.3,NaN,NaN,NaN
579,24-6985,Иванов ЕГ,53.0,М,Да,Да,ИвановЕГ6985_history_0.html,Да,2024-04-03,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
580,24-6985,Иванов ЕГ,53.0,М,Да,Да,ИвановЕГ6985_history_0.html,Да,2024-04-03,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585,24-665,Бакланов ВИ,83.0,М,Да,Да,БаклановВИ665_history_0.html,Да,2024-01-15,Да,...,-3.8,20.0,20.0,20.0,20.0,20.0,20.0,NaN,NaN,NaN
594,24-665,Бакланов ВИ,83.0,М,Да,Да,БаклановВИ665_history_0.html,Да,2024-01-15,Да,...,-3.8,20.0,20.0,20.0,20.0,20.0,20.0,NaN,NaN,NaN
602,24-6599,Михайлова ВП,71.0,Ж,Да,Да,МихайловаВП6599_history_0.html,Да,2024-03-31,Да,...,-9.8,15.2,15.2,15.2,15.2,15.2,15.2,NaN,NaN,NaN
603,24-6599,Михайлова ВП,71.0,Ж,Да,Да,МихайловаВП6599_history_0.html,Да,2024-03-31,Да,...,-9.8,15.2,15.2,15.2,15.2,15.2,15.2,NaN,NaN,NaN
620,24-6359,Козлов ВВ,47.0,М,Да,Да,КозловВВ6359_history_0.html,Да,2024-03-28,Да,...,-7.5,17.4,17.4,17.4,17.4,17.4,17.4,NaN,NaN,NaN
621,24-6359,Козлов ВВ,47.0,М,Да,Да,КозловВВ6359_history_0.html,Да,2024-03-28,Да,...,-7.5,17.4,17.4,17.4,17.4,17.4,17.4,NaN,NaN,NaN
812,24-4420,Гальмутдинов ТГ,71.0,М,Да,Да,ГальмутдиновТГ4420_history_0.html,Да,2024-03-01,Да,...,NaN,18.8,18.8,18.8,18.8,18.8,18.8,NaN,1800.0,1800.0
813,24-4420,Гальмутдинов ТГ,71.0,М,Да,Да,ГальмутдиновТГ4420_history_0.html,Да,2024-03-01,Да,...,NaN,18.8,18.8,18.8,18.8,18.8,18.8,NaN,1800.0,1800.0
928,24-29211,Калита СВ,45.0,М,Да,Да,КалитаСВ29211_history_0.html,Да,2024-10-21,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
929,24-29211,Калита СВ,45.0,М,Да,Да,КалитаСВ29211_history_0.html,Да,2024-10-21,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
949,24-29130,Даниленко СВ,42.0,М,Да,Да,ДаниленкоСВ29130_history_0.html,Да,2024-10-20,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
950,24-29130,Даниленко СВ,42.0,М,Да,Да,ДаниленкоСВ29130_history_0.html,Да,2024-10-20,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
984,24-2866,Панченко НИ,75.0,Ж,Да,Да,ПанченкоНИ2866_history_0.html,Да,2024-02-11,Да,...,NaN,NaN,20.1,20.1,NaN,23.2,23.2,NaN,NaN,NaN
986,24-2866,Панченко НИ,75.0,Ж,Да,Да,ПанченкоНИ2866_history_0.html,Да,2024-02-11,Да,...,NaN,NaN,20.1,20.1,NaN,23.2,23.2,NaN,NaN,NaN
1154,24-25992,Колмаков ДМ,45.0,М,Да,Да,КолмаковДМ25992_history_0.html,Да,2024-09-08,Да,...,-2.0,21.2,NaN,21.2,21.2,NaN,21.2,NaN,NaN,NaN
1155,24-25992,Колмаков ДМ,45.0,М,Да,Да,КолмаковДМ25992_history_0.html,Да,2024-09-08,Да,...,-2.0,21.2,NaN,21.2,21.2,NaN,21.2,NaN,NaN,NaN
1157,24-25979,Гоппорова БО,55.0,Ж,Да,Да,ГоппороваБО25979_history_0.html,Да,2024-09-10,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1158,24-25979,Гоппорова БО,55.0,Ж,Да,Да,ГоппороваБО25979_history_0.html,Да,2024-09-10,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1487,24-22825,Вершинин АМ,65.0,М,Да,Да,ВершининАМ22825_history_0.html,Да,2024-07-19,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1488,24-22825,Вершинин АМ,65.0,М,Да,Да,ВершининАМ22825_history_0.html,Да,2024-07-19,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1551,24-2260,Попов ВП,75.0,М,Да,Да,ПоповВП2260_history_0.html,Да,2024-02-02,Да,...,-8.3,16.7,16.7,16.7,16.7,16.7,16.7,NaN,NaN,NaN
1556,24-2260,Попов ВП,75.0,М,Да,Да,ПоповВП2260_history_0.html,Да,2024-02-02,Да,...,-8.3,16.7,16.7,16.7,16.7,16.7,16.7,NaN,NaN,NaN
1571,24-22179,Павлов ДВ,49.0,М,Да,Да,ПавловДВ22179_history_0.html,Да,2024-07-16,Да,...,-10.4,NaN,15.0,15.0,NaN,15.0,15.0,NaN,NaN,NaN
1572,24-22179,Павлов ДВ,49.0,М,Да,Да,ПавловДВ22179_history_0.html,Да,2024-07-16,Да,...,-10.4,NaN,15.0,15.0,NaN,15.0,15.0,NaN,NaN,NaN
1640,24-14374,Ефремова РС,77.0,Ж,Да,Да,ЕфремоваРС14374_history_0.html,Да,2024-07-09,Да,...,-6.7,NaN,18.1,18.1,NaN,18.1,18.1,NaN,NaN,NaN
1641,24-14374,Ефремова РС,77.0,Ж,Да,Да,ЕфремоваРС14374_history_0.html,Да,2024-07-09,Да,...,-6.7,NaN,18.1,18.1,NaN,18.1,18.1,NaN,NaN,NaN
1644,24-14257,Батуров АП,66.0,М,Да,Да,БатуровАП14257_history_0.html,Да,2024-07-07,Да,...,-5.1,NaN,11.9,11.9,NaN,13.9,13.9,NaN,NaN,NaN
1664,24-14257,Батуров АП,66.0,М,Да,Да,БатуровАП14257_history_0.html,Да,2024-07-07,Да,...,-5.1,NaN,11.9,11.9,NaN,13.9,13.9,NaN,NaN,NaN
1840,24-12386,Макаров ЛП,77.0,М,Да,Да,МакаровЛП12386_history_0.html,Да,2024-06-15,Да,...,-15.7,12.0,12.0,12.0,12.0,12.0,12.0,NaN,NaN,NaN
1841,24-12386,Макаров ЛП,77.0,М,Да,Да,МакаровЛП12386_history_0.html,Да,2024-06-15,Да,...,-15.7,12.0,12.0,12.0,12.0,12.0,12.0,NaN,NaN,NaN
1843,24-12371,Короткова ЛИ,64.0,Ж,Да,Да,КоротковаЛИ12371_history_0.html,Да,2024-06-14,Да,...,-10.9,NaN,14.4,14.4,NaN,14.6,14.6,NaN,NaN,NaN
1844,24-12371,Короткова ЛИ,64.0,Ж,Да,Да,КоротковаЛИ12371_history_0.html,Да,2024-06-14,Да,...,-10.9,NaN,14.4,14.4,NaN,14.6,14.6,NaN,NaN,NaN
1849,24-12351,Абрамов КВ,62.0,М,Да,Да,АбрамовКВ12351_history_0.html,Да,2024-06-13,Да,...,-9.1,NaN,15.7,15.7,NaN,15.7,15.7,NaN,NaN,NaN
1850,24-12351,Абрамов КВ,62.0,М,Да,Да,АбрамовКВ12351_history_0.html,Да,2024-06-13,Да,...,-9.1,NaN,15.7,15.7,NaN,15.7,15.7,NaN,NaN,NaN
1856,24-12120,Литвиненко РВ,69.0,Ж,Да,Да,ЛитвиненкоРВ12120_history_0.html,Да,2024-06-11,Да,...,-12.0,13.5,13.5,13.5,13.5,13.5,13.5,NaN,NaN,NaN
1857,24-12120,Литвиненко РВ,69.0,Ж,Да,Да,ЛитвиненкоРВ12120_history_0.html,Да,2024-06-11,Да,...,-12.0,13.5,13.5,13.5,13.5,13.5,13.5,NaN,NaN,NaN
1956,24-11380,Осина НИ,70.0,Ж,Да,Да,ОсинаНИ11380_history_0.html,Да,2024-05-30,Да,...,-8.8,NaN,14.3,14.3,NaN,16.8,16.8,NaN,1253.0,1253.0
1957,24-11380,Осина НИ,70.0,Ж,Да,Да,ОсинаНИ11380_history_0.html,Да,2024-05-30,Да,...,-8.8,NaN,14.3,14.3,NaN,16.8,16.8,NaN,1253.0,1253.0
1958,24-1136,Брындиков ВИ,74.0,М,Да,Да,БрындиковВИ1136_history_0.html,Да,2024-01-18,Да,...,-5.5,19.7,19.7,19.7,19.7,19.7,19.7,NaN,2526.0,2526.0
1959,24-1136,Брындиков ВИ,74.0,М,Да,Да,БрындиковВИ1136_history_0.html,Да,2024-01-18,Да,...,-5.5,19.7,19.7,19.7,19.7,19.7,19.7,NaN,2526.0,2526.0
2111,23-26025,Кашкарева ЛД,69.0,Ж,Да,Да,КашкареваЛД26025_history_0.html,Да,2023-12-24,Да,...,-2.3,NaN,21.2,21.2,NaN,22.0,22.0,NaN,NaN,NaN
2112,23-26025,Кашкарева ЛД,69.0,Ж,Да,Да,КашкареваЛД26025_history_0.html,Да,2023-12-24,Да,...,-2.3,NaN,21.2,21.2,NaN,22.0,22.0,NaN,NaN,NaN
2148,23-25956,Денисова ЛД,76.0,Ж,Да,Да,ДенисоваЛД25956_history_0.html,Да,2023-12-23,Да,...,2.7,25.0,25.0,25.0,25.7,25.7,25.7,NaN,NaN,NaN
2149,23-25956,Денисова ЛД,76.0,Ж,Да,Да,ДенисоваЛД25956_history_0.html,Да,2023-12-23,Да,...,2.7,25.0,25.0,25.0,25.7,25.7,25.7,NaN,NaN,NaN
2158,23-25773,Закревский ВЛ,71.0,М,Да,Да,ЗакревскийВЛ25773_history_0.html,Да,2024-01-10,Да,...,-5.2,NaN,19.9,19.9,NaN,19.9,19.9,NaN,NaN,NaN
2159,23-25773,Закревский ВЛ,71.0,М,Да,Да,ЗакревскийВЛ25773_history_0.html,Да,2024-01-10,Да,...,-5.2,NaN,19.9,19.9,NaN,19.9,19.9,NaN,NaN,NaN
2167,23-25475,Наумов АЮ,48.0,М,Да,Да,НаумовАЮ25475_history_0.html,Да,2023-12-17,Да,...,1.3,23.4,23.4,23.4,23.4,23.4,23.4,NaN,NaN,NaN
2168,23-25475,Наумов АЮ,48.0,М,Да,Да,НаумовАЮ25475_history_0.html,Да,2023-12-17,Да,...,1.3,23.4,23.4,23.4,23.4,23.4,23.4,NaN,NaN,NaN
2169,23-25474,Куприянов ВП,71.0,М,Да,Да,КуприяновВП25474_history_0.html,Да,2023-12-17,Да,...,1.5,23.8,23.8,23.8,24.7,24.7,24.7,NaN,NaN,NaN
2170,23-25474,Куприянов ВП,71.0,М,Да,Да,КуприяновВП25474_history_0.html,Да,2023-12-17,Да,...,1.5,23.8,23.8,23.8,24.7,24.7,24.7,NaN,NaN,NaN
2209,23-25134,Гмарь АА,78.0,М,Да,Да,ГмарьАА25134_history_0.html,Да,2023-12-12,Да,...,-5.6,19.0,19.0,19.0,19.0,19.0,19.0,NaN,NaN,NaN
2210,23-25134,Гмарь АА,78.0,М,Да,Да,ГмарьАА25134_history_0.html,Да,2023-12-12,Да,...,-5.6,19.0,19.0,19.0,19.0,19.0,19.0,NaN,NaN,NaN
2211,23-25075,Черданцев НИ,71.0,М,Да,Да,ЧерданцевНИ25075_history_0.html,Да,2023-12-11,Да,...,1.4,NaN,23.9,23.9,NaN,23.9,23.9,NaN,NaN,NaN
2212,23-25075,Черданцев НИ,71.0,М,Да,Да,ЧерданцевНИ25075_history_0.html,Да,2023-12-11,Да,...,1.4,NaN,23.9,23.9,NaN,23.9,23.9,NaN,NaN,NaN
2218,23-24950,Письменных КИ,60.0,М,Да,Да,ПисьменныхКИ24950_history_0.html,Да,2023-12-09,Да,...,-0.8,NaN,23.2,23.2,NaN,23.2,23.2,NaN,NaN,NaN
2219,23-24950,Письменных КИ,60.0,М,Да,Да,ПисьменныхКИ24950_history_0.html,Да,2023-12-09,Да,...,-0.8,NaN,23.2,23.2,NaN,23.2,23.2,NaN,NaN,NaN
2269,23-24950,Письменных КИ,60.0,М,Да,Да,ПисьменныхКИ24950_history_0.html,Да,2023-12-09,Да,...,-0.8,NaN,23.2,23.2,NaN,23.2,23.2,NaN,NaN,NaN
2270,23-24950,Письменных КИ,60.0,М,Да,Да,ПисьменныхКИ24950_history_0.html,Да,2023-12-09,Да,...,-0.8,NaN,23.2,23.2,NaN,23.2,23.2,NaN,NaN,NaN
2290,23-24079,Жиров СИ,62.0,М,Да,Да,ЖировСИ24079_history_0.html,Да,2023-11-27,Да,...,-0.4,NaN,21.1,21.1,NaN,21.1,21.1,NaN,NaN,NaN
2291,23-24079,Жиров СИ,62.0,М,Да,Да,ЖировСИ24079_history_0.html,Да,2023-11-27,Да,...,-0.4,NaN,21.1,21.1,NaN,21.1,21.1,NaN,NaN,NaN
2292,23-24079,Жиров СИ,62.0,М,Да,Да,ЖировСИ24079_history_0.html,Да,2023-11-27,Да,...,-0.4,NaN,21.1,21.1,NaN,21.1,21.1,NaN,NaN,NaN
2335,23-24079,Жиров СИ,62.0,М,Да,Да,ЖировСИ24079_history_0.html,Да,2023-11-27,Да,...,-0.4,NaN,21.1,21.1,NaN,21.1,21.1,NaN,NaN,NaN
2336,23-24079,Жиров СИ,62.0,М,Да,Да,ЖировСИ24079_history_0.html,Да,2023-11-27,Да,...,-0.4,NaN,21.1,21.1,NaN,21.1,21.1,NaN,NaN,NaN
2337,23-24079,Жиров СИ,62.0,М,Да,Да,ЖировСИ24079_history_0.html,Да,2023-11-27,Да,...,-0.4,NaN,21.1,21.1,NaN,21.1,21.1,NaN,NaN,NaN
2349,23-23800,Оглы РЧ,65.0,Ж,Да,Да,ОглыРЧ23800_history_0.html,Да,2023-11-23,Да,...,-5.3,NaN,17.9,17.9,NaN,19.4,19.4,NaN,1796.7,1796.7
2350,23-23800,Оглы РЧ,65.0,Ж,Да,Да,ОглыРЧ23800_history_0.html,Да,2023-11-23,Да,...,-5.3,NaN,17.9,17.9,NaN,19.4,19.4,NaN,1796.7,1796.7
2351,23-23800,Оглы РЧ,65.0,Ж,Да,Да,ОглыРЧ23800_history_0.html,Да,2023-11-23,Да,...,-5.3,NaN,17.9,17.9,NaN,19.4,19.4,NaN,1796.7,1796.7
2352,23-23800,Оглы РЧ,65.0,Ж,Да,Да,ОглыРЧ23800_history_0.html,Да,2023-11-23,Да,...,-5.3,NaN,17.9,17.9,NaN,19.4,19.4,NaN,1796.7,1796.7
2514,23-21656,Мирошников ВА,74.0,М,Да,Да,МирошниковВА21656_history_0.html,Да,2023-10-25,Да,...,-1.7,NaN,20.8,20.8,NaN,20.8,20.8,NaN,NaN,NaN
2515,23-21656,Мирошников ВА,74.0,М,Да,Да,МирошниковВА21656_history_0.html,Да,2023-10-25,Да,...,-1.7,NaN,20.8,20.8,NaN,20.8,20.8,NaN,NaN,NaN
2516,23-21606,Панова МЛ,63.0,Ж,Да,Да,ПановаМЛ21606_history_0.html,Да,2023-10-18,Да,...,-2.0,21.6,21.6,21.6,21.6,21.6,21.6,NaN,NaN,NaN
2517,23-21606,Панова МЛ,63.0,Ж,Да,Да,ПановаМЛ21606_history_0.html,Да,2023-10-18,Да,...,-2.0,21.6,21.6,21.6,21.6,21.6,21.6,NaN,NaN,NaN
2573,23-21143,Котович АА,52.0,М,Да,Да,КотовичАА21143_history_0.html,Да,2023-10-19,Да,...,-5.6,17.6,17.6,17.6,17.6,17.6,17.6,NaN,NaN,NaN
2574,23-21143,Котович АА,52.0,М,Да,Да,КотовичАА21143_history_0.html,Да,2023-10-19,Да,...,-5.6,17.6,17.6,17.6,17.6,17.6,17.6,NaN,NaN,NaN
5690,17-5411,Ким АП,65.0,Ж,Да,Да,КимАП_history_0.html,Да,2017-04-04,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10799,17-5411,Ким АП,61.0,Ж,Да,Да,КимАП_history_0.html,Да,2017-04-04,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15482,23-23215,Арефьев ВН,68.0,М,Да,Да,АрефьевВН23215_history_0.html,Да,2023-11-24,Да,...,-3.5,NaN,19.2,19.2,NaN,20.1,20.1,NaN,NaN,NaN
15485,23-23215,Арефьев ВН,68.0,М,Да,Да,АрефьевВН23215_history_0.html,Да,2023-11-24,Да,...,-3.5,NaN,19.2,19.2,NaN,20.1,20.1,NaN,NaN,NaN
16335,24-31461,Слаута НП,70.0,Ж,Да,Да,СлаутаНП31461_history_0.html,Да,2024-12-09,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16340,24-31461,Слаута НП,70.0,Ж,Да,Да,СлаутаНП31461_history_0.html,Да,2024-12-09,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div id='q-high-1'></div>
<div style="background: #FDD; border-left: 40px solid #F00; padding: 10px;">
🔴 <b>Вопрос: </b> Почему мы здесь выбрасываем дубликаты, сгруппированные по коду пациента и name?
</div>

У нас могут быть различные случаи госпитализации одного и того же пациента в разное время. Мы можем расценивать это как разные посещения разных пациентов и обрабатывать их соответственно (с дальнейшей стратификацией по пациенту)

In [12]:
#оставим первое вхождение, так как первая строка больше заполнена
d_v49 = d_v49.drop_duplicates(subset=["Код пациента", "Name"], keep='first')

In [13]:
d_v49.shape

(6203, 473)

In [14]:
d_v49["Код пациента"].nunique()

6203

### РЕАНИМАЦИЯ

In [15]:
#Таблица Реанимация из Наша база версия 1.2
reanimation = pd.read_csv("./data_raw/side_project/Reanimaciya.csv", sep=',')
display(reanimation.head())
display(f'Размер датасета: {reanimation.shape}')

,№,Код пациента,Повторный,Экстренный,Поступил,Перевод,Умер,APACHE2 1сутки,APACHE2 3дня,APACHE2 выписка,...,допмин,норадреналин,левосимендан,доза адреналина,доза добутамина,доза допмина,доза норадреналина,мезатон,доза мезатона,Тирофибан
0,14299,21-3684,0,1,03/07/21 00:00:00,03/09/21 00:00:00,0,13.0,0.0,0.0,...,0,0,0,NaN,NaN,NaN,NaN,0,NaN,0
1,14301,21-3691,0,1,03/08/21 00:00:00,03/09/21 00:00:00,0,10.0,0.0,0.0,...,0,0,0,NaN,NaN,NaN,NaN,0,NaN,0
2,14302,21-3698,0,1,03/09/21 00:00:00,03/10/21 00:00:00,0,14.0,0.0,0.0,...,0,0,0,NaN,NaN,NaN,NaN,0,NaN,0
3,14303,21-3693,0,1,03/08/21 00:00:00,03/09/21 00:00:00,0,6.0,0.0,0.0,...,0,0,0,NaN,NaN,NaN,NaN,0,NaN,0
4,14304,21-3692,0,1,03/08/21 00:00:00,03/10/21 00:00:00,0,16.0,0.0,0.0,...,0,0,0,NaN,NaN,NaN,NaN,0,NaN,0

'Размер датасета: (24194, 41)'

In [16]:
#Определение начала года в датасете
reanimation['Поступил']= reanimation['Поступил'].astype("datetime64[ns]")
display(reanimation['Поступил'].isna().sum())
display(reanimation['Поступил'].sort_values().head(1))
#конец года
display(reanimation['Поступил'].sort_values(ascending= False).head(1))

np.int64(0)

218   2014-12-28
Name: Поступил, dtype: datetime64[ns]

22889   2024-11-19
Name: Поступил, dtype: datetime64[ns]

In [17]:
#Дубликаты
#проверим наличие явных дубликатов
display(f'{reanimation.duplicated().sum()} явных дубликатов')

'0 явных дубликатов'

In [18]:
reanimation.shape

(24194, 41)

### Объединение датасетов

In [19]:
#Добавление в 'Код пациента' части перед дефисом, которая несет информацию про год
d_v49['Код пациента'] = d_v49['Код пациента'].astype(str)

#Извлечение части кода после символа '-'
d_v49['Код после дефиса'] = d_v49['Код пациента'].apply(lambda x: x.split('-')[-1] if '-' in x else x)

#Так как код после - не уникальный, то мы должны добавить 2 цифры в начало
#Так как первые две цифры в коде пациента это год, добавим эти цифры,
#год возьмем из столбца 'Начало операции(ИБ)(Новый)'
# Добавление года в код пациента
def add_year(code_patient, date):
    if '-' not in code_patient and pd.notna(date):  # Проверяем, есть ли '-' и не является ли дата NaT
        year = date.year % 100  # Получаем два последних числа года
        return f"{year}-{code_patient}"  # Формируем новый код
    return code_patient  # Возвращаем оригинальный код

d_v49.replace({'Начало операции(ИБ)(Новый)': '-'}, np.nan, inplace=True)#заменим '-' на NaN
d_v49['Начало операции(ИБ)(Новый)']= d_v49['Начало операции(ИБ)(Новый)'].astype("datetime64[ns]")

d_v49['дата поступления'] = pd.to_datetime(d_v49['дата поступления'], errors='coerce')
#Применение функции к DataFrame
d_v49['Код пациента'] = d_v49.apply(lambda row: add_year(row['Код пациента'],
                                                         row['Начало операции(ИБ)(Новый)']), axis=1)
d_v49['Код пациента'] = d_v49.apply(
    lambda row: add_year(row['Код пациента'], row['Начало операции(ИБ)(Новый)']
                         if pd.notna(row['Начало операции(ИБ)(Новый)']) else row['дата поступления']),
    axis=1
)

In [20]:
#Дубликаты по коду и имени
display(d_v49[d_v49[["Код пациента", "Name"]].duplicated(keep=False) == True])#keep=False все строки помечаются как дубликаты по 'Код пациента' и 'Name'

#Дубликаты
#проверим наличие явных дубликатов
display(f'{reanimation.duplicated().sum()} явных дубликатов')

Empty DataFrame
Columns: [Код пациента, Name, Age, Sex, Наличие в БД, Наличие в файле, Диагноз Файл, Диагноз ИМ, Диагноз ИМ Дата, STEMI (Новый), noSTEMI, Диагноз Нестабильная стенакордия, STEMI, ЧКВ, Дата STEMI, Вид STEMI, SYNTAX Score, Инфаркт-зависимая артерия, Поражение ствола, Количество пораженных сосудов(Syntax), Количество пораженных сосудов(Значимость), TIMI, Инфаркт миокарда в анамнезе (<3), Инфаркт миокарда в анамнезе (>3), Инфаркт миокарда со стентированием в анамнезе, ОНМК (иш) в анамнезе, ОНМК (гем) в анамнезе, Стентирование в анамнезе, Тромболизис, Форма ФП, Калий, Дилатация предсердий, ФП b (после чкв), ФП a (в анамнезе), ФП при окс (до чкв), ФП постоянная форма, ФЖ, Пробежки ЖТ, Рецидивирующая ЖТ, MKB, Класс ОСН по Killip, ХСН стадия, ХСН фк, ГБ стадия, ГБ риск, АГ, Стенокардия (ИБ), Стенокардия форма(ИБ), Стенокардия ФК (ИБ), СД, ХБП, ЯБ, МКБ, ЖКБ, ФВ ЛЖ (b), ФВ ЛЖ, EDV, КДР ЛЖ, КСР ЛЖ, МЖП, ЗСЛЖ, ПСПЖ, СДЛА, Размер правого желудочка, Стеноз аортального клапана (степень), Недостаточность аортального клапана (степень), Стеноз митрального клапана (степень), Недостаточность митрального клапана (степень), Недостаточность трикуспидального клапана (степень), НПВ, НПВ диаметр, La1, La2, Ra1, Ra2, Bypass#, Гематокрит, Гемоглобин, Эритроциты, Лейкоциты, Тромбоциты, Нейтрофилы (абсолютное значение), Нейтрофилы (относительное значение), Лимфоциты (абсолютное значение), Лимфоциты (относительное значение), Моноциты (абсолютное значение), Моноциты (относительное значение), Эозинофилы (абсолютное значение), Эозинофилы (относительное значение), Базофилы (абсолютное значение), Базофилы (относительное значение), Сумма всех лейкоцитов, Средний объем эритроцита, Среднее содержание гемоглобина в эритроците, Ср, концентрация гемоглобина в эритроците, Распределение эритроцитов по объему (RDW-CV), Распределение эритроцитов по объему (RDW-SD), Средний объем тромбоцита (MPV), Расчетная ширина распределения тромбоцитов, Тромбокрит, ...]
Index: []

[0 rows x 474 columns]

'0 явных дубликатов'

In [21]:
#Преобразование даты в правильный формат
reanimation['Поступил'] = pd.to_datetime(reanimation['Поступил'], format='%m/%d/%y %H:%M:%S')

#Добавление года в код пациента
def add_year(code_patient, date):
    if '-' not in code_patient:  # Проверяем, есть ли '-'
        year = date.year % 100  # Получаем два последних числа года
        return f"{year}-{code_patient}"  # Формируем новый код
    return code_patient  # Возвращаем оригинальный код

#Применение функции к DataFrame
reanimation.loc[:, 'Код пациента'] = reanimation.apply(lambda row: add_year(row['Код пациента'],
                                                                            row['Поступил']), axis=1)

In [22]:
 #проверка что все пациенты из "Поступление2" вошли в датасет реанимация
display(d_v49['Код пациента'].isin(reanimation['Код пациента']).all())
d_v49[~d_v49['Код пациента'].isin(reanimation['Код пациента'])]
#этих пациентов нет в реанимации

np.False_

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,Диагноз Файл,Диагноз ИМ,Диагноз ИМ Дата,STEMI (Новый),...,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP,Код после дефиса
6091,20-13329,Игнатьюк ЛР,66.0,М,Да,Да,ИгнатьюкЛеонидРоманович13329_history_0.html,Да,2020-08-31,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13329
10064,17-15565,Пшеничый НВ,71.0,М,Да,Да,ПшеничныйНВ15565_history_0.html,Да,2015-10-15,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15565
16335,24-31461,Слаута НП,70.0,Ж,Да,Да,СлаутаНП31461_history_0.html,Да,2024-12-09,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31461
16483,24-30787,Тимашов СГ,73.0,М,Да,Да,ТимашовСГ30787_history_0.html,Да,2024-11-19,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30787
16490,24-30797,Кофтарев ВС,51.0,М,Да,Да,КофтаревВС30797_history_0.html,Да,2024-11-10,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1073.0,1073.0,30797
17032,16-18897,Кузнецов ВТ,56.0,Ж,Да,Да,КузнецовВТ18900_history_0.html,Да,2016-11-19,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18897
17324,14-8539,Иванова АА,68.0,Ж,Да,Да,ИвановаАА_history_0.html,Да,2014-06-25,Да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8539

In [23]:
#Соединяем две таблицы Реанимация и DataSet_V49
df = d_v49.merge(reanimation, how='inner', on='Код пациента')
#df.head()

In [24]:
#проверка даты
display(df['Поступил'].sort_values(ascending= False).head(1))
display(df['Поступил'].sort_values(ascending= True).head(1))
display(df['Начало операции(ИБ)(Новый)'].isna().sum())
display(df['Начало операции(ИБ)(Новый)'].sort_values().head(1))
display(df['Начало операции(ИБ)(Новый)'].sort_values(ascending= False).head(1))
display(df['Дата взятия биоматериала (Общий анализ крови)'].sort_values(ascending= False).head(1))
display(df['Дата взятия биоматериала (Общий анализ крови)'].sort_values().head(1))
display(df['Дата STEMI'].sort_values(ascending= False).head(1))
display(df['Дата STEMI'].sort_values().head(1)) #у двух пациентов стоит дата стеми 2012 год а по факту 2017

5545   2024-11-16
Name: Поступил, dtype: datetime64[ns]

6384   2015-01-08
Name: Поступил, dtype: datetime64[ns]

np.int64(17)

6384   2015-01-09 00:10:00
Name: Начало операции(ИБ)(Новый), dtype: datetime64[ns]

5545   2024-11-16 17:35:00
Name: Начало операции(ИБ)(Новый), dtype: datetime64[ns]

1142   2022-02-17 09:35:00
Name: Дата взятия биоматериала (Общий анализ крови), dtype: datetime64[ns]

76   2015-02-05 16:44:00
Name: Дата взятия биоматериала (Общий анализ крови), dtype: datetime64[ns]

357   2024-10-28
Name: Дата STEMI, dtype: datetime64[ns]

5038   2012-01-11
Name: Дата STEMI, dtype: datetime64[ns]

In [25]:
display(df.shape)
display(df['Код пациента'].nunique())

(6498, 514)

6196

In [26]:
# Удалим столбцы с пропусками более 50%
data_df_null = pd.DataFrame({
    'Имя столбца': df.columns,
    'Null': df.isna().sum()  # количество пропусков в каждом столбце
})

# Вычисляем процент пропусков
data_df_null['Null %'] = (data_df_null['Null'] / df.shape[0]) * 100

# Получаем список столбцов с >50% пропусков
columns_to_drop = data_df_null[data_df_null['Null %'] > 50]['Имя столбца'].tolist()

# Удаляем эти столбцы из исходного DataFrame
df_cleaned = df.drop(columns=columns_to_drop)

### Создание новых столбцов и фильтрация датасета

Новая информация:
У нас есть три точки
1. до госпитализации, это когда пациент приезжает в больницу и там есть параметр «ОСН по тк Killip»в основной базе (datasetv47)
2. есть параметр, который на входе в реанимацию
3. есть параметр во время реанимации - в базе реаниматологов анастезиологов (acses Реанимация.csv)

- Если в базе анастезиологи есть КШ, значит был настоящий КШ и значит он был при поступлении в больницу
- Если при поступлении в больницу «ОСН по тк Killip» был <4, значит у человека не было КШ
- КШ развился он или нет по базе реанимация (acses Реанимация.csv) синдромный по факту развития шока

- Мы должны выбрать всех тех людей у кого ОСН по тк Killip <4
- но можно выбрать тех, дополнить базу у  кого не развился, что у них было 4 на входе(ОСН по ТК Киллип)но в последней оценке Killip 4 не прописана  — расширяем тот класс который 0

 - ОСН по Killip <4 , а в базе access есть данные что получал норадреналин или адреналин, или допамин, или добутамин  --- развился КШ
  - Правильнее смотреть на Killip в реанимации

In [27]:
len(list(df_cleaned.columns))

233

In [28]:
#у скольких пациентов различаются ОСН по Killip и Killip в реанимации
df_cleaned[(df_cleaned['Класс ОСН по Killip'] != df_cleaned['Killip']) &
    (df_cleaned['Killip'].notna())][['Класс ОСН по Killip','Killip','Код пациента']]

      Класс ОСН по Killip  Killip Код пациента
0                     3.0     1.0      15-9993
39                    3.0     1.0      21-8140
41                    4.0     3.0     19-19282
56                    2.0     1.0         17-7
65                    2.0     4.0       21-612
...                   ...     ...          ...
6348                  3.0     4.0     21-15209
6366                  2.0     4.0     21-14882
6381                  3.0    13.0      22-1412
6494                  1.0     2.0        21-10
6495                  3.0     2.0         20-1

[1718 rows x 3 columns]

In [29]:
df_cleaned['Класс ОСН по Killip'].isna().sum()

np.int64(0)

In [30]:
#0.убираем повторное поступление в реанимации
# Удаляем строки, где Повторный == 1
df_cleaned = df_cleaned[df_cleaned['Повторный'] != 1]

# Удаляем столбец 'Повторный', потому что там остались одни 0-и
df_cleaned = df_cleaned.drop('Повторный', axis=1)

#1.так как Killip в реанимации ставят врачи, правильнее различия определять по нему
# Создаем маску для отличающихся строк
mask = (df_cleaned['Класс ОСН по Killip'] != df_cleaned['Killip']) & (df_cleaned['Killip'].notna())

# Проставляем значения из Killip в Класс ОСН по Killip
df_cleaned.loc[mask, 'Класс ОСН по Killip'] = df_cleaned.loc[mask, 'Killip']

In [31]:
display(df_cleaned[(df_cleaned['Killip'].isna()) & (df_cleaned['Класс ОСН по Killip']== 4)][['Класс ОСН по Killip','Killip', 'Код пациента']])
#тут никого не осталось

#остальные пропуски заполняем как Класс ОСН по Killip

mask = ((df_cleaned['Killip'].isna()) & (df_cleaned['Класс ОСН по Killip'] != 4))

# Проставляем значения из Класс ОСН по Killip в Killip
df_cleaned.loc[mask, 'Killip'] = df_cleaned.loc[mask, 'Класс ОСН по Killip']

      Класс ОСН по Killip  Killip Код пациента
17                    4.0     NaN      15-9176
81                    4.0     NaN      15-4351
83                    4.0     NaN      15-3951
90                    4.0     NaN      15-2500
92                    4.0     NaN      15-2489
119                   4.0     NaN      24-9116
283                   4.0     NaN      24-5244
521                   4.0     NaN     24-25415
678                   4.0     NaN      24-1744
793                   4.0     NaN     24-12358
983                   4.0     NaN     23-24944
1067                  4.0     NaN     23-22336
1185                  4.0     NaN      22-1421
1249                  4.0     NaN      21-8560
1281                  4.0     NaN        21-79
1454                  4.0     NaN      21-3425
1594                  4.0     NaN     21-22270
1602                  4.0     NaN     21-22072
1871                  4.0     NaN     21-13770
2076                  4.0     NaN      20-8772
2351                  4.0     NaN      20-3211
2495                  4.0     NaN     20-18543
2524                  4.0     NaN     20-18038
2626                  4.0     NaN     20-15707
2723                  4.0     NaN     20-13999
2829                  4.0     NaN     20-11970
2878                  4.0     NaN     20-11042
2952                  4.0     NaN      15-1989
2972                  4.0     NaN     15-19122
3108                  4.0     NaN      19-7390
3370                  4.0     NaN      19-2723
3487                  4.0     NaN     19-20875
3559                  4.0     NaN      15-9014
3584                  4.0     NaN     15-17856
3626                  4.0     NaN     19-17884
3699                  4.0     NaN      17-1440
4181                  4.0     NaN     18-17707
4593                  4.0     NaN     18-15530
4705                  4.0     NaN     18-13366
4877                  4.0     NaN      15-1721
4879                  4.0     NaN     15-17098
5134                  4.0     NaN     17-20824
5233                  4.0     NaN      15-8498
5738                  4.0     NaN     15-16497
5968                  4.0     NaN      16-2434
6343                  4.0     NaN     15-15575
6368                  4.0     NaN     15-14680
6384                  4.0     NaN       15-140
6438                  4.0     NaN     15-12317
6442                  4.0     NaN     15-12194
6474                  4.0     NaN     15-10783

In [32]:
df_cleaned['GRACE'].isna().sum()

np.int64(1716)

In [33]:
df_cleaned['ЧСС (b)'] = pd.to_numeric(df_cleaned['ЧСС (b)'].astype(str).str.replace(',', '.'), errors='coerce')
df_cleaned['ЧСС (b)'].astype(float)

df_cleaned['Креатинин'] = pd.to_numeric(df_cleaned['Креатинин'].astype(str).str.replace(',', '.'), errors='coerce')
df_cleaned['Креатинин'].astype(float)

0       202.19
1       122.81
2       137.00
3        85.91
4       102.29
         ...
6493    145.00
6494     74.00
6495    104.38
6496    116.32
6497     97.19
Name: Креатинин, Length: 6207, dtype: float64

In [34]:
#так как есть пропуски то создадим признак расчитанный GRACE
## Расчет GRACE
df_cleaned['GRACE(Рассчет)']=28
df_cleaned.loc[(df_cleaned['Age'] < 30) , ('GRACE(Рассчет)')]+=0
df_cleaned.loc[(df_cleaned['Age'] >= 30) & (df_cleaned['Age'] <= 39), ('GRACE(Рассчет)')]+=8
df_cleaned.loc[(df_cleaned['Age'] >= 40) & (df_cleaned['Age'] <= 49), ('GRACE(Рассчет)')]+=25
df_cleaned.loc[(df_cleaned['Age'] >= 50) & (df_cleaned['Age'] <= 59), ('GRACE(Рассчет)')]+=41
df_cleaned.loc[(df_cleaned['Age'] >= 60) & (df_cleaned['Age'] <= 69), ('GRACE(Рассчет)')]+=58
df_cleaned.loc[(df_cleaned['Age'] >= 70) & (df_cleaned['Age'] <= 79), ('GRACE(Рассчет)')]+=75
df_cleaned.loc[(df_cleaned['Age'] >= 80) & (df_cleaned['Age'] <= 89), ('GRACE(Рассчет)')]+=91
df_cleaned.loc[(df_cleaned['Age'] > 89) , ('GRACE(Рассчет)')]+=100

df_cleaned.loc[(df_cleaned['ЧСС (b)'] >= 51) & (df_cleaned['ЧСС (b)'] <= 69), ('GRACE(Рассчет)')]+=3
df_cleaned.loc[(df_cleaned['ЧСС (b)'] >= 70) & (df_cleaned['ЧСС (b)'] <= 89), ('GRACE(Рассчет)')]+=9
df_cleaned.loc[(df_cleaned['ЧСС (b)'] >= 90) & (df_cleaned['ЧСС (b)'] <= 109), ('GRACE(Рассчет)')]+=15
df_cleaned.loc[(df_cleaned['ЧСС (b)'] >= 110) & (df_cleaned['ЧСС (b)'] <= 149), ('GRACE(Рассчет)')]+=24
df_cleaned.loc[(df_cleaned['ЧСС (b)'] >= 150) & (df_cleaned['ЧСС (b)'] <= 199), ('GRACE(Рассчет)')]+=38
df_cleaned.loc[(df_cleaned['ЧСС (b)'] >= 200) , ('GRACE(Рассчет)')]+=46

df_cleaned.loc[(df_cleaned['Систолическое АД(b)'] < 80), ('GRACE(Рассчет)')]+=58
df_cleaned.loc[(df_cleaned['Систолическое АД(b)'] >= 81) & (df_cleaned['Систолическое АД(b)'] <= 99), ('GRACE(Рассчет)')]+=53
df_cleaned.loc[(df_cleaned['Систолическое АД(b)'] >= 100) & (df_cleaned['Систолическое АД(b)'] <= 119), ('GRACE(Рассчет)')]+=43
df_cleaned.loc[(df_cleaned['Систолическое АД(b)'] >= 120) & (df_cleaned['Систолическое АД(b)'] <= 139), ('GRACE(Рассчет)')]+=34
df_cleaned.loc[(df_cleaned['Систолическое АД(b)'] >= 140) & (df_cleaned['Систолическое АД(b)'] <= 159), ('GRACE(Рассчет)')]+=24
df_cleaned.loc[(df_cleaned['Систолическое АД(b)'] >= 160) & (df_cleaned['Систолическое АД(b)'] <= 199), ('GRACE(Рассчет)')]+=10
df_cleaned.loc[(df_cleaned['Систолическое АД(b)'] > 200), ('GRACE(Рассчет)')]+=0

df_cleaned.loc[(df_cleaned['Креатинин'] >= 0) & (df_cleaned['Креатинин'] <= 35), ('GRACE(Рассчет)')]+=1
df_cleaned.loc[(df_cleaned['Креатинин'] > 35) & (df_cleaned['Креатинин'] <= 70), ('GRACE(Рассчет)')]+=4
df_cleaned.loc[(df_cleaned['Креатинин'] > 70) & (df_cleaned['Креатинин'] <= 105), ('GRACE(Рассчет)')]+=7
df_cleaned.loc[(df_cleaned['Креатинин'] > 105) & (df_cleaned['Креатинин'] <= 140), ('GRACE(Рассчет)')]+=10
df_cleaned.loc[(df_cleaned['Креатинин'] > 140) & (df_cleaned['Креатинин'] <= 176), ('GRACE(Рассчет)')]+=13
df_cleaned.loc[(df_cleaned['Креатинин'] > 176) & (df_cleaned['Креатинин'] <= 353), ('GRACE(Рассчет)')]+=21
df_cleaned.loc[(df_cleaned['Креатинин'] > 353) , ('GRACE(Рассчет)')]+=28

#Killip это из реанимации
df_cleaned.loc[(df_cleaned['Killip'] == 2), ('GRACE(Рассчет)')]+=20
df_cleaned.loc[(df_cleaned['Killip'] == 3), ('GRACE(Рассчет)')]+=39
df_cleaned.loc[(df_cleaned['Killip'] == 4), ('GRACE(Рассчет)')]+=59

df_cleaned.loc[(df_cleaned['Age'].isna()==True) | (df_cleaned['ЧСС (b)'].isna()==True) | (df_cleaned['Систолическое АД(b)'].isna()==True) |
         (df_cleaned['Креатинин'].isna()==True) | (df_cleaned['Класс ОСН по Killip'].isna()==True) ,('GRACE(Рассчет)')]=None

df_cleaned['GRACE(Рассчет)'].isna().sum()

np.int64(159)

In [35]:
df_cleaned['GRACE(Общее)'].isna().sum()

np.int64(2711)

In [36]:
#обогатим наш расчитанный признак другими GRACE
df_cleaned['GRACE(Рассчет)'] = df_cleaned.apply(
    lambda row: row['GRACE(Рассчет)']
                if pd.notna(row['GRACE(Рассчет)']) and row['GRACE(Рассчет)'] != ''
                else row.get('GRACE(Общее)', row.get('GRACE', None)),
    axis=1
)

- Мы должны выбрать всех тех людей у кого ОСН по тк Killip <4
- но можно выбрать тех, дополнить базу у  кого не развился, что у них было 4 на входе(ОСН по ТК Киллип)но в последней оценке Killip 4 не прописана  — расширяем тот класс который 0

In [37]:
df_need = df_cleaned[
    (df_cleaned['Класс ОСН по Killip'] < 4) |
    ((df_cleaned['Класс ОСН по Killip'] == 4) &
     ((df_cleaned['Killip'] != 4) | df_cleaned['Killip'].isna()))
]

In [38]:
# КШ развился он или нет по базе реанимация (acses Реанимация.csv) синдромный по факту развития шока
# или условие ОСН по Killip <4 , а в базе access есть данные что получал норадреналин или адреналин, или допамин, или добутамин  --- развился КШ

'''Только в 'КШ развился в реанимации по синдромному диагнозу'
Дополним пациентов у которых развился в реанимации {'15-14680', '15-17098', '17-20824', '15-3951', '15-14239', '15-19122',  '18-15607', '15-7477', '19-3238', '17-16378', '15-18304', '15-15051', '15-12317', '15-4859', '16-19325',  '15-13875', '15-15575', '15-140', '18-15682',   '16-46', '17-3537', '18-10775', '16-420',  '15-9176', '21-13770', '16-18474','16-1294', '18-13366', '22-24', '15-2655', '17-114', '18-15530', '20-8772'} +33 -- это все проверенные ЕА'''

list_KSH_cindrom_diagnos = ['15-14680', '15-17098', '17-20824', '15-3951', '15-14239', '15-19122',  '18-15607', '15-7477', '19-3238', '17-16378', '15-18304', '15-15051', '15-12317', '15-4859', '16-19325',  '15-13875', '15-15575', '15-140', '18-15682',   '16-46', '17-3537', '18-10775', '16-420',  '15-9176', '21-13770', '16-18474','16-1294', '18-13366', '22-24', '15-2655', '17-114', '18-15530', '20-8772']

df_need ['КШ развился в реанимации'] = df_need.apply(
    lambda row: 1 if (row['Класс ОСН по Killip'] < 4) and (row['адреналин'] ==1 or row['добутамин'] ==1 or row['допмин'] ==1 or row['норадреналин'] ==1 ) else 0,
    axis=1
)

df_need.loc[df_need['Код пациента'].isin(list_KSH_cindrom_diagnos), 'КШ развился в реанимации'] = 1


'''у каких-то пациентов ЕА (которые по условию или условие ОСН по Killip <4 , а в базе access есть данные что получал норадреналин или адреналин, или допамин, или добутамин  --- развился КШ) не развился КШ'''
list_not_KSH =['21-8140','21-7215','24-7542','24-24589', '19-20526','19-10429', '19-11100', '19-11287',
               '19-14062', '19-15331', '19-17132', '19-17591', '20-96', '20-9356', '20-9228', '20-8038',
               '20-7910', '20-7382', '20-6859', '20-6750', '20-6272', '20-6230', '20-5829', '20-5826',
               '20-5821', '20-5511', '20-5340', '20-4946', '20-4055', '20-3780', '20-368',
               '20-3326', '20-20146', '20-19911', '20-19499', '20-19496', '20-19388', '20-1897',
               '20-18151', '20-18110', '20-1803', '20-18003', '20-17867', '20-17801', '20-17747',
               '20-17665', '20-17521', '20-17501', '20-16765', '20-16760', '20-16752', '20-16143', '20-16140',
               '20-15897', '20-15828', '20-15296', '20-15098', '20-14872', '20-14870',
               '20-14745', '20-14506', '20-14384', '20-14380', '20-14312', '20-14164', '20-14074',
               '20-1383', '20-13694', '20-13667', '20-13651', '20-13514', '20-13326', '21-14400',
               '21-13465', '21-173', '21-17094', '23-23881', '23-22787', '23-21597', '22-910',
               '22-77', '22-2679', '22-1414', '22-1171', '21-3774', '21-24611', '21-24393',
               '21-24371', '21-243', '21-23269', '21-23123', '21-22270', '21-22216', '21-20281',
               '21-18869']
df_need.loc[df_need['Код пациента'].isin(list_not_KSH), 'КШ развился в реанимации'] = 0
list_KSH =['24-6359','23-21656']
df_need.loc[df_need['Код пациента'].isin(list_KSH), 'КШ развился в реанимации'] = 1

/tmp/ipykernel_91920/1321704203.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_need ['КШ развился в реанимации'] = df_need.apply(

In [39]:
#выведем для проверки КШ развился и не развился
len(list(df_need[df_need['КШ развился в реанимации']==1]['Код пациента'].unique()))

200

In [40]:
sorted(list(df_need[df_need['КШ развился в реанимации']==1]['Код пациента'].unique()))

['15-12317',
 '15-13875',
 '15-140',
 '15-14239',
 '15-14680',
 '15-15051',
 '15-15575',
 '15-17098',
 '15-18304',
 '15-19122',
 '15-2655',
 '15-3951',
 '15-9176',
 '16-1294',
 '16-18474',
 '16-19325',
 '16-420',
 '16-46',
 '17-114',
 '17-16378',
 '17-20824',
 '17-3537',
 '18-10775',
 '18-13366',
 '18-15530',
 '18-15607',
 '18-15682',
 '19-10228',
 '19-10241',
 '19-10631',
 '19-10977',
 '19-10982',
 '19-1106',
 '19-12156',
 '19-12503',
 '19-12512',
 '19-12839',
 '19-13365',
 '19-14048',
 '19-15792',
 '19-16242',
 '19-17250',
 '19-17512',
 '19-17587',
 '19-1770',
 '19-18019',
 '19-18034',
 '19-18322',
 '19-18740',
 '19-18893',
 '19-19282',
 '19-19308',
 '19-1935',
 '19-19786',
 '19-19964',
 '19-20680',
 '19-21122',
 '19-22403',
 '19-2276',
 '19-2595',
 '19-2950',
 '19-3135',
 '19-3139',
 '19-3238',
 '19-4040',
 '19-5317',
 '19-5725',
 '19-5866',
 '19-5973',
 '19-6255',
 '19-7134',
 '19-7391',
 '19-8229',
 '19-9031',
 '19-9825',
 '20-10280',
 '20-10359',
 '20-10509',
 '20-10587',
 '20-10713',
 '20-10805',
 '20-10894',
 '20-10929',
 '20-11098',
 '20-11123',
 '20-1173',
 '20-11936',
 '20-12003',
 '20-13566',
 '20-14141',
 '20-15164',
 '20-15184',
 '20-15610',
 '20-16008',
 '20-16158',
 '20-17825',
 '20-18524',
 '20-19159',
 '20-19778',
 '20-19859',
 '20-2734',
 '20-4057',
 '20-4945',
 '20-5983',
 '20-6278',
 '20-6671',
 '20-6703',
 '20-6781',
 '20-7809',
 '20-875',
 '20-8772',
 '20-9784',
 '21-10603',
 '21-11011',
 '21-11119',
 '21-11555',
 '21-11805',
 '21-12172',
 '21-13241',
 '21-1362',
 '21-13746',
 '21-13770',
 '21-14106',
 '21-1461',
 '21-1487',
 '21-15328',
 '21-15733',
 '21-15844',
 '21-16129',
 '21-17004',
 '21-1720',
 '21-17252',
 '21-17385',
 '21-17445',
 '21-17730',
 '21-17747',
 '21-18250',
 '21-18365',
 '21-18729',
 '21-18741',
 '21-19406',
 '21-19494',
 '21-19613',
 '21-20288',
 '21-20450',
 '21-20539',
 '21-2235',
 '21-2299',
 '21-23804',
 '21-24392',
 '21-249',
 '21-24915',
 '21-25064',
 '21-25151',
 '21-2684',
 '21-315',
 '21-5038',
 '21-6494',
 '21-7488',
 '21-781',
 '21-8145',
 '21-8700',
 '22-17056',
 '22-184',
 '22-24',
 '22-2472',
 '22-313',
 '22-8474',
 '23-21656',
 '23-23333',
 '23-24079',
 '23-25586',
 '23-25962',
 '24-11380',
 '24-12120',
 '24-13504',
 '24-14376',
 '24-22523',
 '24-2280',
 '24-22811',
 '24-23745',
 '24-23821',
 '24-24011',
 '24-24020',
 '24-27217',
 '24-27514',
 '24-27551',
 '24-27774',
 '24-28112',
 '24-29385',
 '24-29431',
 '24-4116',
 '24-5026',
 '24-5462',
 '24-5744',
 '24-5871',
 '24-6359',
 '24-7324',
 '24-9003',
 '24-9317']

все 200 пациента проверены и согласованы с ЕА

--19-19804  --19-20788 --19-4183  --19-5215  --19-7372  --19-8078 --22-1412  --19-14681  --19-17116
--19-17120 --19-17124   --20-8241   --21-22680 есть в списке у ЕА но у нас нет видимо из-за фильтров

In [41]:
#Список столбцов для удаления и здесь же удалим столбцы
columns_to_drop = [
    #'Unnamed: 0',
    'Диагноз Файл',
    'Диагноз ИМ',
    'Диагноз ИМ Дата',
    'Name',
    #'Файл(Выгрузка Philips)',
    'Наличие в БД',
    'Наличие в файле',
    'STEMI',
    'STEMI (Новый)',
    'ЧКВ',
    'Дата STEMI',
    'noSTEMI',
    #'Unnamed: 11',
    #'Кардиогенный шок (1-да, 0-нет)',
    'Дата направления (Общий анализ крови)',
    'Дата взятия биоматериала (Общий анализ крови)',
    'Дата выполнения (Общий анализ крови)',
    'Дата направления (Общий анализ крови-экспрес)',
    'Дата взятия биоматериала (Общий анализ крови-экспрес)',
    'Дата выполнения (Общий анализ крови-экспрес)',
    'Начало операции(ИБ)(Новый)',
    'Конец операции(ИБ)(Новый)',
    'дата поступления',
    'дата выписки',
    #'дата смерти',
    #'Поступление в реанимацию',
    #'Выписка из реанимации',
    'Отделение',
    'Файл(Анализы)',
    'Файл(ИБ)',
    #'Набор данных (Данные Кокарев)',
    #'Unnamed: 346',
    'Код после дефиса',
    '№',
    'Поступил',
    'Перевод',
    #'Синдромный диагноз_x',
    #'Синдромный диагноз_y',#так как мы создали новый столбец Развился вероятно этот нам не нужен
    #'КШ развился в реанимации по синдромному диагнозу',
    #'Killip',
    #'killip',
    #'Класс ОСН по Killip',
    #'calendarDay',
    'Срочность',
    'Тип первой операции БД',# тут всего одно значение ЧКА(чка)
    'Ход операции',#одно значение Да
    'Протокол коронарографии',#одно значение Да
    'Запись требует проверки',
    'В базе данных',
    'Кардиогенный шок',
    'GRACE(Общее)',
    'GRACE'
]

#удаление столбцов
df_need = df_need.copy()
df_need.drop(axis='columns', columns=columns_to_drop, inplace=True)

In [42]:
''' были найдены пациенты у которых значения такие как 'норадреналин' и 'Норадреналин' и др отличаются, исправим это'''
#норадреналин и Норадреналин
list_nor =[
    '21-5038',#есть нор
    '19-20511',#есть
    '21-612',#есть
    '20-2732',#есть
    '21-24371',#есть
    '21-8140',#есть
    '19-17120',#есть
    '21-24915',#есть
    '19-21695',#есть
    '19-19804',#есть
    '20-18110',#есть
    '20-8241',#есть
    '21-14400',#есть
    '21-10603',#есть
    '21-22680',#есть
    '20-13326',#есть
    '21-17094',#есть
    '19-17133',#есть
    '19-8078',#есть
    '20-18003',#есть
    '22-1970',#есть
    '19-14681',#есть
    '19-15792',#есть
    '20-17801',#есть
    '21-18869',#есть
    '19-20788',#есть
    '20-3808',#есть
    '21-7215' #есть

]
not_nor ='20-5340',#нет но допамин

list_dob =[
    '19-20511',#есть
    '21-612', #есть
    '20-6914',#есть
    '20-14312'#есть

]

list_lev =[
    '20-2732',#есть
    '21-24371',#есть
    '19-15792'#есть
]
mes ='20-1300'#есть

#адреналин и допмин не ясно
#исправим по этим пациентам
df_need.loc[df_need['Код пациента'].isin(list_nor), 'Норадреналин'] = 'Да'
df_need.loc[df_need['Код пациента'].isin([not_nor]), 'Норадреналин'] = 'Нет'
df_need.loc[df_need['Код пациента'].isin(list_dob), 'Добутамин'] = 'Да'
df_need.loc[df_need['Код пациента'].isin(list_lev), 'Левосимендан'] = 'Да'
df_need.loc[df_need['Код пациента'].isin([mes]), 'Мезатон'] = 'Да'

print(df_need['Код пациента'].nunique())

columns_to_drop = [ 'Умер','норадреналин','допмин','адреналин', 'добутамин', 'левосимендан', 'мезатон']
df_need = df_need.drop(columns=columns_to_drop, errors='ignore') #в столбцах пропусков нет, по целевой переменной (Развился=1) количество совпадает
#Исход заболевания = умер при спорных моментак когда смерть=1 а умер 0, поэтому оставляем столбец 'Смерть'

5869

In [43]:
df_need['ХСН фк'].value_counts()

ХСН фк
2        3265
0         815
1         466
IIFK      433
3         294
IIIFK      30
IFK        25
4          19
IVFK        3
Name: count, dtype: int64

In [44]:
# Определяем множества значений для каждой группы
group_10 = {'0', '1', 'IFK'}
group_234 = {'2', '3', '4', 'IIFK', 'IIIFK', 'IVFK'}

# Создаем признаки
df_need['ХСН_фк_01'] = df_need['ХСН фк'].astype(str).str.strip().isin(group_10).astype(int)
df_need['ХСН_фк_234'] = df_need['ХСН фк'].astype(str).str.strip().isin(group_234).astype(int)

In [45]:
df_need['ХСН_фк_01'].value_counts()

ХСН_фк_01
0    4576
1    1306
Name: count, dtype: int64

In [46]:
for col in df_need.columns:
    print(df_need[col].value_counts())

Код пациента
15-17342    2
20-12104    2
15-8238     2
21-22927    2
16-18167    2
           ..
20-8029     1
20-8038     1
20-81       1
20-8100     1
20-7835     1
Name: count, Length: 5869, dtype: int64
Age
64.0    227
65.0    220
66.0    213
63.0    211
60.0    209
62.0    205
58.0    204
67.0    203
68.0    201
69.0    191
57.0    191
61.0    187
59.0    179
70.0    174
55.0    174
71.0    159
72.0    157
56.0    153
54.0    139
53.0    138
73.0    120
50.0    113
51.0    112
49.0    105
52.0    102
74.0    102
75.0    101
77.0     97
48.0     96
76.0     90
79.0     83
46.0     81
78.0     79
47.0     76
45.0     71
44.0     68
43.0     66
81.0     62
80.0     54
82.0     52
83.0     49
42.0     46
41.0     40
84.0     36
40.0     31
85.0     28
37.0     21
87.0     20
38.0     18
39.0     17
36.0     14
86.0     13
35.0     13
88.0     12
34.0     10
89.0      8
33.0      7
90.0      6
30.0      5
91.0      4
32.0      4
27.0      4
93.0      3
31.0      2
92.0      2
97.0      1
26.0      1
29.0      1
Name: count, dtype: int64
Sex
М    4020
Ж    1859
Name: count, dtype: int64
Диагноз Нестабильная стенакордия
Нет    5510
Да      369
Name: count, dtype: int64
Вид STEMI
Задний      2715
Передний    2396
Name: count, dtype: int64
Инфаркт-зависимая артерия
ПМЖВ                  1850
ПКА                   1796
ПМЖВ - Несовадает      469
ПКА - Несовадает       461
ОВ                     423
2                      219
ОВ - Несовадает        103
ДВ                      72
ЗБВ                     58
ВТК                     53
ЗМЖВ                    27
0                       27
ДВ - Несовадает         25
Ствол                   24
ВТК - Несовадает        22
ЗБВ - Несовадает        13
АИ                      13
3                       12
ЗМЖВ - Несовадает        8
Ствол - Несовадает       5
Name: count, dtype: int64
Поражение ствола
Нет    5689
Да      193
Name: count, dtype: int64
Количество пораженных сосудов(Syntax)
1.0    2153
2.0    2123
3.0    1447
0.0     154
4.0       5
Name: count, dtype: int64
Количество пораженных сосудов(Значимость)
1.0    2700
2.0    2031
3.0     987
0.0     164
Name: count, dtype: int64
TIMI
3.0    3908
1.0     299
0.0      99
2.0      92
Name: count, dtype: int64
Инфаркт миокарда в анамнезе (<3)
Нет    5708
Да      174
Name: count, dtype: int64
Инфаркт миокарда в анамнезе (>3)
Нет    5305
Да      577
Name: count, dtype: int64
Инфаркт миокарда со стентированием в анамнезе
Нет    4731
Да      156
Name: count, dtype: int64
ОНМК (иш) в анамнезе
Нет    3230
Да       28
Name: count, dtype: int64
Тромболизис_x
Нет    3167
Да     1714
Name: count, dtype: int64
ФП b (после чкв)
Нет    4883
Да      983
Name: count, dtype: int64
ФП a (в анамнезе)
Нет    5429
Да      440
Name: count, dtype: int64
MKB
I21.1    1568
I21.0    1428
I21.9     926
I22.0     150
I22.1     139
         ...
L08.9       1
K56.0       1
N31.2       1
J13.0       1
I67.9       1
Name: count, Length: 181, dtype: int64
Класс ОСН по Killip
1.0    4405
2.0     919
3.0     425
0.0      82
4.0      51
Name: count, dtype: int64
ХСН фк
2        3265
0         815
1         466
IIFK      433
3         294
IIIFK      30
IFK        25
4          19
IVFK        3
Name: count, dtype: int64
ГБ стадия
3.0    2375
0.0     343
4.0     304
2.0     196
1.0      70
5.0       2
Name: count, dtype: int64
ГБ риск
4.0    2398
0.0     334
3.0     122
1.0      51
2.0      50
8.0       1
Name: count, dtype: int64
Стенокардия (ИБ)
Нет    4293
Да      811
Name: count, dtype: int64
СД
Нет    4739
Да     1143
Name: count, dtype: int64
ХБП
Нет    4941
Да      940
Name: count, dtype: int64
МКБ
Нет    4226
Да       53
Name: count, dtype: int64
ФВ ЛЖ
60.0    563
50.0    394
55.0    352
56.0    286
62.0    266
65.0    259
52.0    252
58.0    226
45.0    217
57.0    206
48.0    196
59.0    178
49.0    161
63.0    158
61.0    157
64.0    156
53.0    155
47.0    138
54.0    131
40.0    127
46.0    106
51.0    100
66.0     85
70.0     79
42.0     75
68.0     74
43.0     68
38.0     63
67.0     59
35.0     44
44.0     43
30.0     27
69.0     24
75.0     21
41.0     20
37.0     18
32.0     15
36.0     15
73.0     14
33.0     14
25.0     13
72.0     13
39.0     11
34.0     10
28.0     10
74.0     10
29.0      5
27.0      4
26.0      3
31.0      3
80.0      3
71.0      3
24.0      2
15.0      1
16.0      1
18.0      1
85.0      1
76.0      1
77.0      1
23.0      1
20.0      1
22.0      1
Name: count, dtype: int64
КДР ЛЖ
5       482
4.9     453
4.7     437
5.2     425
4.8     420
5.3     394
5.1     332
4.5     328
5.4     322
4.6     290
5.5     257
5.6     203
4.3     171
5.7     171
4.4     170
4.2     128
4.1      98
4        92
5.8      66
6        62
6.1      48
5.9      45
3.9      34
6.2      26
6.3      26
6.5      23
3.8      22
6.4      15
3.6      13
6.6      13
3.7       8
3.5       7
6.8       6
7.6       2
6.7       2
7.2       2
7.5       2
7.1       1
6.9       1
3.1       1
4.55      1
7.3       1
7         1
3         1
8         1
Name: count, dtype: int64
КСР ЛЖ
3.2      484
3.3      445
3.6      444
3.5      436
3        420
3.7      371
3.1      354
3.4      348
3.8      304
3.9      296
2.9      231
4        221
2.8      211
2.7      144
4.1      128
4.2      113
2.6       93
4.3       69
2.5       63
4.4       56
4.5       55
2.4       42
2.3       34
4.6       30
4.8       29
4.7       25
5         25
4.9       23
2.1       13
5.3       12
2         10
5.4        9
5.1        9
2.2        9
5.2        9
5.7        4
5.6        4
1.9        3
5.5        3
6.2        3
6.4        2
5.8        2
3.01       1
2.97       1
6.6        1
36         1
3.21       1
3.58       1
4.01       1
4.165      1
6.1        1
1.7        1
5.9        1
Name: count, dtype: int64
МЖП
1.00    1442
1.10    1247
1.20     677
0.90     662
1.30     509
1.40     300
0.80     298
1.50     146
0.70     106
1.60      53
1.70      27
0.60      27
1.80      14
1.15       8
2.00       6
1.24       6
1.25       5
1.90       5
1.23       4
1.12       4
0.95       4
1.18       4
0.50       4
1.27       4
1.13       3
1.38       3
0.98       3
0.86       2
2.10       2
1.36       2
1.16       2
1.35       2
0.84       2
1.17       2
0.92       2
1.22       2
2.20       2
0.40       2
1.28       2
0.89       2
1.43       1
1.64       1
0.83       1
0.82       1
0.85       1
0.91       1
1.26       1
0.97       1
0.87       1
0.96       1
1.14       1
1.41       1
1.55       1
Name: count, dtype: int64
ЗСЛЖ
1.00    1708
1.10    1182
0.90     898
1.20     690
0.80     378
1.30     356
1.40     150
0.70      96
1.50      52
0.60      15
1.60      12
0.50       8
1.70       6
1.12       6
1.15       4
1.25       4
0.40       3
0.86       3
1.18       3
0.95       3
1.24       3
0.98       3
0.83       2
1.35       2
1.13       2
1.22       2
0.89       2
1.23       2
1.90       2
0.84       1
1.80       1
1.21       1
0.81       1
1.36       1
0.94       1
1.26       1
1.27       1
1.33       1
1.17       1
0.96       1
1.14       1
Name: count, dtype: int64
ПСПЖ
0.30    3353
0.40    1092
0.35     881
0.45      73
0.50      67
0.33      41
0.32      15
0.60      11
0.37       2
0.34       2
0.55       1
0.52       1
0.42       1
0.80       1
0.70       1
0.36       1
0.20       1
Name: count, dtype: int64
СДЛА
25.0     1324
30.0     1019
28.0      595
24.0      300
26.0      255
22.0      215
23.0      190
32.0      158
35.0      155
20.0      141
27.0      141
40.0      116
38.0       94
29.0       90
45.0       81
33.0       65
37.0       64
50.0       50
43.0       49
21.0       40
31.0       39
42.0       33
34.0       32
55.0       29
41.0       28
39.0       26
48.0       23
47.0       20
36.0       18
53.0       17
60.0       16
65.0       15
46.0       15
52.0       13
62.0       10
18.0       10
51.0       10
19.0       10
44.0        8
49.0        8
58.0        8
68.0        7
70.0        6
67.0        5
57.0        5
17.0        5
63.0        4
75.0        4
56.0        4
54.0        4
74.0        3
61.0        3
59.0        3
76.0        3
64.0        2
16.0        2
66.0        2
86.0        1
15.0        1
78.0        1
3.0         1
82.0        1
80.0        1
85.0        1
117.0       1
95.0        1
102.0       1
4.0         1
73.0        1
83.0        1
Name: count, dtype: int64
Размер правого желудочка
2.0    2111
2.5    1217
2.4     623
1.8     282
2.6     248
2.1     248
2.2     217
2.3     197
1.9     121
1.6      50
2.8      47
2.7      32
3.0      17
1.7      15
1.3      12
1.5       8
2.9       5
4.0       5
3.2       4
5.0       3
3.4       2
3.3       1
3.6       1
3.5       1
1.2       1
4.2       1
4.4       1
Name: count, dtype: int64
Стеноз аортального клапана (степень)
0    3246
1       4
Name: count, dtype: int64
НПВ диаметр
1.50    2714
1.80     424
2.00     313
1.60     310
1.30     136
1.70      97
1.90      89
1.40      59
2.10      22
2.20      15
2.30      10
2.40       9
2.50       9
1.20       7
2.70       5
2.80       4
2.60       3
1.00       2
2.90       2
3.10       2
2.35       1
1.55       1
3.20       1
2.15       1
1.10       1
Name: count, dtype: int64
La1
3.80    529
3.60    482
3.90    481
3.70    468
4.00    467
3.50    412
4.10    375
4.20    358
3.40    263
4.30    255
4.50    214
3.30    189
3.20    188
4.40    179
4.60    143
4.70     96
4.80     84
3.10     80
3.00     64
4.90     49
5.00     47
2.90     33
5.20     28
5.10     17
5.30      9
5.50      9
5.40      8
2.80      7
2.70      5
5.60      4
2.60      4
6.20      3
5.70      3
6.10      2
3.56      1
2.50      1
5.80      1
6.60      1
5.90      1
1.20      1
1.90      1
Name: count, dtype: int64
La2
5.0    521
4.8    438
4.5    435
5.2    425
4.9    412
4.6    408
4.7    388
5.1    378
5.3    203
5.5    182
4.4    167
5.4    165
4.3    165
4.2    153
5.7    141
5.6    130
4.1    114
4.0    109
5.8     96
5.9     87
6.0     86
6.1     50
6.3     38
6.2     37
3.9     37
6.5     27
3.8     24
6.4     22
6.7     20
6.6     16
6.8     13
7.0     10
3.7      9
6.9      8
3.6      8
3.5      7
7.2      7
7.5      5
7.3      4
7.1      4
7.6      2
2.0      1
3.4      1
7.4      1
8.5      1
3.0      1
8.2      1
8.3      1
2.9      1
3.3      1
7.7      1
7.8      1
Name: count, dtype: int64
Ra1
3.5    621
3.6    542
3.7    514
3.8    483
3.4    465
3.2    390
3.9    387
4.0    358
3.3    322
3.0    277
3.1    239
4.1    230
4.2    164
4.3    126
4.5     89
2.9     66
4.4     61
4.6     46
2.8     45
4.8     28
4.7     26
4.9     24
2.7     15
5.0     11
2.6     10
5.1      9
5.3      7
5.2      4
5.4      3
5.8      2
5.5      2
2.5      2
2.4      2
5.6      1
5.7      1
2.2      1
6.2      1
6.4      1
6.1      1
6.9      1
Name: count, dtype: int64
Ra2
4.5    682
4.7    492
4.6    470
4.9    425
4.8    418
5.0    402
5.2    319
5.1    298
4.2    283
4.3    270
4.0    263
4.4    241
4.1    191
3.9    103
5.3     91
5.5     79
3.8     78
5.4     58
5.7     54
5.6     41
5.8     40
3.7     37
5.9     25
6.0     25
3.6     22
6.2     21
3.5     20
6.4     19
6.3     18
6.1     16
6.8     12
6.5     12
6.6      8
6.7      6
3.3      6
3.0      5
6.9      4
7.0      4
3.2      4
8.2      2
7.5      2
3.4      2
3.1      2
7.8      1
7.4      1
8.1      1
7.2      1
9.5      1
7.7      1
7.6      1
Name: count, dtype: int64
Гематокрит
40.00    57
38.40    54
38.30    54
38.20    52
36.20    52
         ..
18.60     1
15.00     1
18.00     1
0.44      1
0.35      1
Name: count, Length: 358, dtype: int64
Гемоглобин
147.0    169
150.0    151
141.0    148
137.0    144
144.0    144
        ...
79.0       1
46.0       1
44.0       1
195.0      1
69.0       1
Name: count, Length: 134, dtype: int64
Эритроциты
4.46    60
4.25    59
4.33    57
4.40    56
4.38    54
        ..
6.21     1
2.68     1
2.81     1
3.00     1
1.73     1
Name: count, Length: 374, dtype: int64
Лейкоциты
8.40     73
9.20     71
9.80     70
11.60    70
9.70     64
         ..
11.51     1
12.31     1
9.14      1
11.05     1
6.32      1
Name: count, Length: 996, dtype: int64
Тромбоциты
191.0    52
182.0    51
215.0    49
199.0    47
193.0    47
         ..
475.0     1
29.0      1
399.0     1
493.0     1
422.0     1
Name: count, Length: 421, dtype: int64
Нейтрофилы (абсолютное значение)
5.05     18
5.59     17
3.57     16
4.83     16
6.02     15
         ..
14.75     1
13.89     1
9.80      1
17.54     1
13.44     1
Name: count, Length: 1294, dtype: int64
Нейтрофилы (относительное значение)
68.00    29
63.10    28
62.30    27
63.20    27
56.50    26
         ..
43.50     1
71.01     1
40.40     1
28.40     1
35.50     1
Name: count, Length: 568, dtype: int64
Лимфоциты (абсолютное значение)
1.90    133
1.80    118
1.40    110
1.70    110
1.50    107
       ...
8.40      1
5.33      1
3.93      1
0.41      1
4.37      1
Name: count, Length: 452, dtype: int64
Лимфоциты (относительное значение)
18.6    29
17.5    28
14.3    28
16.5    27
24.0    27
        ..
45.8     1
49.7     1
58.5     1
44.8     1
48.6     1
Name: count, Length: 470, dtype: int64
Моноциты (абсолютное значение)
0.82    75
0.93    75
0.74    74
0.75    72
0.64    72
        ..
2.71     1
3.72     1
2.64     1
2.88     1
2.30     1
Name: count, Length: 256, dtype: int64
Моноциты (относительное значение)
9.20     105
8.50     105
8.40      99
9.60      96
9.30      94
        ...
20.50      1
20.60      1
1.40       1
9.91       1
21.80      1
Name: count, Length: 197, dtype: int64
Эозинофилы (абсолютное значение)
0.01    525
0.02    334
0.03    329
0.00    287
0.04    279
       ...
0.95      1
5.40      1
0.77      1
0.96      1
0.86      1
Name: count, Length: 134, dtype: int64
Эозинофилы (относительное значение)
0.10     573
0.20     342
0.00     314
0.30     273
0.40     252
        ...
7.80       1
0.17       1
9.60       1
14.50      1
8.20       1
Name: count, Length: 113, dtype: int64
Базофилы (абсолютное значение)
0.02    1463
0.03    1153
0.01     997
0.04     734
0.05     421
0.06     198
0.00     119
0.07     108
0.08      62
0.09      41
0.10      11
0.11      11
0.14       6
0.12       6
0.13       4
0.16       3
0.18       2
0.15       2
0.17       2
0.24       2
0.39       1
0.89       1
0.20       1
0.23       1
0.50       1
1.15       1
0.40       1
0.22       1
Name: count, dtype: int64
Базофилы (относительное значение)
0.20     1188
0.10     1054
0.30     1014
0.40      749
0.50      497
0.60      304
0.00      206
0.70      178
0.80      108
0.90       46
1.00       23
1.10       16
1.20        9
1.40        9
1.30        8
1.60        2
3.20        2
1.90        2
2.20        2
1.70        2
5.60        1
1.80        1
2.00        1
9.70        1
1.50        1
11.30       1
0.12        1
Name: count, dtype: int64
Сумма всех лейкоцитов
100.0    2572
100.0     139
0.0        77
100.1      23
100.5      22
         ...
115.8       1
14.6        1
109.5       1
129.4       1
63.0        1
Name: count, Length: 561, dtype: int64
Средний объем эритроцита
86.8     59
87.8     48
88.4     48
85.6     47
89.5     46
         ..
101.5     1
65.0      1
70.4      1
60.0      1
53.7      1
Name: count, Length: 426, dtype: int64
Среднее содержание гемоглобина в эритроците
30.9    118
31.5    117
29.6    114
30.0    114
30.2    111
       ...
16.0      1
20.5      1
38.8      1
16.1      1
37.5      1
Name: count, Length: 205, dtype: int64
Ср, концентрация гемоглобина в эритроците
339.0    127
342.0    119
344.0    115
340.0    114
345.0    113
        ...
32.0       1
32.8       1
32.3       1
37.7       1
461.0      1
Name: count, Length: 199, dtype: int64
Распределение эритроцитов по объему (RDW-CV)
13.2    235
13.5    214
13.6    207
12.8    206
13.1    200
       ...
24.9      1
23.9      1
10.7      1
10.9      1
11.0      1
Name: count, Length: 122, dtype: int64
Распределение эритроцитов по объему (RDW-SD)
43.0    74
45.1    74
46.1    73
43.8    72
41.9    69
        ..
59.4     1
64.4     1
69.4     1
61.0     1
36.1     1
Name: count, Length: 296, dtype: int64
Средний объем тромбоцита (MPV)
8.70     157
8.30     140
11.00    136
8.60     135
8.80     128
8.40     127
10.20    125
10.00    121
8.50     121
9.90     121
10.80    120
10.40    118
8.20     117
9.00     116
8.00     115
8.90     114
9.80     114
9.30     113
8.10     111
11.20    110
10.70    109
9.10     109
9.70     108
7.80     107
10.60    107
10.50    105
10.90    105
7.90     105
9.60     104
10.30    104
9.40     102
7.70     101
9.20      99
9.50      99
10.10     97
11.40     94
11.10     93
11.30     93
11.50     88
11.60     78
7.40      77
7.30      76
7.60      72
7.50      69
11.70     65
11.80     57
12.00     54
11.90     53
12.10     49
7.20      44
7.10      44
12.50     37
12.30     36
7.00      36
12.70     31
12.20     31
12.60     30
6.90      27
12.40     27
12.80     22
13.10     16
12.90     14
13.30     14
13.20     13
6.80      11
13.00     11
6.70      10
13.40     10
13.60      9
13.50      8
6.50       7
6.60       7
13.90      5
6.30       4
14.00      3
14.30      2
14.20      2
13.70      2
6.40       2
14.10      2
13.80      1
9.36       1
14.70      1
6.20       1
Name: count, dtype: int64
Расчетная ширина распределения тромбоцитов
16.0    206
16.1    195
15.9    193
15.8    186
15.7    168
       ...
23.4      1
22.9      1
7.9       1
21.7      1
23.1      1
Name: count, Length: 138, dtype: int64
Тромбокрит
0.200    369
0.210    355
0.180    344
0.190    343
0.220    341
0.160    312
0.230    309
0.170    281
0.240    275
0.250    265
0.150    257
0.260    224
0.140    198
0.270    175
0.280    174
0.290    153
0.130    143
0.310    113
0.300    111
0.320    105
0.120     92
0.110     68
0.330     63
0.340     62
0.350     57
0.360     38
0.100     33
0.370     31
0.380     29
0.400     29
0.390     21
0.080     18
0.090     15
0.430     12
0.440     12
0.450     11
0.420     10
0.470      8
0.410      7
0.490      6
0.070      4
0.460      4
0.500      4
0.510      4
0.530      3
0.060      3
0.040      3
0.194      2
0.590      2
0.480      2
0.030      2
0.141      2
0.540      2
0.680      2
0.365      1
0.550      1
0.950      1
0.162      1
0.990      1
0.116      1
0.099      1
1.970      1
0.265      1
0.191      1
0.050      1
0.147      1
0.304      1
0.620      1
0.020      1
0.173      1
0.332      1
0.068      1
0.166      1
0.560      1
0.427      1
0.164      1
0.131      1
0.148      1
Name: count, dtype: int64
Коэффициент крупных тромбоцитов
33.90    37
32.80    35
32.00    35
32.90    34
28.10    32
         ..
10.10     1
14.30     1
16.40     1
15.20     1
8.15      1
Name: count, Length: 445, dtype: int64
СОЭ
2.0      229
10.0     217
15.0     191
12.0     179
14.0     171
        ...
112.0      1
113.0      1
87.0       1
105.0      1
0.0        1
Name: count, Length: 102, dtype: int64
С-реактивный белок
0.00      54
6.60      14
13.90     14
2.90      14
1.40      13
          ..
15.77      1
122.00     1
159.68     1
15.71      1
16.27      1
Name: count, Length: 2088, dtype: int64
PLR (тромбоциты/лимфоциты абс) (61-239)
0.00      233
100.00     26
150.00     13
80.00      13
120.00     12
         ...
564.84      1
97.91       1
66.24       1
89.69       1
89.67       1
Name: count, Length: 4109, dtype: int64
SII (тромбоциты*нейтрофилы абс / лимфоциты абс)
0.000       464
395.370       2
534.530       2
1861.830      2
805.000       2
           ...
2202.900      1
297.240       1
397.880       1
844.290       1
904.752       1
Name: count, Length: 4654, dtype: int64
ELR (эозинофилы абс/лимфоциты абс
0.130000    303
0.140000    297
0.150000    272
0.120000    264
0.160000    248
           ...
0.016949      1
0.037594      1
0.017647      1
0.104938      1
0.066667      1
Name: count, Length: 787, dtype: int64
ELR %
0.00    1372
0.01     889
0.02     232
0.03     144
0.04     137
0.05      95
0.06      82
0.08      75
0.07      65
0.09      52
0.11      44
0.10      37
0.12      28
0.13      26
0.16      17
0.14      13
0.18      12
0.15      11
0.19       9
0.20       9
0.22       6
0.21       5

In [47]:
df_need['Лейкоциты(a)'] = pd.to_numeric(df_need['Лейкоциты(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Лейкоциты(a)'].astype(float)


df_need['Нейтрофилы (абсолютное значение)(a)'] = pd.to_numeric(df_need['Нейтрофилы (абсолютное значение)(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Нейтрофилы (абсолютное значение)(a)'].astype(float)

df_need['Лимфоциты (абсолютное значение)(a)'] = pd.to_numeric(df_need['Лимфоциты (абсолютное значение)(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Лимфоциты (абсолютное значение)(a)'].astype(float)

df_need['Эр(a)'] = pd.to_numeric(df_need['Эр(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Эр(a)'].astype(float)

df_need['Гематокрит(a)'] = pd.to_numeric(df_need['Гематокрит(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Гематокрит(a)'].astype(float)

df_need['Глюкоза(a)'] = pd.to_numeric(df_need['Глюкоза(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Глюкоза(a)'].astype(float)


df_need['Систолическое АД(b)'] = df_need['Систолическое АД(b)'].fillna(df['САД(a)'])
df_need['Диастолического АД(b)'] = df_need['Диастолического АД(b)'].fillna(df['ДАД(a)'])

df_need['АСАТ(a)'] = pd.to_numeric(df_need['АСАТ(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['АСАТ(a)'].astype(float)

df_need['АЛАТ(a)'] = pd.to_numeric(df_need['АЛАТ(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['АЛАТ(a)'].astype(float)


df_need['Билирубин общий(a)'] = pd.to_numeric(df_need['Билирубин общий(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Билирубин общий(a)'].astype(float)

df_need['Холестерин общий(a)'] = pd.to_numeric(df_need['Холестерин общий(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Холестерин общий(a)'].astype(float)

df_need['Триглицериды(a)'] = pd.to_numeric(df_need['Триглицериды(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Триглицериды(a)'].astype(float)

df_need['Креатинин(a)'] = pd.to_numeric(df_need['Креатинин(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['Креатинин(a)'].astype(float)

df_need['ЛДГ(a)'] = pd.to_numeric(df_need['ЛДГ(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['ЛДГ(a)'].astype(float)

df_need['КФК(a)'] = pd.to_numeric(df_need['КФК(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['КФК(a)'].astype(float)


df_need['С-реактивный белок(а)'] = pd.to_numeric(df_need['С-реактивный белок(а)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['С-реактивный белок(а)'].astype(float)


df_need['ПТИ(a)'] = pd.to_numeric(df_need['ПТИ(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['ПТИ(a)'].astype(float)

df_need['МНО(a)'] = pd.to_numeric(df_need['МНО(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['МНО(a)'].astype(float)

df_need['ФБГ(a)'] = pd.to_numeric(df_need['ФБГ(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['ФБГ(a)'].astype(float)

df_need['ТВ(a)'] = pd.to_numeric(df_need['ТВ(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['ТВ(a)'].astype(float)

df_need['АПТВ(a)'] = pd.to_numeric(df_need['АПТВ(a)'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['АПТВ(a)'].astype(float)

df_need['СКФ'] = pd.to_numeric(df_need['СКФ'].astype(str).str.replace(',', '.'), errors='coerce')
df_need['СКФ'].astype(float)


df_need['Нейтрофилы (абсолютное значение)(a)'] = (
    pd.to_numeric(df_need['Нейтрофилы (абсолютное значение)(a)'].astype(str).str.replace(',', '.'), errors='coerce'))
df_need['Нейтрофилы (абсолютное значение)(a)'].astype(float)



df_need['Hb(a)'] = (
    pd.to_numeric(df_need['Hb(a)'].astype(str).str.replace(',', '.'), errors='coerce'))
df_need['Hb(a)'].astype(float)

/tmp/ipykernel_91920/116652248.py:22: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need['Диастолического АД(b)'] = df_need['Диастолического АД(b)'].fillna(df['ДАД(a)'])

0       105.0
1       139.0
2       151.0
3       185.0
4       136.0
        ...
6492    145.0
6494    112.0
6495    157.0
6496    155.0
6497    162.0
Name: Hb(a), Length: 5882, dtype: float64

In [48]:
#непрерывные признаки
continuous_features = [
    'Age',
    'ФВ ЛЖ',
    'КДР ЛЖ',
    'КСР ЛЖ',
    'МЖП',
    'ЗСЛЖ',
    'ПСПЖ',
    'СДЛА',
    'Размер правого желудочка',
    'НПВ диаметр',
    'La1',
    'La2',
    'Ra1',
    'Ra2',
    'Гематокрит',
    'Гемоглобин',
    'Эритроциты',
    'Лейкоциты',
    'Тромбоциты',
    'Нейтрофилы (абсолютное значение)',
    'Нейтрофилы (относительное значение)',
    'Лимфоциты (абсолютное значение)',
    'Лимфоциты (относительное значение)',
    'Моноциты (абсолютное значение)',
    'Моноциты (относительное значение)',
    'Эозинофилы (абсолютное значение)',
    'Эозинофилы (относительное значение)',
    'Базофилы (абсолютное значение)',
    'Базофилы (относительное значение)',
    'Сумма всех лейкоцитов',
    'Средний объем эритроцита',
    'Среднее содержание гемоглобина в эритроците',
    'Ср, концентрация гемоглобина в эритроците',
    'Распределение эритроцитов по объему (RDW-CV)',
    'Распределение эритроцитов по объему (RDW-SD)',
    'Средний объем тромбоцита (MPV)',
    'Расчетная ширина распределения тромбоцитов',
    'Тромбокрит',
    'Коэффициент крупных тромбоцитов',
    'СОЭ',
    #'С-реактивный белок',
    'PLR (тромбоциты/лимфоциты абс) (61-239)',
    'SII (тромбоциты*нейтрофилы абс / лимфоциты абс)',
    'ELR (эозинофилы абс/лимфоциты абс',
    'ELR %',
    'ENR (эозин абс/нейтрофилы абс)',
    'BLR (базофилы абс/лимфоциты абс)',
    'GLR (глюкоза мг/дл / лимф абс)',
    'FLR (fibr/L abs)',
    'RLR (RDW/ lymph abs)',
    'MPV/PC (MPV/ PLT)',
    'Глюкоза в мг/дл',
    'Фибриноген',
    'Мочевина(b)',
    'Продолжительность операции',
    'Apache II',
    'Рост',
    'Вес',
    'Индекс массы тела',
    'Систолическое АД(b)',
    'Диастолического АД(b)',
    'ЧСС (b)',
    'Лейкоциты(a)',
    'Нейтрофилы (абсолютное значение)(a)',
    'Эр(a)',
    'Hb(a)',
    'Гематокрит(a)',
    'Тромбоциты(a)',
    'Глюкоза(a)',
    'Мочевина(a)',
    'ПТИ(a)',
    'МНО(a)',
    'ФБГ(a)',
    'ТВ(a)',
    'АПТВ(a)',
    'Креатинин',
    'СКФ',
    'SpO2',
    'GRACE(Рассчет)',
    'eGFR',
    #новые
    'АСАТ(a)',
    'АЛАТ(a)',
    'Билирубин общий(a)',
    'Холестерин общий(a)',
    'Триглицериды(a)',
    'Креатинин(a)',
    'ЛДГ(a)',
    'КФК(a)'
    #'MnSistAD',
    #'MnDiasAD',
    #'MnMeanAD',
    #'MxSistAD',
    #'MxDiasAD',
    #'MxMeanAD',
    #'SisStart',
    #'DiaStart',
    #'MeanStart',
    #'SisEnd',
    #'DiaEnd',
    #'MeanEnd'
]

#исправляем тип непрерывного признака Фибриноген
df_need= df_need.copy()
df_need.loc[:, 'Фибриноген'] = pd.to_numeric(df_need['Фибриноген'], errors='coerce')

#дихотомические признаки
dichotomous_features = [
    'Диагноз Нестабильная стенакордия',
    'ХСН_фк_10',
    'ХСН_фк_234',
    'Sex', # 1-мужчина 0 -женщина
    'Вид STEMI',#задний передний
    'Поражение ствола',#да нет
    'Инфаркт миокарда в анамнезе (<3)',#да нет
    'Инфаркт миокарда в анамнезе (>3)',#да нет
    'Инфаркт миокарда со стентированием в анамнезе',#да нет  и тут есть пустые
    'ОНМК (иш) в анамнезе',
    'ФП b (после чкв)', #да нет
    'ФП a (в анамнезе)',#да нет
    'Стенокардия (ИБ)',#да нет  и тут есть пустые
    'СД',#да нет
    'ХБП',#да нет и тут есть пустые
    'МКБ',
    'Стеноз аортального клапана (степень)',
    'Смерть',#да нет
    'повторные операции',
    'Смерть в реанимации',
    'GRACE(Общее)>140',
    'интегрилин|эптифибатид|коромакс|агграстат',#Да Нет и пустые
    'Общий анализ крови раньше операции',#Да Нет и пустые
    'Общий анализ крови_экспресс раньше операции',#Да Нет и пустые
    'Аортальный стеноз (Градиент)',
    'Аортальный стеноз (Заключение)',
    'ХОБЛ (Новый столбец)',#Да Нет и пустые
    'Стенокардия в диагнозе при поступлении',#Да Нет и пустые
    'ПИКС в диагнозе при поступлении',#Да Нет
    'Инфаркт-зависимая артерия(Огригированная)2',#Передний/Задний бассейн
    'Ишемический инсульт (Выгрузка из ИБ - временный столбец)',#Да Нет
    'Геморрагический инсульт (Выгрузка из ИБ - временный столбец)',#Да Нет
    'Инсульт (Выгрузка из ИБ - временный столбец)',#Да Нет
    'Курит',#Да Нет
    'GRACE(Общее)>156',
    'Отек легких(b)',
    'Отек легких(a)',#Да Нет
    'Отек легких',#Да Нет
    'Медицинская помощь оказана за первые 4 часа',#Да Нет
    'Гипертоническая болезнь',#Да Нет
    'GRACE (Низкий риск)',#Да Нет
    'GRACE (Средний риск)',#Да Нет
    'GRACE (Высокий риск)',#Да Нет
    'TIMI (Летальность) (Низкий риск)',#Да Нет
    'TIMI (Летальность) (Средний риск)',#Да Нет
    'TIMI (Летальность) (Высокий риск)',#Да Нет
    'PAMI (Низкий риск)',#Да Нет
    'PAMI (Средний риск)',#Да Нет
    'PAMI (Высокий риск)',#Да Нет
    'CADILLAC (Низкий риск)',
    'CADILLAC (Средний риск)',
    'CADILLAC (Высокий риск)',
    'РЕКОРД (Низкий риск)',#Да Нет
    'РЕКОРД (Высокий риск)',#Да Нет
    'А-В блокаДа (Новый)',#Да Нет
    'Адреналин',#Да Нет
    'Добутамин',#Да Нет
    'Допмин',#Да Нет
    'Норадреналин',#Да Нет
    'Левосимендан',#Да Нет
    'Мезатон',#Да Нет
    'Экстренный',#не меняем
    'Интегреллин',#не меняем
    'Тромболизис',
    #'Тромболизис у нас',#не меняем
    'ФВ<30%',#не меняем
    'Тирофибан',#не меняем
    'Аортальный стеноз (Градиент)',
    'Аортальный стеноз (Заключение)'
]
#'А-В блокада' - это можно не использовать так как есть признак 'А-В блокаДа (Новый)' который на 2 значения больше заполнен и уже является дихотомическим
'''def categorize_AB(value):
    if value == 'Нет':
        return 0
    else:
        return 1

df_need= df_need.copy()
df_need['А-В блокада категория'] = df_need['А-В блокада'].apply(categorize_AB)'''

#Исправляем столбец РЕКОРД и CADILLAC
#Создаем mapping для замены
_mapping = {
        'Нет': 0,
        'Да': 1,
        '0': 0,
        '1': 1,
        0: 0,
        1: 1
    }

# Заменяем значения
df_need['РЕКОРД (Низкий риск)'] = df_need['РЕКОРД (Низкий риск)'].replace(_mapping)
df_need['РЕКОРД (Высокий риск)'] = df_need['РЕКОРД (Высокий риск)'].replace(_mapping)

df_need['CADILLAC (Низкий риск)'] = df_need['CADILLAC (Низкий риск)'].replace(_mapping)
df_need['CADILLAC (Средний риск)'] = df_need['CADILLAC (Средний риск)'].replace(_mapping)
df_need['CADILLAC (Высокий риск)'] = df_need['CADILLAC (Высокий риск)'].replace(_mapping)


# Обогащаем парные признаками, заполняя пропуски в одном значением из другого
df_need['Курит'] = df_need['Курит'].fillna(df_need['Smoking'])
df_need['Тромболизис_x'] = df_need['Тромболизис_x'].fillna(df_need['Тромболизис_y'])
# Заменяем все числовые значения на соответствующие строки
df_need['Тромболизис_x'] = df_need['Тромболизис_x'].replace({
    1: 'Да',
    0: 'Нет',
    '1': 'Да',
    '0': 'Нет'
})
# Переименовываем объединенные признаки
df_need = df_need.rename(columns={'Тромболизис_x': 'Тромболизис'})

# Закодируем вручную дихотомические признаки с учетом особенностей
for col in dichotomous_features:
    if col in df_need.columns:
        unique_vals = df_need[col].dropna().unique()

        if set(unique_vals) == {'Да', 'Нет'}:
            # Особые случаи где "Нет" = 1, "Да" = 0
            if col in ['Тромболизис', 'Стенокардия (ИБ)', 'МКБ', 'Общий анализ крови_экспресс раньше операции',
                      'Инфаркт-зависимая артерия(Огригированная)2', 'Курит',
                      'Медицинская помощь оказана за первые 4 часа', 'Гипертоническая болезнь',
                      'GRACE (Низкий риск)', 'GRACE (Средний риск)',
                      'TIMI (Летальность) (Низкий риск)', 'TIMI (Летальность) (Средний риск)',
                      'PAMI (Низкий риск)', 'PAMI (Средний риск)',
                      'CADILLAC (Низкий риск)', 'CADILLAC (Средний риск)',
                      'РЕКОРД (Низкий риск)', 'Экстренный']:
                df_need[col] = df_need[col].replace({'Нет': 1, 'Да': 0})
            else:
                df_need[col] = df_need[col].replace({'Да': 1, 'Нет': 0})

        elif set(unique_vals) == {'М', 'Ж'}: #Пол
            df_need[col] = df_need[col].replace({'М': 0, 'Ж': 1})

        elif set(unique_vals) == {'Задний', 'Передний'}: #Вид STEMI
            df_need[col] = df_need[col].replace({'Задний': 0, 'Передний': 1})

        elif set(unique_vals) == {'Правый бассейн', 'Передний бассейн'}:
            df_need[col] = df_need[col].replace({'Правый бассейн': 1, 'Передний бассейн': 0}) #Инфаркт-зависимая артерия(Огригированная)2


#категориальные признаки
categorical_features=[
    'Инфаркт-зависимая артерия',
    'Количество пораженных сосудов(Syntax)',
    'Количество пораженных сосудов(Значимость)',
    'TIMI категория',
    'CADILLAC категория',
    'РЕКОРД категория',
    'PAMI категория',
    'TIMI Летальность категория',
    #'ХСН фк',
    'Вид операции(ИБ)(Новый)',
    'Исход заболевания',
    #'Сопутствующие1',
    'Инфаркт-зависимая артерия(Огригированная)',
    'KDIGO',
    'Baun',
    'MKB категория',
    'APACHE2 выписка категория',
    'APACHE2 1сутки категория',
    'APACHE2 3дня категория',
    'Экстренная операция(ИБ)(Новый)', #экстренная/плановая и Да
    'ГБ стадия категория',
    'ГБ риск категория'

]


#переделаем некоторые категориальные признаки
#МКВ
def categorize_MKB(value):
    if value in ['C18.9', 'C25.2',  'C34.3', 'C34.9', 'C50.0', 'C67.9', 'C90.0', 'D33.3']:
        return 'КЛАСС III БОЛЕЗНИ КРОВИ, КРОВЕТВОРНЫХ ОРГАНОВ И ОТДЕЛЬНЫЕ НАРУШЕНИЯ, ВОВЛЕКАЮЩИЕ ИММУННЫЙ МЕХАНИЗМ (D50-D89)'
    elif value in ['E05.0', 'E10.0', 'E10.6', 'E10.7', 'E11.6', 'E11.7','E13.7'  ]:
        return 'КЛАСС IV БОЛЕЗНИ ЭНДОКРИННОЙ СИСТЕМЫ, РАССТРОЙСТВА ПИТАНИЯ И НАРУШЕНИЯ ОБМЕНА ВЕЩЕСТВ (E00-E90)'
    elif value in ['G09.0', 'G23.8', 'G25.5', 'G31.0', 'G37.8', 'G45.0', 'G46.0',  'G55.1', 'G55.3', 'G56.1', 'G90.0', 'G93.4' ]:
        return 'КЛАСС VI БОЛЕЗНИ НЕРВНОЙ СИСТЕМЫ (G00-G99)'
    elif value in ['I20.0','I20.00','I20.8','I20.80','I20.9', 'I21.0', 'I21.00', 'I21.1', 'I21.10', 'I21.2', 'I21.3',  'I21.4',  'I21.40',
                 'I21.9', 'I21.90', 'I22.0', 'I22.00', 'I22.1', 'I22.10','I22.8', 'I22.80', 'I22.9', 'I22.90', 'I23.8','I24.0', 'I24.8', 'I25.0', 'I25.1', 'I25.2', 'I25.5',  'I25.50', 'I25.6', 'I25.8', 'I26.0', 'I26.9', 'I27.0', 'I27.9', 'I31.0', 'I32.0', 'I33.0', 'I33.9', 'I34.0', 'I34.2', 'I35.0' , 'I35.1', 'I35.2', 'I39.0','I40.0', 'I41.8', 'I42.0', 'I42.1', 'I42.2', 'I42.7', 'I42.8', 'I42.9', '143.0', '143.1', '144.0', '144.2', '144.3', '144.7', '145.2', '145.5' , '145.6', '145.8', '147.0' , '147.1', '147.2', '147.9', '148.0', '148.1', '148.2', '148.9', '149.0', '149.3', '149.4', '149.5', '149.8', '149.9', '150.0', '150.9', '151.9', 'I61.0', 'I61.1', 'I61.3', 'I63.3', 'I63.4', 'I61.40', 'I63.40', 'I63.9','I69.3', 'I63.5', 'I67.8', 'I67.9', 'I69.0', 'I69.8', 'I69.80', 'I70.0', 'I70.2', 'I70.9', 'I73.8',  'I82.8', 'I83.9', 'I11.0', 'I11.9']:
        return 'КЛАСС IX БОЛЕЗНИ СИСТЕМЫ КРОВООБРАЩЕНИЯ (I00-I99)'
    elif value in ['J11.1','J84.0', 'J47.0', 'J15.4', 'J18.0', 'J90.0', 'J45.0', 'J44.0', 'J44.9', 'J84.9', 'J45.9', 'J13.0' ]:
        return 'КЛАСС X БОЛЕЗНИ ОРГАНОВ ДЫХАНИЯ (J00-J99)'
    elif value in [ 'K80.0', 'K86.1', 'K80.1','K50.1', 'K57.2', 'K63.2', 'K82.8','K52.9', 'K73.8', 'K25.4', 'K74.0', 'K22.1','K57.3','K74.6','K26.2', 'K51.1','K85.0','K21.0', 'K58.9', 'K26.0', 'K56.0', 'K51.0', 'K82.9' ]:
        return 'КЛАСС XI БОЛЕЗНИ ОРГАНОВ ПИЩЕВАРЕНИЯ (K00-K93)'
    elif value in [ 'M07.0', 'M16.1', 'M15.0', 'M42.1', 'M05.0', 'M06.0',  'M02.9', 'M05.3', 'M33.2', 'M02.0', 'M42.0', 'M48.9', 'M34.9', 'M51.0', 'M45.0']:
        return 'КЛАСС XIII БОЛЕЗНИ КОСТНО-МЫШЕЧНОЙ СИСТЕМЫ И СОЕДИНИТЕЛЬНОЙ ТКАНИ (M00-M99)'
    elif value in [ 'N20.1', 'N83.9', 'N73.9', 'N20.9', 'N40.0', 'N11.0', 'N13.3', 'N83.1',  'N31.2']:
        return 'КЛАСС XIV БОЛЕЗНИ МОЧЕПОЛОВОЙ СИСТЕМЫ (N00-N99)'
    elif value in ['S06.3', 'S06.6', 'S30.0', 'S06.0', 'S82.6', 'S72.0',  'S82.8', 'T84.1' ]:
        return 'КЛАСС XIX ТРАВМЫ, ОТРАВЛЕНИЯ И НЕКОТОРЫЕ ДРУГИЕ ПОСЛЕДСТВИЯ ВОЗДЕЙСТВИЯ ВНЕШНИХ ПРИЧИН (S00-T98)'
    else:
        'Другие заболевания'

df_need['MKB категория'] = df_need['MKB'].apply(categorize_MKB)
#точно правильно




def categorize_GV_st(value):
    if value in [0.0, 1.0]:
        return 'Низкий уровень'
    elif value in [2.0, 3.0]:
        return 'Средний уровень'
    elif value >= 4.0:
        return 'Высокий уровень'
    else:
        return 'Неизвестно'

df_need['ГБ стадия категория'] = df_need['ГБ стадия'].apply(categorize_GV_st)


def categorize_GV_r(value):
    if value in [0.0, 1.0, 2.0]:
        return 'Низкий уровень'
    elif value in [3.0, 4.0, 5.0]:
        return 'Средний уровень'
    elif value >= 6.0:
        return 'Высокий уровень'
    else:
        return 'Неизвестно'

df_need['ГБ риск категория'] = df_need['ГБ риск'].apply(categorize_GV_r)

def categorize_cadillac(value):
    if value in [0.0, 1.0, 2.0]:
        return 'Низкий уровень'
    elif value in [3.0, 4.0, 5.0]:
        return 'Средний уровень'
    elif value >= 6.0:
        return 'Высокий уровень'
    else:
        return 'Неизвестно'

df_need['CADILLAC категория'] = df_need['CADILLAC'].apply(categorize_cadillac)


def categorize_record(value):
    if value in [0.0, 1.0]:
        return 'Низкий риск'
    elif value in [2.0]:
        return 'Умеренный риск'
    elif value in [3.0]:
        return 'Высокий риск'
    elif value >= 4.0:
        return 'Очень высокий'
    else:
        return 'Неизвестно'

df_need['РЕКОРД категория'] = df_need['РЕКОРД'].apply(categorize_record)



def categorize_pami(value):
    if value in [0, 1, 2, 3]:
        return 'Низкий риск'
    elif value in [4, 5, 6]:
        return 'Средний риск'
    elif value >= 7:
        return 'Высокий риск'
    else:
        return 'Неизвестно'

df_need['PAMI категория'] = df_need['PAMI'].apply(categorize_pami)


def timi_to_binary(value):
    """
    Преобразует TIMI в бинарный признак для модели.
    Возвращает:
    0 — неуспешная реперфузия (высокий риск)
    1 — успешная реперфузия (низкий риск)
    """
    if value in [0.0, 1.0, 2.0]:
        return 0  # Неуспех / высокий риск
    elif value == 3.0:
        return 1  # Успех / низкий риск
    else:
        return None  # пропуск или ошибка


def categorize_timi_deth(value):
    if value in [0.0, 1.0, 2.0]:
        return 'Низкий риск'
    elif value in [3.0, 4.0]:
        return 'Умеренный риск'
    elif value in [5.0, 6.0]:
        return 'Высокий риск'
    elif value >= 7.0 :
        return 'Очень высокий риск'
    else:
        return 'Неизвестно'

df_need['TIMI категория'] = df_need['TIMI'].apply(timi_to_binary)
df_need['TIMI Летальность категория'] = df_need['TIMI (Летальность)'].apply(categorize_timi_deth)



def categorize_apache2(score):
    if score <= 10:
        return 'Низкий риск (0-10)'
    elif 11 <= score <= 16:
        return 'Умеренный риск (11-16)'
    elif 17 <= score <= 24:
        return 'Высокий риск (17-24)'
    elif score > 24:
        return 'Критический риск (25+)'
    else:
        return 'Неизвестно'
#ЕА проверил
df_need= df_need.copy()
df_need['APACHE2 выписка категория'] = df_need['APACHE2 выписка'].apply(categorize_apache2)
df_need['APACHE2 1сутки категория'] = df_need['APACHE2 1сутки'].apply(categorize_apache2)
df_need['APACHE2 3дня категория'] = df_need['APACHE2 3дня'].apply(categorize_apache2)




df_need = df_need.rename(columns={'Age':'Возраст',
                        'Sex':'Пол',
                        'Инсульт (Выгрузка из ИБ - временный столбец)': 'Инсульт',
                        'Ишемический инсульт (Выгрузка из ИБ - временный столбец)':'Ишемический инсульт',
                        'Экстренная операция(ИБ)(Новый)':'Экстренная операция',
                        'ХОБЛ (Новый столбец)':'ХОБЛ',
                        'Стенокардия (ИБ)':'Стенокардия',
                        'Геморрагический инсульт (Выгрузка из ИБ - временный столбец)':'Геморрагический инсульт',
                        'А-В блокаДа (Новый)':'А-В блокаДа'})

/tmp/ipykernel_91920/1630583476.py:204: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need['РЕКОРД (Низкий риск)'] = df_need['РЕКОРД (Низкий риск)'].replace(_mapping)
/tmp/ipykernel_91920/1630583476.py:205: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need['РЕКОРД (Высокий риск)'] = df_need['РЕКОРД (Высокий риск)'].replace(_mapping)
/tmp/ipykernel_91920/1630583476.py:207: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need['CADILLAC (Низкий риск)'] = df_need['CADILLAC (Низкий риск)'].replace(_mapping)
/tmp/ipykernel_91920/1630583476.py:208: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need['CADILLAC (Средний риск)'] = df_need['CADILLAC (Средний риск)'].replace(_mapping)
/tmp/ipykernel_91920/1630583476.py:209: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need['CADILLAC (Высокий риск)'] = df_need['CADILLAC (Высокий риск)'].replace(_mapping)
/tmp/ipykernel_91920/1630583476.py:242: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need[col] = df_need[col].replace({'Да': 1, 'Нет': 0})
/tmp/ipykernel_91920/1630583476.py:245: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need[col] = df_need[col].replace({'М': 0, 'Ж': 1})
/tmp/ipykernel_91920/1630583476.py:248: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need[col] = df_need[col].replace({'Задний': 0, 'Передний': 1})
/tmp/ipykernel_91920/1630583476.py:240: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need[col] = df_need[col].replace({'Нет': 1, 'Да': 0})
/tmp/ipykernel_91920/1630583476.py:251: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_need[col] = df_need[col].replace({'Правый бассейн': 1, 'Передний бассейн': 0}) #Инфаркт-зависимая артерия(Огригированная)2

In [49]:
df_need.to_excel('отфильтрованая таблица 19_04_26 с Killip.xlsx')

In [50]:
df_need.shape

(5882, 203)

In [229]:
#выведем для проверки КШ развился и не развился
print(len(list(df_need[df_need['КШ развился в реанимации']==1]['Код пациента'].unique())))
print(len(list(df_need[df_need['КШ развился в реанимации']==0]['Код пациента'].unique())))

200
5669

In [230]:
#Список столбцов для удаления и здесь же удалим столбцы
columns_to_drop = [
    'Killip',
    'killip',
    'Класс ОСН по Killip',
    'Код пациента'
]

#удаление столбцов
df_need = df_need.copy()
df_need.drop(axis='columns', columns=columns_to_drop, inplace=True)

df_need.to_excel('отфильтрованая таблица 19_04_26 без Killip.xlsx')